(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.RubizhModel=factory();})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const VERSION=1, text=x=>String(x??'').trim(), key=x=>text(x).normalize('NFKC').toLowerCase().replace(/[’`]/g,"'").replace(/\s+/g,' '), unique=a=>[...new Set(a.filter(Boolean))], clone=x=>JSON.parse(JSON.stringify(x)), ids=x=>unique(Array.isArray(x)?x.map(text):text(x).split(/[,\n]/).map(text));
const COLORS={'Чорний':['black','чорний','черный','чёрный'],'Олива':['olive','олива','olive drab','оливковий','оливковый'],'Койот':['coyote','койот'],'Хакі':['khaki','хаки','хакі'],'Коричневий':['brown','коричневий','коричневый'],'Сірий':['grey','gray','сірий','серый'],'Білий':['white','білий','белый'],'Зелений':['green','зелений','зеленый'],'Синій':['blue','синій','синий'],'Темно-синій':['dark navy','navy','темно-синій','темно-синий'],'Пісочний':['tan','пісочний','песочный'],'Світлий койот':['light coyote','світлий койот','светлый койот'],'Темна олива':['темна олива','темная олива','dark olive'],'Графіт':['graphite','графіт','графит']};
const CAMOUFLAGES={'Мультикам':['multicam','мультикам'],'ММ14':['мм14','mm14','мм-14','mm-14'],'Піксель':['піксель','пиксель','pixel'],'Мультикам Black':['multicam black','black multicam','чорний мультикам','черный мультикам'],'Мультикам Tropic':['multicam tropic','multicam tropical'],'Woodland':['woodland','вудленд']};
for(const pattern of ["Темний мультикам", "Білий мультикам", "Світлий мультикам", "Осінній мультикам", "Зелений мультикам", "Зимовий мультикам", "Мультикам грязь", "Степной мультикам", "Зелений камуфляж", "Темний камуфляж", "Весняний камуфляж", "Камуфляж земля", "Хижак", "Хижак Піксель", "Зелене листя", "Осіннє листя", "Дубове листя", "Хвойний ліс", "Альпийская клякса"]){CAMOUFLAGES[pattern]=[pattern];}
CAMOUFLAGES['Мультикам бруд']=['мультикам грязь','мультикам бруд'];CAMOUFLAGES['Степовий мультикам']=['степной мультикам','степовий мультикам'];CAMOUFLAGES['Альпійська пляма']=['альпийская клякса','альпійська пляма'];
// Explicit supplier spellings; distinct shades stay distinct.
Object.assign(COLORS,{'Червоний':['red','красный','червоний'],'Помаранчевий':['orange','оранжевый','помаранчевий'],'Жовтий':['yellow','желтый','жёлтый','жовтий'],'Бежевий':['beige','бежевый','бежевий'],'Блакитний':['light blue','голубой','блакитний'],'Рожевий':['pink','розовый','рожевий'],'Бузковий':['lilac','сиреневый','бузковий'],'Бордовий':['burgundy','бордовый','бордовий'],'Сріблястий':['silver','серебристый','сріблястий'],'Прозорий':['transparent','прозрачный','прозорий'],'Жовто-блакитний':['жовто-блакитний','жовто блакитний'],'Армійський зелений':['army green'],'Ranger Green':['ranger green'],'Темний хакі':['темний-хаки','темний хакі','темный хаки'],'Сіро-золотий':['сіро-золотий'],'Чорний з принтом':['чорний з принтом']});
COLORS['Олива'].push('od green');COLORS['Ranger Green'].push('рейнджер грін','рейнджер грин');COLORS['Темний хакі'].push('темний-хакі');CAMOUFLAGES['Альпийская клякса'].push('альпійська клякса');COLORS['Хакі'].push('хакi');COLORS['Темно-синій'].push('dark navy blue');COLORS['Пісочний'].push('sand');
CAMOUFLAGES['Мультикам'].push('камуфляж мультикам');CAMOUFLAGES['Піксель'].push('камуфляж піксель','камуфляж пиксель');CAMOUFLAGES['Woodland'].push('pl вудленд');CAMOUFLAGES['Хижак'].push('хищник');CAMOUFLAGES['Осіннє листя'].push('листя осінь');CAMOUFLAGES['Весняний мультикам']=['мультикам весна','весняний мультикам'];CAMOUFLAGES['Vegetato']=['vegetato'];CAMOUFLAGES['Kryptek']=['криптек','kryptek'];
const ATTR_KEYS={season:['сезон','сезонність','season'],material:['матеріал','материал','material'],membrane:['мембрана','membrane'],gender:['стать','пол','gender'],volume_l:['об’єм','об\'єм','объем','обʼєм','volume_l'],protection_class:['клас захисту','класс защиты','protection_class'],plate_size:['розмір плити','размер плиты','plate_size'],plate_size_supported:['сумісні розміри плит','поддерживаемые размеры плит','plate_size_supported'],helmet_size:['розмір шолома','размер шлема','helmet_size'],helmet_rail_type:['тип рейок шолома','helmet_rail_type'],helmet_shell_type:['тип оболонки шолома','helmet_shell_type'],rail_type:['тип рейки','rail_type'],radio_connector:['розʼєм рації','роз\'єм рації','разъем рации','radio_connector'],ptt_connector:['розʼєм ptt','разъем ptt','ptt_connector'],connector:['розʼєм','разъем','connector'],battery_type:['тип батареї','тип батареи','battery_type'],charger_type:['тип зарядного пристрою','charger_type'],mount_standard:['стандарт кріплення','mount_standard'],lumens:['світловий потік','люмени','люмены','lumens'],waterproof_rating:['водозахист','waterproof_rating'],molle:['molle','молле'],quick_release:['швидке скидання','быстрый сброс','quick_release'],hood:['капюшон','hood'],insulation:['утеплювач','утеплитель','insulation'],color:['колір','цвет','color'],camouflage:['камуфляж','camouflage']};
const TYPE_BY_CATEGORY={clothing_insulated_vests:'clothing',footwear_shoes:'shoes',armor_ballistic_blankets:'ballistic_blanket',footwear_care:'shoe_care',communications_earplugs:'earplugs',electronics_rf_detectors:'rf_detector',symbols_flags:'flag',field_watches:'watch',clothing_combat_shirts:'combat_shirt',clothing_pants:'pants',clothing_jackets:'jacket',clothing_fleece:'fleece',clothing_thermal:'base_layer',clothing_socks:'socks',clothing_gloves:'gloves',footwear_tactical_boots:'boots',footwear_socks:'socks',footwear_boots:'boots',footwear_sneakers:'shoes',armor_plate_carriers:'plate_carrier',armor_vests:'armor_vest',armor_plates:'armor_plate',armor_soft:'soft_armor',helmets_ballistic:'helmet',communications_headsets:'headset',communications_ptt:'radio_ptt',communications_radios:'radio',bags_backpacks:'backpack',bags_assault_backpacks:'backpack',medical_tourniquets:'tourniquet',medical_ifak:'ifak',power_flashlights:'flashlight',tools_flashlights:'flashlight',lighting_handheld:'flashlight',lighting_headlamps:'flashlight',lighting_tactical:'flashlight',load_bearing_belts:'battle_belt',load_bearing_rps:'rps',protection_knee:'knee_protection',eye_glasses:'eye_protection',eye_goggles:'eye_protection'};
const COMPONENTS={combat_shirt:'combat_shirt',pants:'pants',jacket:'outer_layer',fleece:'fleece',base_layer:'base_layer',boots:'footwear',shoes:'footwear',socks:'socks',plate_carrier:'carrier',armor_vest:'carrier',armor_plate:'plates',helmet:'helmet',headset:'hearing',backpack:'backpack',ifak:'ifak',tourniquet:'tourniquet',gloves:'gloves',eye_protection:'eye_protection',battle_belt:'battle_belt',rps:'rps',pouch:'pouch',knee_protection:'knee_protection'};
const RELATION_TYPES=['compatible','recommended_with','alternative','replacement','bundle','incompatible'];
const BOOL=new Map([['yes',true],['так',true],['да',true],['true',true],['є',true],['1',true],['ні',false],['нет',false],['no',false],['false',false],['немає',false],['0',false]]);
// Same first-match-in-order result as scanning the dictionary, via a lazily built index (rebuilt if the dictionary changes).
const ALIAS_INDEX=new WeakMap();
function aliasIndex(dictionary){const frozen=Object.isFrozen(dictionary)&&ALIAS_INDEX.get(dictionary);if(frozen)return frozen.map;const entries=Object.entries(dictionary),size=entries.reduce((n,[,list])=>n+1+list.length,0),cached=ALIAS_INDEX.get(dictionary);if(cached&&cached.size===size&&cached.keys===entries.length)return cached.map;const map=new Map();for(const [canonical,list] of entries){const k=key(canonical);for(const n of [k,...list.map(key)])if(!map.has(n))map.set(n,canonical);}ALIAS_INDEX.set(dictionary,{size,keys:entries.length,map});return map;}
function alias(value,dictionary){return aliasIndex(dictionary).get(key(value))||null;}
function palette(raw,rawCamouflage=''){
 const values=text(raw).split(/\s*(?:\/|;|\+|,)\s*/).filter(Boolean),colors=[],patterns=[],unknown=[];
 for(const v of [...values,...text(rawCamouflage).split(/\s*[;,]\s*/).filter(Boolean)]){const c=alias(v,COLORS),cam=alias(v,CAMOUFLAGES);if(cam)patterns.push(cam);else if(c)colors.push(c);else unknown.push(v);}
 return {color:unique(colors).join(' / ')||null,camouflage:unique(patterns).join(' / ')||null,unknown:unique(unknown)};
}
// Same result as Object.keys(ATTR_KEYS).find(f=>f===rawKey||aliases match): the earliest field wins either way.
let ATTR_FIELD_INDEX=null;
function attributeField(rawKey){
 const fields=Object.keys(ATTR_KEYS),size=fields.reduce((n,f)=>n+ATTR_KEYS[f].length,0);
 if(!ATTR_FIELD_INDEX||ATTR_FIELD_INDEX.fields!==fields.length||ATTR_FIELD_INDEX.size!==size){const byAlias=new Map(),pos=new Map();fields.forEach((f,i)=>{pos.set(f,i);for(const a of ATTR_KEYS[f]){const k=key(a);if(!byAlias.has(k))byAlias.set(k,i);}});ATTR_FIELD_INDEX={fields:fields.length,size,byAlias,pos,list:fields};}
 const exact=ATTR_FIELD_INDEX.pos.get(rawKey),byAlias=ATTR_FIELD_INDEX.byAlias.get(key(rawKey)),best=Math.min(exact??Infinity,byAlias??Infinity);
 return Number.isFinite(best)?ATTR_FIELD_INDEX.list[best]:undefined;
}
function attributes(raw={},manual={}){
 const out={},unknown=[],conflicts=[];
 for(const [rawKey,value] of Object.entries(raw)){const field=attributeField(rawKey);if(!field||value==null||value==='')continue;let v=value;
  if(field==='season'){const values={winter:['winter','зима','зимовий','зимний'],summer:['summer','літо','лето','літній','летний'],demiseason:['demiseason','демісезон','демисезон'],all_season:['all_season','всесезонний','всесезонный','all season']};v=alias(value,values)||text(value);}
  if(field==='gender'){v=alias(value,{male:['male','чоловічий','мужской'],female:['female','жіночий','женский'],unisex:['unisex','унісекс','унисекс']})||text(value);}
  if(['molle','quick_release','hood','membrane'].includes(field)){v=typeof value==='boolean'?value:BOOL.get(key(value));if(v===undefined){unknown.push({field,raw:value});continue;}}
  if(['volume_l','lumens'].includes(field)){const match=/^\s*(\d+(?:[.,]\d+)?)\s*(?:л|l|літрів|литров|lm|лм|люменів)?\s*$/iu.exec(text(value));if(!match){unknown.push({field,raw:value});continue;}v=+match[1].replace(',','.');if(v<=0){conflicts.push({field,raw:value});continue;}}
  if(out[field]!==undefined&&JSON.stringify(out[field])!==JSON.stringify(v)){delete out[field];conflicts.push({field,raw:value});continue;}if(!conflicts.some(c=>c.field===field))out[field]=v;
 }
 const c=palette(out.color,out.camouflage);if(out.color||out.camouflage){out.color=c.color;out.camouflage=c.camouflage;unknown.push(...c.unknown.map(raw=>({field:'color_camouflage',raw})));}
 Object.assign(out,clone(manual));return {values:out,unknown,conflicts};
}
function type(category,name=''){return TYPE_BY_CATEGORY[category]||(category?.startsWith('pouches_')?'pouch':category?.startsWith('bags_')?'bag':category?.startsWith('clothing_')?'clothing':null);}
function size(raw,productType,options={}){
 const source=text(raw),n=source.toUpperCase().replace(/Х/g,'X').replace(/\s+/g,''),need=/^(?:combat_shirt|pants|jacket|fleece|base_layer|clothing|boots|shoes|gloves|helmet)$/.test(productType||'');let system=null,normalized=null,unconfirmed=false;
 const paired=/^(\d{2}(?:[-/]\d{2})?)\s*(?:\(\s*)?(XXS|XS|S|M|L|XL|XXL|XXXL|[2-5]XL)\s*\)?$/iu.exec(source),fit=/^(XXS|XS|S|M|L|XL|XXL|XXXL|[2-5]XL)\s*\((LONG|REGULAR|SHORT)\)$/iu.exec(source),numericHeight=/^(\d{2}(?:[-/]\d{2})?)\s*[/]\s*([1-6](?:[-/]?[1-6])?)$/u.exec(source);
 const explicitUniversal=/^(?:OS|ONE SIZE|ONE-SIZE|УНІВЕРСАЛЬНИЙ|УНИВЕРСАЛЬНЫЙ|ОДИН РОЗМІР|ОДИН РАЗМЕР)$/iu.test(source);
 if(paired&&/^(?:combat_shirt|pants|jacket|fleece|base_layer|clothing)$/.test(productType||'')){system='clothing_numeric';normalized=paired[1];}
 else if(fit&&!['boots','shoes','helmet'].includes(productType)){system=productType==='gloves'?'gloves':'clothing_alpha';normalized=fit[1].toUpperCase().replace(/XXXL/g,'3XL').replace(/XXL/g,'2XL');}
 else if(numericHeight&&!['boots','shoes','helmet'].includes(productType)){system='clothing_numeric';normalized=numericHeight[1];}
 else if(!source){unconfirmed=need;}
 else if(explicitUniversal){system='universal';normalized='OS';unconfirmed=need&&options.universalConfirmed!==true;}
 else if(/^(?:XXS|XS|S|M|L|XL|XXL|XXXL|2XL|3XL|4XL|5XL)(?:[-/](?:XXS|XS|S|M|L|XL|XXL|XXXL|2XL|3XL|4XL|5XL))*$/.test(n)){system=productType==='gloves'?'gloves':'clothing_alpha';normalized=n.replace(/XXXL/g,'3XL').replace(/XXL/g,'2XL');}
 else if(productType==='gloves'&&/^(?:[6-9]|1[0-3])$/.test(n)){system='gloves';normalized=+n;}
 else if(['boots','shoes'].includes(productType)&&/^\d{2}(?:[.,]5)?$/.test(n)&&+n.replace(',','.')>=20&&+n.replace(',','.')<=55){system='eu_shoes';normalized=+n.replace(',','.');}
 else if(productType==='helmet'&&/^\d{2}(?:[-/]\d{2})?\s*(?:CM|СМ)?$/.test(n)){system='helmet_cm';normalized=n.replace(/CM|СМ/g,'');}
 else if(/^\d{2}(?:[-/]\d{2})?(?:[-/]\d{3})?$/.test(n)&&!['boots','shoes','helmet'].includes(productType)){system=productType==='gloves'?'gloves':'clothing_numeric';normalized=n;}
 else {unconfirmed=need;}
 return {size_raw:source,size_display:source||null,size_normalized:normalized,size_system:system,size_type:system,size_alpha:paired&&system==='clothing_numeric'?paired[2].toUpperCase().replace(/XXXL/g,'3XL').replace(/XXL/g,'2XL'):null,size_fit:fit?fit[2].toLowerCase():null,size_height:numericHeight?numericHeight[2]:null,size_unconfirmed:unconfirmed};
}
function categoryStatus(p){if(p.category_status==='CONFLICT_REVIEW'||p.category_review_status==='CONFLICT_REVIEW')return 'CONFLICT';if(['NEEDS_REVIEW','CONFLICT','UNCLASSIFIED'].includes(p.category_review_status))return p.category_review_status;if(!p.canonical_category_id&&!p.last_confirmed_category_id)return 'UNCLASSIFIED';if(p.category_locked||p.category_source==='manual'||p.catSource==='manual'||p.fieldMeta?.category?.source==='manual')return 'MANUAL_CONFIRMED';return p.category_status==='CONFIRMED'?'AUTO_CONFIRMED':p.category_status||'CONFIRMED';}
function normalized(p,options={}){
 const source=(p.variants||[]).flatMap(v=>Object.values(v.offers||{})).find(o=>o.original_name||o.source_name),category=p.canonical_category_id||p.last_confirmed_category_id||null,productType=p.primary_product_type||type(category,p.name),a=attributes({...p.canonical_attributes,...p.attrs},p.normalized_attributes||{}),pat=palette(a.values.color,a.values.camouflage);
 const compat={...Object.fromEntries(Object.entries(a.values).filter(([k])=>/^(?:plate_size|plate_size_supported|helmet_rail_type|helmet_shell_type|radio_connector|ptt_connector|battery_type|charger_type|mount_standard|molle)$/.test(k))),...(p.compatibility||{})};
 compat.compatible_product_ids=ids(compat.compatible_product_ids);compat.incompatible_product_ids=ids(compat.incompatible_product_ids);
 const relations=(p.relations||[]).filter(r=>RELATION_TYPES.includes(r.type)&&r.product_id&&r.product_id!==p.id),recommended=unique([...ids(p.recommended_with),...relations.filter(r=>r.type==='recommended_with').map(r=>r.product_id)]);
 return {data_model_version:VERSION,source_name_raw:p.source_name_raw??source?.original_name??source?.source_name??p.original_name??p.fieldMeta?.name?.supplierOriginal??p.name??'',normalized_name:text(p.normalized_name||p.name),marketing_name_uk:text(p.marketing_name_uk||p.name),source_description:p.source_description??p.fieldMeta?.desc?.supplierOriginal??p.fieldMeta?.desc?.supplierValue??'',source_language:p.source_language||(/[ыэъё]/iu.test(text(source?.original_name||p.name)+' '+text(p.source_description||source?.source_description))?'ru':'unknown'),translated_description_uk:p.translated_description_uk??p.desc??'',canonical_category_id:category,canonical_category_path:options.path?options.path(category):p.canonical_category_path||p.category||'',classification_source:p.category_source||p.catSource||'unknown',classification_confidence:p.category_confidence??0,classification_reason:(p.category_reasons||[]).join(' · '),category_locked:!!(p.category_locked||p.category_source==='manual'||p.catSource==='manual'||p.fieldMeta?.category?.source==='manual'),category_review_status:categoryStatus(p),last_confirmed_category_id:p.last_confirmed_category_id||category,primary_product_type:productType,filter_attributes:a.values,attribute_warnings:[...a.unknown,...a.conflicts],color:pat.color,camouflage:pat.camouflage,compatibility:compat,kit_component:p.kit_component??COMPONENTS[productType]??null,kit_component_tags:ids(p.kit_component_tags),kit_eligible:p.kit_eligible!==false,kit_priority:Number.isFinite(+p.kit_priority)?Math.min(100,Math.max(0,+p.kit_priority)):0,budget_tier:['basic','optimal','premium'].includes(p.budget_tier)?p.budget_tier:null,recommended_with:recommended,alternative_group:text(p.alternative_group)||null,recommendation_locked:p.recommendation_locked===true,relations};
}
function compatibility(a,b){
 const ac=a.compatibility||{},bc=b.compatibility||{},rels=[...(a.relations||[]).filter(r=>r.product_id===b.id),...(b.relations||[]).filter(r=>r.product_id===a.id)];
 if(ids(ac.incompatible_product_ids).includes(b.id)||ids(bc.incompatible_product_ids).includes(a.id)||rels.some(r=>r.type==='incompatible'))return {status:'incompatible',source:'manual',reason:'Ручна заборона сумісності'};
 if(ids(ac.compatible_product_ids).includes(b.id)||ids(bc.compatible_product_ids).includes(a.id)||rels.some(r=>r.type==='compatible'))return {status:'compatible',source:'manual',reason:'Ручне підтвердження сумісності'};
 const dim=v=>{const m=/^(\d+(?:[.,]\d+)?)\s*[xх×]\s*(\d+(?:[.,]\d+)?)\s*(cm|см|mm|мм)?$/iu.exec(text(v));if(m){const f=/mm|мм/i.test(m[3]||'')?0.1:1;return [+m[1].replace(',','.')*f,+m[2].replace(',','.')*f].sort((a,b)=>a-b).join('x');}return key(v);};
 const pairs=[['plate_carrier','armor_plate','plate_size_supported','plate_size',dim],['helmet','headset','helmet_rail_type','mount_standard',key],['radio','radio_ptt','radio_connector','ptt_connector',key]];
 for(const [at,bt,ak,bk,normalize] of pairs){let first=a,second=b;if(a.primary_product_type===bt&&b.primary_product_type===at){first=b;second=a;}if(first.primary_product_type!==at||second.primary_product_type!==bt)continue;const x=first.compatibility?.[ak],y=second.compatibility?.[bk];if(!x||!y)return {status:'unknown',source:'attributes',reason:'Недостатньо специфікацій сумісності'};if(ak==='plate_size_supported'&&[...(Array.isArray(x)?x:[x]),y].some(v=>/^\d.*[xх×].*\d$/iu.test(text(v))))return {status:'unknown',source:'attributes',reason:'Для розмірів плит не зазначено одиниць'};const xs=(Array.isArray(x)?x:[x]).map(normalize);return {status:xs.includes(normalize(y))?'compatible':'incompatible',source:'attributes',reason:'Порівняння специфікацій'};}
 return {status:'unknown',source:'none',reason:'Сумісність не підтверджена'};
}
function quality(p,variants=[],options={}){
 const n=normalized(p,options),errors=[],warnings=[],checks={category:!!n.canonical_category_id,photos:!!p.photos?.length,price:variants.some(v=>v.site_price>0),variants:variants.length>0,availability:variants.some(v=>v.availability==='in_stock'||v.availability==='preorder'&&v.preorder_confirmed===true),name:!!n.marketing_name_uk,brand:!!p.brand,attributes:Object.keys(n.filter_attributes).length>0,description:!!text(n.translated_description_uk||p.desc),compatibility:!['plate_carrier','armor_plate','helmet','headset','radio','radio_ptt'].includes(n.primary_product_type)||Object.keys(n.compatibility).some(k=>!/_product_ids$/.test(k)&&n.compatibility[k]!=null)||n.compatibility.compatible_product_ids.length>0};
 for(const k of ['category','photos','price','variants','availability','name'])if(!checks[k])errors.push('missing_'+k);
 if(p.variant_grouping_conflict||p.variants?.length>(options.variantLimit||50))errors.push('variant_grouping');
 if(variants.length&&variants.every(v=>v.size_unconfirmed))errors.push('missing_size');
 if(variants.length&&variants.every(v=>v.margin_blocked))errors.push('margin_below_minimum');
 if(['CONFLICT','NEEDS_REVIEW','UNCLASSIFIED'].includes(n.category_review_status))warnings.push('category_review');
 for(const k of ['brand','attributes','description','compatibility'])if(!checks[k])warnings.push('missing_'+k);
 if(n.attribute_warnings.length)warnings.push('attribute_normalization');
 if(variants.some(v=>v.size_unconfirmed))warnings.push('missing_size');
 if(variants.some(v=>v.color_unknown?.length))warnings.push('unknown_color_camouflage');
 if(variants.some(v=>v.price_anomaly))warnings.push('price_anomaly');
 return {quality_score:Object.values(checks).filter(Boolean).length*10,critical_errors:unique(errors),warnings:unique(warnings),publication_readiness:errors.length?'BLOCKED':warnings.length?'READY_WITH_WARNINGS':'READY'};
}
function duplicateCandidates(products){
 const byId=new Map(products.map(p=>[p.id,p])),buckets=new Map(),pairs=new Map(),add=(a,b,evidence,strong)=>{if(a.id===b.id)return;const id=[a.id,b.id].sort().join('|'),item=pairs.get(id)||{status:'POSSIBLE_DUPLICATE',product_ids:[a.id,b.id].sort(),evidence:[],strong:false};item.evidence=unique([...item.evidence,evidence]);item.strong ||= strong;pairs.set(id,item);};
 for(const p of products){const signatures=[];for(const v of p.variants||[])for(const [sid,o] of Object.entries(v.offers||{}))if(o.s)signatures.push(['sku:'+sid+':'+text(o.s),'supplier_sku',true]);if(p.brand&&p.modelArticle)signatures.push(['model:'+key(p.brand)+':'+key(p.modelArticle),'brand_model',true]);if(p.brand&&p.name)signatures.push(['name:'+key(p.brand)+':'+key(p.name),'brand_name',false]);for(const [signature,evidence,strong] of signatures){const prev=buckets.get(signature)||[];for(const other of prev.slice(0,20))add(p,other,evidence,strong);if(!prev.some(x=>x.id===p.id))prev.push(p);buckets.set(signature,prev);}}
 return [...pairs.values()].map(pair=>{const [a,b]=pair.product_ids.map(id=>byId.get(id));if(a.photos?.some(ph=>b.photos?.includes(ph)))pair.evidence.push('shared_photo');return pair;});
}
function filterSchema(category){const base=['brand','color','camouflage'];if(/^clothing_|^footwear_/.test(category))return [...base,'size','season','material','membrane','gender'];if(/^armor_/.test(category))return [...base,'protection_class','plate_size','plate_size_supported','material','quick_release','molle'];if(/^helmets_/.test(category))return [...base,'helmet_size','helmet_rail_type','helmet_shell_type','protection_class'];if(/^communications_/.test(category))return [...base,'connector','radio_connector','ptt_connector','mount_standard'];if(/^bags_/.test(category))return [...base,'volume_l','material','molle'];return [...base,'material'];}
// Built-in dictionaries are complete here; freezing them lets alias indexes never go stale.
for(const d of [COLORS,CAMOUFLAGES,ATTR_KEYS]){for(const list of Object.values(d))Object.freeze(list);Object.freeze(d);}
return {VERSION,COLORS,CAMOUFLAGES,ATTR_KEYS,TYPE_BY_CATEGORY,COMPONENTS,RELATION_TYPES,palette,attributes,size,type,normalized,categoryStatus,quality,compatibility,duplicateCandidates,filterSchema,ids};
});
