// Production release: controlled migration on the existing production store.
const PRODUCTION_RELEASE_VERSION='10.9.3',PRODUCTION_RC_COMMIT='440aa60ee42795ba8bf5167d8121470a5a56aab3';
const PRODUCTION_SYNC_ENABLED=false,PRODUCTION_AUTOPRICES_ENABLED=false;
const PRODUCTION_MIGRATION={state:'loading',plan:null,lastReport:null,error:'',backupId:null};
const releaseStorage=RubizhReleaseStorage;
function productionMode(){return PIM_RELEASE_CHANNEL==='production';}
function productionRowsData(rows){
 const cfg=rows.find(x=>x.key==='meta/config')?.data;
 const collect=(prefix,field,key)=>{const list=[],ids=new Set();for(const r of rows.filter(x=>x.key.startsWith(prefix+'/')))for(const x of Object.values(r.data?.[field]||{})){if(!x[key]||ids.has(x[key]))throw Error('INVALID_EXISTING_ID: '+prefix+' '+(x[key]||''));ids.add(x[key]);list.push(releaseStorage.clone(x));}return list;};
 return {cfg:releaseStorage.clone(cfg||{}),products:collect('cat','products','id'),queue:collect('queue','items','k'),content:collect('content','items','k'),logs:rows.filter(x=>x.key.startsWith('logs/')).map(x=>releaseStorage.clone(x.data)),docs:releaseStorage.clone(rows.find(x=>x.key==='docs/index')?.data||[])};
}
function productionHydrate(data){
 S.cfg=Object.assign(releaseStorage.clone(DEFAULT_CFG),releaseStorage.clone(data.cfg));S.products=new Map(data.products.map(p=>[p.id,releaseStorage.clone(p)]));S.queue=new Map(data.queue.map(x=>[x.k,releaseStorage.clone(x)]));S.content=new Map(data.content.map(x=>[x.k,releaseStorage.clone(x)]));S.logs=releaseStorage.clone(data.logs);S.docs=new Map((data.docs||[]).map(x=>[x.id,releaseStorage.clone(x)]));
 S.snap=null;S.imp=null;S.lastUndo=null;S.cfgDirty=false;S.dirtyCat=new Set();S.dirtyQ=new Set();S.dirtyC=new Set();rebuildIndex();bumpData();
}
function productionProtected(data){
 const manual=x=>({category_locked:x.category_locked,category_source:x.category_source==='manual'?x.category_source:undefined,catSource:x.catSource==='manual'?x.catSource:undefined,manual_locks:x.manual_locks,manualFields:x.manualFields,manual_values:Object.fromEntries([...new Set([...Object.keys(x.manual_locks||{}),...Object.keys(x.manualFields||{}),...Object.keys(x.fieldMeta||{})])].filter(k=>x.manual_locks?.[k]||x.manualFields?.[k]||x.fieldMeta?.[k]?.source==='manual').map(k=>[k,x[k]])),locked_category:x.category_locked?{id:x.canonical_category_id,path:x.category}:undefined,fieldMeta:Object.fromEntries(Object.entries(x.fieldMeta||{}).filter(([,v])=>v.source==='manual'))});
 return [...data.products].sort((a,b)=>a.id.localeCompare(b.id)).map(p=>({id:p.id,name:p.name,brand:p.brand,desc:p.desc,attrs:p.attrs,photos:p.photos,photoMeta:p.photoMeta,colors:p.colors,color_galleries:p.color_galleries,publication:{pub:p.pub,ads:p.ads,archived:p.archived,archiveReason:p.archiveReason,archivePrevPub:p.archivePrevPub,syncStatus:p.syncStatus,simple_excluded_reason:p.simple_excluded_reason},manual:manual(p),variants:(p.variants||[]).map(v=>({sku:v.sku,price:v.price,color:v.color,photos:v.photos,barcode:v.barcode,manual:manual(v),offers:Object.entries(v.offers||{}).map(([sid,o])=>({sid,fields:Object.fromEntries(Object.entries(o).filter(([k])=>k!=='last_valid_inventory_observation'))}))}))}));
}
function productionPrices(){return [...S.products.values()].sort((a,b)=>a.id.localeCompare(b.id)).map(p=>[p.id,p.variants.map(v=>[v.sku,calc(p,v).price])]);}
function productionAssertPreserved(before,after,pricesBefore,pricesAfter){
 const oldProducts=new Map(before.products.map(p=>[p.id,p])),newProducts=new Map(after.products.map(p=>[p.id,p]));if(oldProducts.size!==before.products.length||newProducts.size!==after.products.length||oldProducts.size!==newProducts.size)throw Error('MIGRATION_PROTECTED_DATA_CHANGED');for(const [id,p] of oldProducts){const q=newProducts.get(id);if(!q||stableValue105(productionProtected({products:[p]}))!==stableValue105(productionProtected({products:[q]})))throw Error('MIGRATION_PROTECTED_DATA_CHANGED');}
 if(stableValue105(pricesBefore)!==stableValue105(pricesAfter))throw Error('MIGRATION_CALCULATED_PRICES_CHANGED');
 for(const c of before.cfg.canonical_categories||[])if(stableValue105(c)!==stableValue105(after.cfg.canonical_categories.find(x=>x.id===c.id)))throw Error('MIGRATION_CATEGORY_CHANGED: '+c.id);
 for(const k of ['supplier_category_mapping','confirmed_supplier_size_rules','aliases','category_aliases','kits','kit_presets'])if(stableValue105(before.cfg[k]??null)!==stableValue105(after.cfg[k]??null))throw Error('MIGRATION_CONFIG_CHANGED: '+k);
 for(const p of before.products){const q=newProducts.get(p.id);for(const k of ['size_catalogs','size_catalog_candidates'])if(p[k]&&stableValue105(p[k])!==stableValue105(q[k]))throw Error('MIGRATION_EXISTING_SIZE_CATALOG_CHANGED: '+p.id);for(const e of p.classification_exceptions||[])if(!q.classification_exceptions?.some(x=>stableValue105(x)===stableValue105(e)))throw Error('MIGRATION_EXISTING_EXCEPTION_CHANGED: '+p.id);}
 return {LOST_CATEGORIES:0,LOST_SKU:0,LOST_VARIANTS:0,LOST_PHOTOS:0,LOST_PRICES:0,LOST_STOCK:0,IDS_UNCHANGED:true,MANUAL_LOCKS_UNCHANGED:true,PRICES_UNCHANGED:true,STOCK_UNCHANGED:true,PUBLICATION_UNCHANGED:true};
}
function productionCandidateRows(rows,data){
 const out=releaseStorage.clone(rows),config=out.find(x=>x.key==='meta/config');if(config)config.data=releaseStorage.clone(data.cfg);else out.push({key:'meta/config',data:releaseStorage.clone(data.cfg)});
 const byBucket=new Map();for(const p of data.products){const key='cat/'+bucketOf(p.id,NB);if(!byBucket.has(key))byBucket.set(key,{});byBucket.get(key)[p.id]=p;}
 for(const r of out.filter(x=>x.key.startsWith('cat/')))r.data={...r.data,products:releaseStorage.clone(byBucket.get(r.key)||{})};
 for(const [key,products] of byBucket)if(!out.some(x=>x.key===key))out.push({key,data:{products:releaseStorage.clone(products)}});
 return out;
}
async function productionPlan(rows){
 const source=productionRowsData(rows);if(!source.products.length)throw Error('EXISTING_DATABASE_EMPTY: відновіть існуючу базу, порожня migration заборонена');
 const saved={...S};let candidate,pricesBefore,pricesAfter,report;
 try{
  productionHydrate(source);pricesBefore=productionPrices();classificationEnable();releaseStorage.gates(S.cfg);S.cfg.storageBucketVersion=2;
  const tactical=S.cfg.suppliers.find(s=>s.id==='s4p9slmnn0ki');if(tactical?.inventory_policy?.confirmed&&tactical.inventory_policy.mode==='QUANTITY')throw Error('TACTICAL_QUANTITY_CONFIRMATION_REQUIRED: policy не може бути активована без підтвердження');
  let n=0;for(const p of S.products.values()){
   if(p.archived&&p.variants.length===0)continue; // Historical merged-model aliases are not active classification records.
   // Existing normalized RC records are carried over verbatim. Old records use exactly the accepted RC pipeline.
   if(!p.category_confidence_tier||p.variants.some(v=>!v.size_status||!v.size_confidence_tier||!v.source_binding_status)){const publicationKeys=['pub','ads','archived','archiveReason','archivePrevPub','syncStatus','simple_excluded_reason'],original=releaseStorage.clone(p);classificationApplyProduct(p);for(const k of publicationKeys)if(Object.hasOwn(original,k))p[k]=original[k];else delete p[k];}
   for(const v of p.variants)for(const [sid,o] of Object.entries(v.offers||{}))if(!o.last_valid_inventory_observation){const inv=classificationInventory({sid,...o},v);if(inv.availability_confirmation==='CONFIRMED')o.last_valid_inventory_observation={...inv,supplier_sku:o.s};}
   if(++n%100===0)await workflowYield();
  }
  candidate={cfg:releaseStorage.clone(S.cfg),products:releaseStorage.clone([...S.products.values()]),queue:releaseStorage.clone(source.queue),content:releaseStorage.clone(source.content),logs:releaseStorage.clone(source.logs),docs:releaseStorage.clone(source.docs)};pricesAfter=productionPrices();
  const preservation=productionAssertPreserved(source,candidate,pricesBefore,pricesAfter),counts={products:source.products.length,variants:source.products.reduce((n,p)=>n+p.variants.length,0),bindings:source.products.reduce((n,p)=>n+p.variants.reduce((m,v)=>m+Object.keys(v.offers||{}).length,0),0)};
  const category={SAFE_AUTO:0,LIKELY:0,AMBIGUOUS:0,UNTOUCHED:0},size={SAFE_AUTO:0,LIKELY:0,AMBIGUOUS:0},availability={IN_STOCK:0,OUT_OF_STOCK:0,PREORDER:0,UNKNOWN:0,ORDER_ON_REQUEST:0};let payment=0;
  for(const p of S.products.values()){category[p.category_confidence_tier||'UNTOUCHED']++;for(const v of p.variants){size[v.size_confidence_tier]++;if(classificationAvailability(p,v).payment_allowed)payment++;for(const [sid,o] of Object.entries(v.offers||{}))availability[classificationInventory({sid,...o},v).availability_status]++;}}
  report={version:PRODUCTION_RELEASE_VERSION,rc_commit:PRODUCTION_RC_COMMIT,source_sha256:await releaseStorage.rowsDigest(rows),...counts,categories_before:(source.cfg.canonical_categories||[]).length,categories_after:candidate.cfg.canonical_categories.length,builtin_categories:RubizhCategories.catalogue().length,category,size,runtime:classificationSummary(),supplier_availability:availability,PAYMENT_READY:payment,manual_lock_products:source.products.filter(p=>p.category_locked||Object.values(p.manual_locks||{}).some(Boolean)||Object.values(p.fieldMeta||{}).some(m=>m.source==='manual')).length,...preservation,SYNC_ENABLED:false,AUTOPRICES_ENABLED:false,PRODUCTION_WRITES:0};
 }finally{for(const k of Object.keys(S))if(!Object.hasOwn(saved,k))delete S[k];Object.assign(S,saved);rebuildIndex();bumpData();}
 return {source,candidate,rows:productionCandidateRows(rows,candidate),sourceRows:rows,report};
}
async function productionCapture(){if(!Store.db||Store.mode!=='indexeddb')throw Error('ATOMIC_STORAGE_REQUIRED: використайте браузер з IndexedDB; старі дані не змінені');return releaseStorage.capture(Store.db);}
function productionLocalSnapshot(){return Object.fromEntries(Array.from({length:localStorage.length},(_,i)=>localStorage.key(i)).filter(Boolean).map(k=>[k,localStorage.getItem(k)]));}
async function productionEnsureDocuments(){for(const d of S.docs?.values()||[]){const row=await Store._get0('docfile/'+d.id);if(!row?.blob&&!await sbDocBlob(d.id))throw Error('FULL_DOCUMENT_BACKUP_REQUIRED: '+d.id);}}
async function productionPreview(){await productionEnsureDocuments();const rows=await productionCapture();const plan=await productionPlan(rows);PRODUCTION_MIGRATION.plan=plan;PRODUCTION_MIGRATION.lastReport=plan.report;PRODUCTION_MIGRATION.state='preview';return plan.report;}
async function productionBackup(rows,label){
 const id='10.9.3-'+Date.now()+'-'+uid('backup'),source_sha256=await releaseStorage.rowsDigest(rows);
 const {blob,gz}=await releaseStorage.encodeBlob(rows,productionLocalSnapshot(),{release:PRODUCTION_RELEASE_VERSION,rc_commit:PRODUCTION_RC_COMMIT,label,source_sha256},(phase,done,total)=>{if(done===total||done%8===0){PRODUCTION_MIGRATION.progress=phase==='rows'?'Резервна копія: записи '+done+' / '+total:'Резервна копія: файли '+done+' / '+total;if(typeof document!=='undefined'&&typeof requestAnimationFrame==='function')render();}}),backup={id,blob,gz,sha256:await releaseStorage.blobDigest(blob),source_sha256,at:Date.now(),filename:'rubizh-pim-'+id+'.json'+(gz?'.gz':'')};
 PRODUCTION_MIGRATION.progress='Перевіряємо збережену повну копію…';render();await workflowYield();await releaseStorage.saveBackup(backup);const checked=await releaseStorage.readBackup(backup);if(await releaseStorage.rowsDigest(checked.rows)!==source_sha256)throw Error('BACKUP_VALUES_READBACK_FAILED');return backup;
}
async function productionSaveExternal(backup){if(!await offerDownload(backup.filename,backup.blob))return false;return confirm('Переконайтеся, що повний backup '+backup.filename+' збережено на диск. SHA256: '+backup.sha256+'. Продовжити?');}
async function productionApply(){
 const plan=PRODUCTION_MIGRATION.plan;if(!plan)throw Error('MIGRATION_PREVIEW_REQUIRED');
 PRODUCTION_MIGRATION.progress='Перевіряємо, що дані не змінилися…';render();await workflowYield();const current=await productionCapture();if(current.some(r=>r.key==='meta/production_release_10_9_3'&&r.data.version===PRODUCTION_RELEASE_VERSION)){await productionLoad();PRODUCTION_MIGRATION.plan=null;return {...plan.report,ALREADY_MIGRATED:true};}if(await releaseStorage.rowsDigest(current)!==plan.report.source_sha256)throw Error('STALE_MIGRATION: повторіть dry-run');
 PRODUCTION_MIGRATION.state='backing-up';const backup=await productionBackup(current,'Перед production migration 10.9.3');PRODUCTION_MIGRATION.backupId=backup.id;
 if(!await productionSaveExternal(backup)){PRODUCTION_MIGRATION.state='preview';throw Error('EXTERNAL_BACKUP_REQUIRED: migration не застосована');}
 const revision=current.find(x=>x.key==='sync/local_revision')?.data||0,rows=releaseStorage.clone(plan.rows),put=(key,data)=>{const row=rows.find(x=>x.key===key);if(row)row.data=data;else rows.push({key,data});};
 put('sync/local_revision',revision+1);put('meta/production_release_10_9_3',{version:PRODUCTION_RELEASE_VERSION,rc_commit:PRODUCTION_RC_COMMIT,backup_id:backup.id,backup_sha256:backup.sha256,source_sha256:plan.report.source_sha256,at:Date.now(),sync_enabled:false,autoprices_enabled:false});
 PRODUCTION_MIGRATION.state='applying';await releaseStorage.write(Store.db,current,rows);
 try{
  const stored=await productionCapture(),got=productionRowsData(stored);productionHydrate(got);S.storageRevision=revision+1;
  const prices=productionPrices();productionAssertPreserved(plan.source,got,productionPriceFrom(plan.source),prices);
  const expected=new Map(plan.candidate.products.map(p=>[p.id,p]));if(got.products.length!==expected.size||got.products.some(p=>!expected.has(p.id)||stableValue105(p)!==stableValue105(expected.get(p.id)))||stableValue105(got.cfg)!==stableValue105(plan.candidate.cfg))throw Error('MIGRATION_READBACK_FAILED');
  await productionWarmView();
 }catch(error){await releaseStorage.rollback(Store.db,await releaseStorage.readBackup(backup),{operationalGates:false,bumpRevision:false});await productionLoad();PRODUCTION_MIGRATION.state='blocked';throw error;}
 PRODUCTION_MIGRATION.state='ready';PRODUCTION_MIGRATION.lastReport={...plan.report,BACKUP_PATH:releaseStorage.BACKUP_DATABASE+'/backups/'+backup.id,BACKUP_FORMAT:releaseStorage.FORMAT,BACKUP_SHA256:backup.sha256,PERSISTED_VERIFIED:true,EXTERNAL_BACKUP_USER_CONFIRMED:true,LOCAL_MIGRATION_TRANSACTIONS:1,SHOP_WRITES:0};delete PRODUCTION_MIGRATION.lastReport.PRODUCTION_WRITES;PRODUCTION_MIGRATION.plan=null;
 for(const r of rows)if(!/^(autobak\/|autobak_meta\/|safety\/|docfile\/|sync\/|auth\/)/.test(r.key))sbMark(r.key);
 return PRODUCTION_MIGRATION.lastReport;
}
// Warm the existing read-only per-product view cache in short batches. The
// assessment and its existing data-version/minute invalidation are unchanged.
async function productionWarmView(){
 if(S.view!=='simplePublication'||typeof requestAnimationFrame!=='function')return;
 const state=PRODUCTION_MIGRATION.state;PRODUCTION_MIGRATION.state='warming-view';
 try{for(let pass=0;pass<2;pass++){const minute=Math.floor(Date.now()/60000);let n=0,at=performance.now();for(const p of S.products.values()){if(!p.archived)simpleAssess(p);n++;if(performance.now()-at>=16){PRODUCTION_MIGRATION.progress='Готуємо інтерфейс: '+n+' / '+S.products.size;render();await workflowYield();at=performance.now();}}if(minute===Math.floor(Date.now()/60000))break;}}
 finally{PRODUCTION_MIGRATION.state=state;PRODUCTION_MIGRATION.progress='';}
}
function productionPriceFrom(data){const saved={...S};try{productionHydrate(data);return productionPrices();}finally{Object.assign(S,saved);rebuildIndex();bumpData();}}
async function productionLoad(){
 await Store.init();if(!Store.db){const rows=[];for(const k of await Store.keys())rows.push({key:k,data:await Store._get0(k)});productionHydrate(productionRowsData(rows));PRODUCTION_MIGRATION.state='blocked';throw Error('ATOMIC_STORAGE_REQUIRED');}
 let rows=await productionCapture();if(!rows.some(r=>r.key==='meta/config')){const legacy=[];for(const k of Object.keys(localStorage).filter(k=>k.startsWith(Store.fallbackPrefix))){try{legacy.push({key:k.slice(Store.fallbackPrefix.length),data:JSON.parse(localStorage.getItem(k))});}catch{}}if(legacy.length){productionHydrate(productionRowsData(legacy));PRODUCTION_MIGRATION.state='blocked';throw Error('LEGACY_FALLBACK_RECOVERY_REQUIRED: локальні дані знайдено; спочатку відновіть їх з повної копії, порожня migration заборонена');}}
 productionHydrate(productionRowsData(rows));S.storageRevision=rows.find(x=>x.key==='sync/local_revision')?.data||0;
 const marker=rows.find(x=>x.key==='meta/production_release_10_9_3')?.data;
 PRODUCTION_MIGRATION.state=marker?.version===PRODUCTION_RELEASE_VERSION?'ready':'pending';PRODUCTION_MIGRATION.backupId=marker?.backup_id||null;
 if(PRODUCTION_MIGRATION.state==='ready'&&(!classificationEnabled()||S.cfg.inventory_policy_version!==1||!RubizhCategories.catalogue().every(c=>S.cfg.canonical_categories?.some(x=>x.id===c.id)))){PRODUCTION_MIGRATION.state='blocked';throw Error('MIGRATION_MARKER_INVALID');}
 if(PRODUCTION_MIGRATION.state==='ready')await productionWarmView();
}
async function productionRollback(id=PRODUCTION_MIGRATION.backupId){
 const backup=await releaseStorage.getBackup(id),snapshot=await releaseStorage.readBackup(backup);PRODUCTION_MIGRATION.state='rolling-back';const rescue=await productionBackup(await productionCapture(),'Перед rollback 10.9.3');if(!await productionSaveExternal(rescue))throw Error('ROLLBACK_RESCUE_BACKUP_REQUIRED');
 const result=await releaseStorage.rollback(Store.db,snapshot,{localStorage});await productionLoad();PRODUCTION_MIGRATION.state='rolled-back';PRODUCTION_MIGRATION.lastReport={...result,ROLLBACK_BACKUP:id,RESCUE_BACKUP:rescue.id};return result;
}
const productionBeforeLoad=sbBeforeLoad;sbBeforeLoad=async function(){if(!productionMode())return productionBeforeLoad(...arguments);if(!sbCfg()){SB.status='off';return true;}await Store.init();for(;;){if(!sbSession())await sbLoginDialog('Увійдіть для доступу до існуючої бази. Migration ще не застосована.');try{await sbToken();SB.status='ok';return true;}catch(e){if(!e.auth&&sbSession()?.expires_at>Date.now()){SB.status='offline';return true;}lsSet(SB_LS.session,null);await sbLoginDialog('Потрібне підтвердження входу.');}}};
const productionPull=sbPull;sbPull=async function(){if(productionMode()&&PRODUCTION_MIGRATION.state!=='ready')return {changed:0,migration_pending:true};return productionPull(...arguments);};
const productionPersist=persist;persist=async function(){if(productionMode()&&PRODUCTION_MIGRATION.state!=='ready')throw Error('MIGRATION_PENDING: запис призупинено до перевіреної migration');return productionPersist(...arguments);};
const productionLegacyLoad=load;load=async function(){return productionMode()?productionLoad():productionLegacyLoad(...arguments);};
const productionLegacyStartup=startupIntegrityCheck;startupIntegrityCheck=async function(){if(!productionMode())return productionLegacyStartup(...arguments);return {stats:catalogStats(),automatic_repair:false,migration_state:PRODUCTION_MIGRATION.state};};
const productionLegacyPricing=ensurePricingPolicy;ensurePricingPolicy=async function(){return productionMode()?false:productionLegacyPricing(...arguments);};
const productionLegacyV10=v10Startup;v10Startup=async function(){if(!productionMode())return productionLegacyV10(...arguments);S.ui.autoIdx=await autoBackupIndex();S.ui.massIdx=await massLogIndex();if(PRODUCTION_MIGRATION.state==='ready'){await dailyBackupTick();setInterval(dailyBackupTick,60*60e3);}return {sync_enabled:false,autoprices_enabled:false};};
async function productionRestoreServer(){if(S.products.size)throw Error('EXISTING_LOCAL_DATA: синхронізуйте існуючу базу в попередній PIM перед migration');if(!sbCfg())throw Error('EXISTING_SERVER_CONNECTION_REQUIRED');if(sbPending().size)throw Error('PENDING_LOCAL_CHANGES');await productionPull(true);await productionLoad();return {restored:true,products:S.products.size,REMOTE_WRITES:0};}
const productionSchedulePush=sbSchedulePush;sbSchedulePush=function(){if(productionMode()&&PRODUCTION_MIGRATION.state!=='ready')return;return productionSchedulePush(...arguments);};
const productionPush=sbPush;sbPush=async function(){if(productionMode()&&PRODUCTION_MIGRATION.state!=='ready')return {migration_pending:true};return productionPush(...arguments);};
const productionSiteTick=siteAutoTick;siteAutoTick=function(){return productionMode()?false:productionSiteTick(...arguments);};
const productionScheduler=workflowSchedulerStart;workflowSchedulerStart=function(){return productionMode()?false:productionScheduler(...arguments);};
for(const name of ['workflowDownloadSource','workflowFetchSource','workflowRefreshSources']){const old=window[name];window[name]=async function(){if(productionMode())throw Error('AUTOPRICES_DISABLED: потрібен REAL_SOURCE_COMPATIBILITY на справжніх файлах');return old(...arguments);};}
const productionWorkflowAction=workflowAction;workflowAction=async function(action,t){if(productionMode()&&action==='wfSaveSource'){const panel=$(`[data-source-panel="${CSS.escape(t.dataset.sid)}"]`);if(panel?.querySelector('[data-source-enabled]')?.checked||panel?.querySelector('[data-source-apply]')?.checked)throw Error('AUTOPRICES_DISABLED');}return productionWorkflowAction(...arguments);};
const productionSourcePanel=workflowSourcePanel;workflowSourcePanel=function(s){const html=productionSourcePanel(s);return productionMode()?'<p class="small">Автопрайси вимкнено до REAL_SOURCE_COMPATIBILITY. Локальні файли можна імпортувати через preview.</p>'+html.replace(/(<input[^>]*data-source-(?:enabled|apply)[^>]*)(>)/g,'$1 disabled$2').replace(/(<button[^>]*data-act="wfFetchSource"[^>]*)(>)/g,'$1 disabled$2'):html;};
// Preserve #main, #topbar and #view across every migration redraw.
const productionRender=render;render=function(){if(!productionMode())return productionRender(...arguments);if(PRODUCTION_MIGRATION.state==='ready')productionRender(...arguments);else renderNav();const view=$('#view');if(PRODUCTION_MIGRATION.state!=='ready'&&view){const r=PRODUCTION_MIGRATION.lastReport;view.innerHTML='<h1>PIM 10.9.3 — '+(PRODUCTION_MIGRATION.state==='warming-view'?'підготовка інтерфейсу':'міграція існуючої бази')+'</h1><p>Товари: '+S.products.size+'. Доки міграцію не перевірено, запис і cloud push призупинені. Sync магазину й автопрайси вимкнено.</p>'+(!S.products.size?'<p role="alert">У цьому профілі браузера локальний каталог порожній. Відкрийте PIM у тому самому профілі, де збережено ваші товари. Інкогніто й інші профілі мають окрему базу. Не застосовуйте migration до порожньої бази.</p>':'')+(PRODUCTION_MIGRATION.progress?'<p role="status" aria-live="polite">'+esc(PRODUCTION_MIGRATION.progress)+'</p>':'')+(PRODUCTION_MIGRATION.error?'<p>'+esc(PRODUCTION_MIGRATION.error)+'</p>':'')+(!S.products.size&&sbCfg()?'<button class="btn" data-release-action="server-load">Отримати існуючу базу з сервера</button>':'')+'<button class="btn" data-release-action="preview"'+(!S.products.size||PRODUCTION_MIGRATION.busy?' disabled':'')+'>Показати migration dry-run</button>'+(PRODUCTION_MIGRATION.state==='preview'?'<p>Категорії: '+r.categories_before+' → '+r.categories_after+'. SKU: '+r.variants+'. LOST_* = 0. Ціни, фото, stock і manual locks збережено.</p><button class="btn primary" data-release-action="apply">Повна копія файлом + застосувати</button>':'')+'<p><a href="release-recovery.html">Відновлення повної копії / rollback</a>. Порожня нова база не створюється. Фактичні поточні дані перевіряються перед застосуванням. На час міграції закрийте інші вкладки PIM.</p>';}
 if(S.view==='backup'&&view&&PRODUCTION_MIGRATION.backupId)view.insertAdjacentHTML('afterbegin','<section class="panel"><h2>Migration 10.9.3</h2><p>SYNC_ENABLED=false · AUTOPRICES_ENABLED=false</p><button class="btn" data-release-action="report">Звіт</button><button class="btn" data-release-action="download">Повна копія до міграції</button><button class="btn danger" data-release-action="rollback">Rollback даних до міграції</button></section>');};
document.addEventListener('click',async e=>{if(!productionMode())return;const b=e.target.closest('[data-release-action]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();if(PRODUCTION_MIGRATION.busy)return;PRODUCTION_MIGRATION.busy=true;try{PRODUCTION_MIGRATION.error='';const a=b.dataset.releaseAction;if(a==='server-load')await productionRestoreServer();else if(a==='preview')await productionPreview();else if(a==='apply')await productionApply();else if(a==='rollback'){if(!confirm('Відновити всю базу до migration? Пізніші правки також відкотяться; перед цим буде збережено повну rescue-копію.'))return;await productionRollback();}else if(a==='download'){const row=await releaseStorage.getBackup(PRODUCTION_MIGRATION.backupId);await offerDownload(row.filename,row.blob);}else if(a==='report')await offerDownload('rubizh-pim-10.9.3-migration-report.json',new Blob([JSON.stringify(PRODUCTION_MIGRATION.lastReport,null,2)],{type:'application/json'}));}catch(error){PRODUCTION_MIGRATION.error=error.message||String(error);if(PRODUCTION_MIGRATION.state==='applying'||PRODUCTION_MIGRATION.state==='backing-up')PRODUCTION_MIGRATION.state='preview';}finally{PRODUCTION_MIGRATION.busy=false;PRODUCTION_MIGRATION.progress='';render();}},true);
