const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),{createHarness}=require('./isolated-harness.cjs');
function harness(){const h=createHarness();for(const file of ['size-evidence.js','queue-dry-run.inc.js'])new vm.Script(fs.readFileSync(path.join(__dirname,'../lib',file),'utf8')).runInContext(h.ctx);return h;}
test('production cannot invoke safe mutations',()=>{const h=harness();assert.throws(()=>h.run('drApplySafe({})'),/never production/);});
for(const stock of [0,null,-1])test('stock '+stock+' does not create preorder',()=>{const h=harness();h.ctx.offer={stock,availability:'out'};assert.equal(h.run('drAvailability(offer).preorder'),false);});
test('source preorder permits unknown lead time, invents no term',()=>{const h=harness();h.ctx.offer={stock:0,availability:'order',preorder:true};assert.equal(h.run('drAvailability(offer).status'),'PREORDER');assert.equal(h.run('drAvailability(offer).lead_time_days'),null);});
test('owner default or explicit denial does not masquerade as supplier preorder',()=>{const h=harness();h.ctx.offer={stock:0,availability:'out',preorder:true};assert.equal(h.run('drAvailability(offer).preorder'),false);h.ctx.offer={stock:0,availability:'order',preorder:true,preorderManual:true};assert.equal(h.run('drAvailability(offer).preorder'),false);});
test('size does not change stock or availability',()=>{const h=harness(),p=h.product({canonical_category_id:'clothing_pants',primary_product_type:'pants'});h.add(p);h.ctx.p=p;const before=JSON.stringify(p.variants[0].offers);h.run('drSize(p,p.variants[0])');assert.equal(JSON.stringify(p.variants[0].offers),before);});
test('description can be restored from supplier facts without autoarchive',()=>{const h=harness(),p=h.product({desc:'',source_description:'',fieldMeta:{attrs:{source:'supplier',supplierValue:{Матеріал:'Нейлон',Вага:'500 г'}}}});h.ctx.p=p;const d=h.run('drContent(p)');assert.equal(d.archive,false);assert.equal(d.source,'supplier_attributes');assert.ok(d.description.includes('500 г'));assert.ok(!d.description.includes('Cordura'));});
test('description absence alone is exception, never archive',()=>{const h=harness();h.ctx.p=h.product({desc:'',attrs:{},fieldMeta:{}});assert.equal(h.run('drContent(p).archive'),false);assert.equal(h.run('drContent(p).source'),'CONTENT_CONFIRMATION_REQUIRED');});
test('manual description and category are protected',()=>{const h=harness();h.ctx.p=h.product({desc:'',category_locked:true,fieldMeta:{desc:{source:'manual'},attrs:{source:'supplier',supplierValue:{Матеріал:'Нейлон'}}}});assert.equal(h.run('drContent(p).description'),'');assert.equal(h.run('drCategory(p).tier'),'AMBIGUOUS');});
test('known broken and placeholder photos are unusable',()=>{const h=harness();h.ctx.p=h.product({photos:['https://x.test/broken.jpg','https://x.test/placeholder.jpg'],photoMeta:{'https://x.test/broken.jpg':{status:'failed'}},variants:[]});assert.equal(h.run('drPhotos(p).zero'),true);});
test('unknown network photo status is disclosed',()=>{const h=harness();h.ctx.p=h.product();assert.ok(h.run('drPhotos(p).unverified')>0);});
test('similar name alone never sufficient to group',()=>{const h=harness(),a=h.product({id:'a',desc:'<p>Добрий товар.</p>',catSource:'auto'}),b=h.product({id:'b',desc:'<p>Добрий товар.</p>',catSource:'auto'});b.variants[0].sku='RUB-B';b.variants[0].color='Чорний';b.variants[0].offers['supplier-a'].s='feed-b';h.ctx.ps=[a,b];assert.equal(h.run('drModel(ps).tier'),'AMBIGUOUS');});
test('historical stock override is possible only in explicitly isolated audit',()=>{const h=harness();h.ctx.offer={availability:'in',stock:3,stock_stale:true};assert.equal(h.run('drAvailability(offer).status'),'STOCK_CONFIRMATION_REQUIRED');h.run('const _DR_USE_HISTORICAL_STOCK=true;');assert.equal(h.run('drAvailability(offer).status'),'STOCK_CONFIRMATION_REQUIRED');h.run('const _DR_ISOLATED_AUDIT=true;');assert.equal(h.run('drAvailability(offer).status'),'IN_STOCK');});
test('manual normalized primary type prevents automatic category changes',()=>{const h=harness();h.ctx.p=h.product({manual_locks:{primary_product_type:true}});assert.equal(h.run('drCategory(p).tier'),'AMBIGUOUS');});
