'use strict';
// Real Chromium, full HTML/bootstrap, isolated loopback origin. No runtime stubs.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PIM_PLAYWRIGHT_MODULE||'/workspace/scratch/pim-audit-tools/node_modules/playwright-core');
const app=path.resolve(__dirname,'../../app'),html=process.env.PIM_HTML||path.join(app,'rubizh_pim.html'),source=process.env.PIM_SOURCE;
const out=process.env.PIM_BROWSER_REPORT||'/tmp/pim-browser-smoke.json',repro=process.env.PIM_REPRO==='1';
(async()=>{
 const server=http.createServer((req,res)=>{const p=new URL(req.url,'http://localhost').pathname;let f=p==='/source.json'?source:p==='/rubizh_pim.html'?html:path.join(app,p);if(p==='/__seed'){res.end('<!doctype html><title>Private test seed</title><script src="/lib/release-storage.js"></script>');return;}if(!f||!fs.existsSync(f)||!fs.statSync(f).isFile()){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.json')?'application/json':p.endsWith('.css')?'text/css':'text/html');fs.createReadStream(f).pipe(res);});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
 let browser;const result={full_bootstrap:true,runtime_stubs:false,external_network_calls:0,errors:[],console_errors:[],network_errors:[],intercepted_external_requests:0,checks:[]};
 try{
  browser=await chromium.launch({executablePath:process.env.PIM_CHROMIUM||'/usr/bin/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
  const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
  await context.route('**/*',route=>{if(route.request().url().startsWith(base+'/'))return route.continue();result.intercepted_external_requests++;const type=route.request().resourceType();if(!['image','stylesheet','font'].includes(type)){result.network_errors.push('Unexpected external '+type+' request');return route.abort();}return route.fulfill({status:200,contentType:type==='stylesheet'?'text/css':'image/svg+xml',body:type==='stylesheet'?'':'<svg xmlns="http://www.w3.org/2000/svg" width="1" height="1"/>'});});
  const page=await context.newPage();page.on('pageerror',e=>result.errors.push(e.message));page.on('dialog',d=>d.accept());page.on('console',m=>{if(m.type()==='error')result.console_errors.push(m.text());});page.on('response',r=>{if(r.url().startsWith(base+'/')&&r.status()>=400)result.network_errors.push(r.status()+' '+new URL(r.url()).pathname);});
  if(source&&!repro){await page.goto(base+'/__seed');await page.evaluate(async()=>{const data=await (await fetch('/source.json')).json(),rows=RubizhReleaseStorage.portableRows(data),db=await RubizhReleaseStorage.openDatabase();await RubizhReleaseStorage.write(db,[],rows);db.close();});result.checks.push('original full backup seeded into isolated IndexedDB');}
  await page.goto(base+'/rubizh_pim.html',{waitUntil:'load'});await page.waitForFunction(()=>typeof PRODUCTION_MIGRATION!=='undefined'&&PRODUCTION_MIGRATION.state==='pending');await page.waitForTimeout(600);
  if(repro){assert(result.errors.some(e=>e.includes('innerHTML')),'Frozen release must reproduce startup failure');assert.equal(await page.locator('#view').count(),0);result.expected_failure_reproduced=true;return;}
  assert.deepEqual(result.errors,[]);assert.equal(await page.locator('#view').count(),1);assert.equal(await page.locator('#gs').count(),1);assert(!(await page.title()).includes('RC'));result.checks.push('full startup and repeated render preserve shell and search');
  const n=await page.evaluate(()=>S.products.size);result.products=n;
  if(!source){assert.equal(n,0);assert(await page.locator('[data-release-action="preview"]').isDisabled());assert((await page.locator('#view').textContent()).includes('профіл'));result.checks.push('empty profile explicitly identified; empty migration blocked');return;}
  assert.equal(n,3113);await page.locator('[data-release-action="preview"]').click();await page.waitForFunction(()=>PRODUCTION_MIGRATION.state==='preview'||PRODUCTION_MIGRATION.error,{timeout:180000});
  result.preview=await page.evaluate(()=>PRODUCTION_MIGRATION.lastReport);assert(result.preview);assert.equal(result.preview.variants,8734);assert.equal(result.preview.categories_after,143);
  for(const k of Object.keys(result.preview).filter(k=>k.startsWith('LOST_')))assert.equal(result.preview[k],0,k);
  const downloadPromise=page.waitForEvent('download',{timeout:180000});await page.locator('[data-release-action="apply"]').click();const download=await downloadPromise;await download.path();await page.waitForFunction(()=>PRODUCTION_MIGRATION.state==='ready'||PRODUCTION_MIGRATION.error,{timeout:180000});assert.equal(await page.evaluate(()=>PRODUCTION_MIGRATION.error),'');
  result.applied=await page.evaluate(()=>PRODUCTION_MIGRATION.lastReport);assert(result.applied.PERSISTED_VERIFIED);result.checks.push('native preview → actual backup download → confirmation → atomic apply');
  for(const width of [1440,390]){await page.setViewportSize({width,height:1000});for(const view of ['products','cats','suppliers','backup','settings','import']){await page.evaluate(v=>go(v),view);assert.equal(await page.locator('#view').count(),1);assert.equal(await page.locator('#gs').count(),1);assert((await page.locator('#view').textContent()).trim().length);}}
  await page.setViewportSize({width:1440,height:1000});await page.locator('#gs').fill('RUB-');await page.waitForTimeout(400);assert(await page.locator('#gsres').isVisible());result.checks.push('search and 6 main pages at desktop/mobile widths');
  await page.reload({waitUntil:'load'});await page.waitForFunction(()=>PRODUCTION_MIGRATION.state==='ready');const counts=await page.evaluate(()=>({products:S.products.size,variants:[...S.products.values()].reduce((n,p)=>n+p.variants.length,0),categories:S.cfg.canonical_categories.length}));assert.deepEqual(counts,{products:3113,variants:8734,categories:143});
  // Public migration API remains available for retry, with full actual DOM intact.
  result.second=await page.evaluate(async()=>{await productionPreview();return productionApply();});assert(result.second.ALREADY_MIGRATED);await page.evaluate(()=>render());result.checks.push('restart and identical second migration is a no-op');
  await page.evaluate(()=>go('backup'));const rescuePromise=page.waitForEvent('download',{timeout:180000});await page.locator('[data-release-action="rollback"]').click();await (await rescuePromise).path();await page.waitForFunction(()=>PRODUCTION_MIGRATION.state==='rolled-back'||PRODUCTION_MIGRATION.error,{timeout:180000});assert.equal(await page.evaluate(()=>PRODUCTION_MIGRATION.error),'');assert.equal(await page.evaluate(()=>S.products.size),3113);const restoredHash=await page.evaluate(async()=>releaseStorage.digest(stableValue105(productionProtected(productionRowsData(await productionCapture())))));assert.equal(restoredHash,'eb1fdbb9b6792e7eb6c0df610e9c78007175472783ad3eb4708d9ba441551a61');result.rollback_protected_sha256=restoredHash;result.checks.push('native rollback and rescue backup preserve protected catalog hash');assert.deepEqual(result.errors,[]);assert.deepEqual(result.console_errors,[]);assert.deepEqual(result.network_errors,[]);result.status='PASS';
 }finally{fs.writeFileSync(out,JSON.stringify(result,null,2)+'\n');if(browser)await browser.close();await new Promise(r=>server.close(r));console.log(JSON.stringify({report:out,checks:result.checks,errors:result.errors,expected_failure_reproduced:result.expected_failure_reproduced,status:result.status}));}
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
