const VERSION=1;
const negativeRules=[
 {id:'accessory_is_not_target',description:'Підсумок, сумка, кавер або чохол не є предметом, для якого призначені.'},
 {id:'weapon_magazine_requires_context',description:'Слово «магазин» без збройового контексту не визначає категорію.'},
 {id:'plate_requires_armor_context',description:'Слово «плита» без бронезахисту не визначає бронеплиту.'},
 {id:'material_is_not_product_type',description:'Фліс, soft shell і камуфляж самі по собі не визначають тип виробу.'},
 {id:'ifak_empty_bag',description:'Підсумок або порожня сумка для аптечки не є укомплектованою аптечкою.'},
 {id:'training_is_not_medical_use',description:'Навчальний турнікет належить до навчальних медичних засобів.'},
 {id:'specific_before_generic',description:'Спеціальні призначення мають перевагу над загальним типом того самого виробу.'}
];
const equivalents={балистический:'баллистический',балистичний:'балістичний',берцы:'берці',берци:'берці',куртки:'куртка',брюки:'штани',подсумок:'підсумок',подсумки:'підсумок',підсумки:'підсумок',підсум:'підсумок',рации:'рація',рация:'рація',рацій:'рація',шлем:'шолом',шлема:'шолом',шолома:'шолом',шоломи:'шолом',наушники:'навушники',плитоноски:'плитоноска',бронеплиты:'бронеплита',бронеплити:'бронеплита',флис:'фліс',зимняя:'зимова',зимние:'зимові',мужская:'чоловіча',мужские:'чоловічі',женская:'жіноча',тактические:'тактичні',тактическая:'тактична',сумки:'сумка',маскировочная:'маскувальна',сетка:'сітка',курткаа:'куртка',убакc:'убакс',ubaks:'убакс',kurtka:'куртка',podsumok:'підсумок',plitonoska:'плитоноска',broneplita:'бронеплита',multikam:'multicam',мультикам:'multicam'};
const escape=s=>String(s).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
function normalize(value){let s=String(value??'').normalize('NFKC').toLowerCase().trim().replace(/[’‘`ʼ]/g,"'").replace(/[–—−]/g,'-').replace(/[>→\\]+/g,' / ').replace(/<[^>]*>/g,' ').replace(/&nbsp;|&#160;/g,' ').replace(/soft[ -]?shell/g,'soft_shell').replace(/\s+/g,' ');s=s.replace(/[\p{L}\p{N}_']+/gu,w=>equivalents[w]||w);return s.replace(/\s*\/\s*/g,' / ').trim();}
const catalogueCache=new WeakMap(),preparedCache=new WeakMap(),pathCache=new WeakMap();
function catalogue(custom){if(!custom?.length)return defaults;if(catalogueCache.has(custom))return catalogueCache.get(custom);const replacements=new Map((custom||[]).map(c=>[c.id,c]));const result=defaults.map(c=>({...c,...(replacements.get(c.id)||{}),id:c.id,parent_id:c.parent_id,aliases:[...new Set([...c.aliases,...(replacements.get(c.id)?.aliases||[])])]}));catalogueCache.set(custom,result);return result;}
function path(id,custom){const cats=catalogue(custom);let cache=pathCache.get(cats);if(!cache){const map=new Map(cats.map(c=>[c.id,c]));cache=new Map(cats.map(c=>[c.id,c.parent_id?map.get(c.parent_id).name+' / '+c.name:c.name]));pathCache.set(cats,cache);}return cache.get(id)||'';}
function leaf(id){return !!defaults.find(c=>c.id===id&&c.parent_id);}
const patterns=new Map();
function aliasPattern(alias){const n=normalize(alias);let re=patterns.get(n);if(!re){const words=n.split(' '),last=words.pop();let stem=last;if(last.length>5&&/^[\p{L}]+$/u.test(last)){stem=last.replace(/(?:ками|ники|ники|ник|ами|ові|ова|ими|их|ки|ка|ки|и|і|а|я|у|ю)$/u,'');if(stem.length<4)stem=last;}const ending=stem!==last||last.length>5&&/^[\p{L}]+$/u.test(last)?'[\\p{L}]*':'';re=new RegExp('(?<![\\p{L}\\p{N}])'+words.map(escape).concat(escape(stem)+ending).join('\\s+')+'(?![\\p{L}\\p{N}])','u');patterns.set(n,re);}return re;}
function preparedCategories(custom){const cats=catalogue(custom);if(preparedCache.has(cats))return preparedCache.get(cats);const result=cats.filter(c=>c.parent_id).map(c=>({...c,compiled:[...new Set([c.name,...c.aliases])].map(alias=>{const n=normalize(alias),first=n.match(/[\p{L}\p{N}]+/u)?.[0]||'';return {alias,re:aliasPattern(alias),weight:n.length,prefix:first.length>=3?first.slice(0,3):null};})}));preparedCache.set(cats,result);return result;}
function candidates(value,custom,category=false){const text=normalize(value);if(!text)return [];if(category&&text.includes(' / ')){const leafMatches=candidates(text.split(' / ').pop(),custom,false);if(leafMatches.length)return leafMatches;}let found=[];const prefixes=new Set((text.match(/[\p{L}\p{N}]+/gu)||[]).map(w=>w.slice(0,3)));for(const c of preparedCategories(custom))for(const a of c.compiled){if((!a.prefix||prefixes.has(a.prefix))&&a.re.test(text))found.push({id:c.id,alias:a.alias,weight:a.weight});}
 const primary=category?text:text.split(/\s+(?:для|з|із|зі|с|со|with|for|під|под)\s+/u)[0],pouch=/підсум|подсум|pouch/u.test(primary),bag=/сумк|рюкзак|bag|backpack/u.test(primary),cover=/кавер|чохол|чехол|cover|sheath/u.test(primary),mount=/кріплен|креплен|mount|рейк|rails|подушк|padding/u.test(primary);
 if(!category&&primary!==text&&!pouch&&!bag&&!cover&&!mount){const main=candidates(primary,custom);if(main.length)found=found.filter(x=>main.some(y=>y.id===x.id));}
 if(!pouch&&!bag&&!cover&&/магазин.*(?:\b(?:ak|ar|hk|glock)\b|ак(?:м|с)?(?:[ -]|$)|збро|оруж|5[.,]45|7[.,]62|5[.,]56)/u.test(text))found.push({id:'weapon_magazines',alias:'магазин + збройовий контекст',weight:40});
 if(mount&&/плитоноск|бронежилет/u.test(text))found.push({id:'armor_accessories',alias:'кріплення для бронезахисту',weight:40});
 if(pouch){found=found.filter(x=>x.id.startsWith('pouches_'));const targets=[['pouches_dump',/скид|сброс|dump/u],['pouches_medical',/аптеч|медич|медицин|ifak/u],['pouches_tourniquet',/турнікет|турникет|жгут|tourniquet/u],['pouches_radio',/раці|рація|раци|рация|radio/u],['pouches_grenade',/гранат|grenade/u],['pouches_magazine',/магазин|mag pouch|magazine/u],['pouches_phone',/телефон|phone/u],['pouches_other',/навушник|планшет/u]];for(const [id,pattern] of targets)if(pattern.test(text))found.push({id,alias:'підсумок + призначення',weight:30});} 
 else if(bag)found=found.filter(x=>x.id.startsWith('bags_')||x.id==='pouches_medical'||x.id==='pouches_dump'||x.id==='pouches_dangler'||x.id==='field_sleeping_bags');
 if(cover)found=found.filter(x=>['helmets_covers','weapon_cases','eye_accessories','tools_accessories','armor_accessories','pouches_other'].includes(x.id)||x.id.startsWith('pouches_'));
 if(mount&&!pouch&&!bag&&!cover)found=found.filter(x=>!['helmets_ballistic','communications_headsets','communications_radios','electronics_monoculars','armor_plate_carriers'].includes(x.id));
 if(text!=='фліс'&&text!=='fleece'&&(!/кофт|худі|худи|флісов\S*\s+куртк|флисов\S*\s+куртк|fleece jacket|флиск/u.test(text)||/підклад|подклад/u.test(text)))found=found.filter(x=>x.id!=='clothing_fleece');
 if(/штани|брюки|pants/u.test(text))found=found.filter(x=>!['clothing_jackets','clothing_fleece','clothing_thermal'].includes(x.id)||x.id==='clothing_thermal'&&/термо/u.test(text));
 if(cover||pouch||bag)found=found.filter(x=>!['armor_plates','armor_plate_carriers','medical_ifak','medical_tourniquets','communications_radios','helmets_ballistic','tools_knives','weapon_magazines'].includes(x.id));
 if(/карабін\S*\s+(?:ак|ar|мислив|зброй)|винтовка|рушниц/u.test(text))found=found.filter(x=>x.id!=='field_carabiners');
 if(/(?:ремінь|ремень|кумербанд|камербанд).*(?:плитоноск|бронежилет)/u.test(text))found=found.filter(x=>x.id==='armor_accessories');
 const specialized={clothing_suits:['camouflage_suits'],medical_tourniquets:['medical_training'],bags_backpacks:['bags_assault_backpacks','bags_hydration'],bags_tactical:['bags_duffels','bags_waist','bags_shoulder','bags_organizers','pouches_medical','pouches_dump','pouches_dangler'],lighting_handheld:['lighting_headlamps','lighting_tactical'],clothing_headwear:['clothing_balaclavas'],clothing_jackets:['clothing_fleece'],protection_knee:['protection_kits'],protection_elbow:['protection_kits'],medical_bandages:['medical_hemostatic'],pouches_utility:['pouches_panels'],pouches_magazine:['pouches_dump']};
 const present=new Set(found.map(x=>x.id));found=found.filter(x=>!(specialized[x.id]||[]).some(id=>present.has(id)));
 if(!category&&found.some(x=>x.id==='medical_ifak')&&/порожн|пуст|empty|без\s+(?:наповнен|содержим)|неукомплект/u.test(text)){found=found.filter(x=>x.id!=='medical_ifak');found.push({id:'pouches_medical',alias:'порожня аптечка / медична сумка',weight:40});}
 const best=new Map();for(const x of found)if(!best.has(x.id)||x.weight>best.get(x.id).weight)best.set(x.id,x);
 return [...best.values()].sort((a,b)=>b.weight-a.weight);
}
function attributes(input,id){const s=normalize([input.name,input.supplier_category_raw,input.supplier_category_path_raw,input.supplier_subcategory_raw,Object.values(input.attributes||{}).join(' ')].join(' ')),out={};
 if(/жіноч|женск|women|female/u.test(s))out.gender='female';else if(/чоловіч|мужск|male|men'?s/u.test(s))out.gender='male';else if(/унісекс|унисекс|unisex/u.test(s))out.gender='unisex';
 if(/зимов|зимн|winter/u.test(s))out.season='winter';else if(/літн|летн|summer/u.test(s))out.season='summer';else if(/демісез|демисез|demiseason/u.test(s))out.season='demiseason';
 if(/soft_shell/u.test(s))out.material_type='soft_shell';if(/multicam/u.test(s))out.camouflage='multicam';
 if(id==='armor_plates'||id==='armor_soft'||id==='armor_vests'||id==='armor_sets'){const cls=s.match(/([1-6])\s*(?:клас|класс)/u);if(cls)out.protection_class=Number(cls[1]);}
 if(id==='armor_plates'){const dim=s.match(/(\d{2})\s*[xх×]\s*(\d{2})/u);if(dim)out.size=dim[1]+'x'+dim[2];}return out;
}
function supplierContextAllows(category,name,raw){
 const leafText=normalize(raw).split(' / ').pop();
 if(category.id==='clothing_headwear'&&name.id==='clothing_balaclavas'&&/головні убор|головные убор/u.test(leafText))return true;
 if(category.id==='footwear_tactical_boots'&&name.id.startsWith('footwear_')&&/взуття|обувь/u.test(leafText)&&!/(?:черев|ботин)/u.test(leafText))return true;
 if(category.id==='helmets_ballistic'&&name.id.startsWith('helmets_')&&name.id!=='helmets_ballistic'&&!/баліст|баллист/u.test(leafText))return true;
 if(category.id==='bags_tactical'&&name.id.startsWith('bags_')&&/^(?:тактичні |тактические )?сумк/u.test(leafText))return true;
 return false;
}
function supplierPath(input,raw){const full=String(input.supplier_category_path_raw||raw||''),sub=String(input.supplier_subcategory_raw||'');return sub&&normalize(full).split(' / ').pop()!==normalize(sub)?[full,sub].filter(Boolean).join(' / '):full;}
function mappingConfidence(m){return m.confidence==null?1:(Number.isFinite(Number(m.confidence))?Number(m.confidence):0);}
function classify(input={},options={}){const custom=options.categories||[],sid=String(input.supplier_id||''),raw=String(input.supplier_category_raw??''),rawPath=supplierPath(input,raw),name=input.normalized_name||input.name||input.original_name||'',mapping=options.mappings||[];
 const result=(id,source,confidence,rule,extra={})=>({canonical_category_id:id||null,category:id?path(id,custom):'',category_source:source,source:source==='manual'?'manual':source==='mapping'?'auto_mapping':source==='attributes'?'auto_attrs':source==='supplier_rule'?'auto_supplier_category':'auto_name',category_confidence:confidence,category_rule_id:rule,category_status:id?'CONFIRMED':'NEEDS_REVIEW',category_review_status:id?'CONFIRMED':'NEEDS_REVIEW',normalized_name:normalize(name),attributes:attributes({...input,name},id),reasons:[],candidates:[],...extra});
 if(input.category_source==='manual'){const id=leaf(input.canonical_category_id)?input.canonical_category_id:options.manualCategoryId;return id?result(id,'manual',1,'manual'):result(null,'manual',0,'manual-unmapped',{reasons:['Ручне рішення збережено; старий шлях потребує відповідності.']});}
 for(const mode of ['exact','path']){let matches=mapping.filter(m=>m.supplier_id===sid&&m.confirmed!==false&&leaf(m.canonical_category_id)&&(mode==='exact'?String(m.supplier_category_raw)===raw&&(!m.supplier_category_path_raw||normalize(m.supplier_category_path_raw)===normalize(rawPath)):normalize(m.supplier_category_path_raw||m.supplier_category_normalized||m.supplier_category_raw)===normalize(rawPath)));if(mode==='exact'&&matches.some(m=>m.supplier_category_path_raw))matches=matches.filter(m=>m.supplier_category_path_raw);const ids=[...new Set(matches.map(m=>m.canonical_category_id))];if(ids.length>1)return result(null,'conflict',Math.max(...matches.map(m=>mappingConfidence(m))),'mapping-conflict',{category_status:'CONFLICT_REVIEW',category_review_status:'CONFLICT_REVIEW',candidates:ids,reasons:['Суперечливі підтверджені відповідності постачальника.']});if(ids.length===1&&mappingConfidence(matches[0])>=0.8)return result(ids[0],'mapping',mappingConfidence(matches[0]),'mapping-'+mode,{mapping_id:matches[0].id});}
 const byCategory=candidates(rawPath||raw,custom,true),byName=candidates(name,custom),strongCat=byCategory.length===1?byCategory[0]:null,strongName=byName.length===1?byName[0]:null;
 if((strongCat?.id==='medical_ifak'||strongName?.id==='medical_ifak')&&/без\s+(?:наповнен|содержим)|порожн\S*\s+(?:аптеч|сумк|підсум)|empty\s+(?:ifak|medical)/u.test(normalize(input.description||'')))return result(null,'conflict',0.7,'empty-ifak-description',{category_status:'CONFLICT_REVIEW',category_review_status:'CONFLICT_REVIEW',candidates:['medical_ifak','pouches_medical'],reasons:['Опис вказує на порожню аптечку; підтвердіть комплектацію.']});
 if(strongCat&&strongName&&strongCat.id!==strongName.id&&supplierContextAllows(strongCat,strongName,rawPath||raw))return result(strongName.id,'supplier_rule',0.97,'supplier-group-specific-name',{reasons:['Загальна група постачальника уточнена типом виробу в назві.']});
 if(strongCat&&strongName&&strongCat.id!==strongName.id)return result(null,'conflict',0.7,'supplier-name-conflict',{category_status:'CONFLICT_REVIEW',category_review_status:'CONFLICT_REVIEW',candidates:[strongCat.id,strongName.id],reasons:[`Категорія постачальника: ${strongCat.id} (${strongCat.alias})`,`Назва: ${strongName.id} (${strongName.alias})`]});
 if(byCategory.length>1&&strongName&&byCategory.some(x=>x.id===strongName.id))return result(strongName.id,'supplier_rule',0.97,'context-agreement');
 if(byCategory.length>1||byName.length>1)return result(null,'conflict',0.65,'rules-conflict',{category_status:'CONFLICT_REVIEW',category_review_status:'CONFLICT_REVIEW',candidates:[...new Set([...byCategory,...byName].map(x=>x.id))],reasons:['Кілька типів виробу; потрібна ручна перевірка.']});
 if(strongCat)return result(strongCat.id,'supplier_rule',strongName?0.99:0.96,'supplier-alias:'+strongCat.id);
 if(strongName)return result(strongName.id,'name',0.96,'name-alias:'+strongName.id);
 const byDesc=candidates(input.description||'',custom),attrType=Object.entries(input.attributes||{}).filter(([k])=>/^(тип|вид виробу|вид изделия|тип товару|тип виробу|product type|категорія|категория)$/u.test(normalize(k))).map(([,v])=>v).join(' '),byAttrs=candidates(attrType,custom);const suggestions=byDesc.length?byDesc:byAttrs;
 if(suggestions.length)return result(null,byDesc.length?'description':'attributes',suggestions.length===1?0.75:0.6,'weak-context',{candidates:suggestions.map(x=>x.id),suggested_category_id:suggestions.length===1?suggestions[0].id:null,reasons:['Лише опис або характеристики: підтвердіть тип виробу.']});
 return result(null,'unknown',0,'unrecognized',{reasons:['Не знайдено надійного відповідника; товар зберігається.']});
}
function migrationMapping(paths,options={}){return [...new Set(paths)].sort().map(old=>{const exact=catalogue(options.categories).filter(c=>c.parent_id&&path(c.id,options.categories)===old),d=exact.length===1?{canonical_category_id:exact[0].id,category_confidence:1,category_status:'CONFIRMED'}:classify({name:String(old).split(/\s*\/\s*/).pop(),supplier_category_raw:old},options);return {old_category:old,canonical_category_id:d.canonical_category_id,new_category:d.canonical_category_id?path(d.canonical_category_id,options.categories):null,confidence:d.category_confidence,status:d.category_status,candidates:d.candidates||[]};});}
return {VERSION,defaults,negativeRules,equivalents,normalize,catalogue,path,leaf,candidates,classify,attributes,migrationMapping};
