'use strict';
// Offline review candidate. No setters, imports into startup, taxonomy writes or publication calls.
const plain = s => String(s || '').replace(/<[^>]*>/gu, ' ').replace(/&#(x[\da-f]+|\d+);/giu, (_, n) => String.fromCodePoint(n[0].toLowerCase()==='x'?parseInt(n.slice(1),16):Number(n))).replace(/&(nbsp|amp|quot|apos|lt|gt);/gu, (_,n)=>({nbsp:' ',amp:'&',quot:'"',apos:"'",lt:'<',gt:'>'}[n])).replace(/\s+/gu,' ').trim();
const norm = s => plain(s).toLowerCase().replace(/[’`]/gu,"'");
const rule = (id, category, title, facts, reason, tier='SAFE_AUTO') => ({id,category,title,facts,reason,tier});
const rules = [
 rule('grenade-pouch','pouches_grenade',/^підсумок\s+під\s+(?:\d+\s+)?гранат/u,/призначен\S*\s+для\s+(?:двох|двух|\d+)\s+гранат/u,'Изделие — подсумок для гранат. Название модели Double Mag Pouch не перевешивает назначение и конструкцию поставщика.'),
 rule('utility-pouch','pouches_utility',/^підсумок утилітарний/u,/кишен|кишень|карман|організ|органайз|зберігання і транспортування/u,'Утилитарный подсумок подтверждён устройством карманов/организацией хранения.'),
 rule('pouch-not-content','pouches_other',/^(?:чохол )?підсумок (?:під|для) (?:пляшк|оптичн|глушник|глушител)/u,/molle|молле|чохол|чехол|захист|кишен|фіксац|кріплен/u,'Контейнер/подсумок остаётся подсумком; содержимое не является типом изделия.'),
 rule('toiletry-container','pouches_other',/^(?:косметичк|підсумок тактичний для гігієни)/u,/cordura|molle|молле|органайзер|кишен|відділен/u,'Изделие — контейнер для гигиенических принадлежностей, а не средство гигиены.'),
 rule('dangler-complete','pouches_dangler',/^комплект сумка.напашник/u,/функціональн\S*\s+сумка.напашник|зручна,? вмістка і функціональна сумка.напашник/u,'Готовая сумка-напашник с защитной вставкой: основное изделие — функциональная сумка, вставка — часть комплектации.'),
 rule('rigid-phone-mount','electronics_mounts',/^(?:кріплення для смартфона|протиударний нагрудний чохол під смартфон)/u,/abs.?(?:пластик|пластика)|ударостійкого abs/u,'Жёсткий ABS-холдер крепит смартфон ремешками. Это крепление электроники, а не мягкий подсумок для телефона.'),
 rule('fleece-garment','clothing_fleece',/^(?:військова кофта флісова|реглан флісовий)/u,/270\s*г|фліс еластичний|функціональна флісова кофта/u,'Подтверждены самостоятельная кофта/реглан и конструкция/материал; ткань чужого изделия не запускает правило.'),
 rule('rollneck','clothing_fleece',/^базовий тактичний гольф/u,/гольф \(водолазка\).*бавовнян/u,'Действующая категория «Фліс та кофти» включает кофты. Водолазка не объявляется флисовой или термобельём.'),
 rule('war-belt','load_bearing_belts',/^тактичний ремінь war belt/u,/внутрішнього та зовнішнього ременя/u,'Двухкомпонентный разгрузочный пояс подтверждён поставщиком; это не полный РПС и не обычный брючный ремень.'),
 rule('molle-load-belt','load_bearing_belts',/^ремінь тактичний/u,/система molle по всій довжині ременя.*кріплення подсум/u,'Жёсткий пояс для подвеса снаряжения подтверждён конструкцией MOLLE, а не одним словом «тактический».'),
 rule('waist-belt','clothing_belts',/^ремінь (?:тактичний|на фастекс)/u,/(?:об'єм талії|на талію)\s*[-—]?\s*(?:до\s*)?130\s*см/u,'Поставщик прямо задаёт обхват талии/назначение брючного ремня; MOLLE-пояс исключается предыдущим правилом.'),
 rule('trouser-belt','clothing_belts',/^ремінь/u,/брючний пояс|для.*тактичних штанів/u,'Брючный пояс подтверждён поставщиком. Возможность ношения оружия не превращает его в оружейный ремень.'),
 rule('inner-belt','clothing_belts',/^ремінь тактичний з магнітною/u,/основний ремінь під час використання м'якого розвантажувального пояса/u,'Основной/внутренний ремень отделён от наружного разгрузочного пояса.'),
 rule('shoulder-straps','load_bearing_harness',/^підтяжки/u,/y.подібн|y.образн|плеч|рпс/u,'Подтяжки подтверждены плечевой конструкцией; категория «Плечові лямки» уже существует.'),
 rule('weapon-sling','weapon_slings',/^(?:ремінь.*(?:збройовий|триточковий)|додаткове кріплення.ремінь thor)/u,/носіння(?: та фіксації)?(?: стрілецької)? зброї|носи\S* оруж|кріплення зброї/u,'Поставщик описывает полноценный ремень для переноски оружия, а не только антабку или фиксатор.'),
 rule('weapon-retainer','weapon_other',/^(?:ремінь.крюк|магнітний.*(?:фіксатор|тримач)|фіксатор.*mag|mag.r)/u,/збро|оруж/u,'Изделие — фиксатор оружия, не оружейный ремень по сходному слову.'),
 rule('weapon-hardware','weapon_other',/^(?:антабка|сталева антабка|база.*qd|дтк|комплект буферної трубки|(?:руків.?я|рукоятка).*(?:затвор|заряд|зведення)|патрон.*лазер|лазерний.*патрон|додаткове кріплення)/u,/збро|оруж|ar.?15|ar15|передньої антабки|оптичні приціли/u,'Самостоятельная оружейная деталь/крепление отделена от её совместимости, приклада и рукоятки удержания оружия.'),
 rule('charger','power_accessories',/^зарядний пристрій/u,/канал\S* заряджання|заряджан\S* акумуляторів/u,'Зарядный блок подтверждён функцией зарядки аккумуляторов; название «станция» не означает автономную электростанцию.'),
 rule('canteen','field_cookware',/^фляга/u,/матеріал фляги|комплектація.*фляга/u,'Жёсткая фляга/набор с котелком — полевой питьевой сосуд, не мягкий гидратор и не чехол.'),
 rule('gear-clip','field_carabiners',/^кріплення.*gear clip/u,/нейлон|еластичн|затиск|караби|замика/u,'Самостоятельный клипс крепления входит в существующую категорию «Карабіни та кріплення».'),
 rule('textile-balaclava','clothing_balaclavas',/^маска з черепом/u,/балаклав|бавовн|cotton|еластичн|поліестер/u,'Текстильная маска-балаклава не является баллистической защитной маской.'),
 rule('tactical-pen','tools_other',/^(?:металева військова кулькова ручка|тактична ручка)/u,/розбийте вікно|склобій|вольфрам/u,'Тактическая ручка со стеклобоем: самостоятельный инструмент подтверждён конструкцией, а не словом «военная».'),
 rule('armor-kit-complete','armor_sets',/^комплект бронезахисту/u,/у комплекті:.*плитоноска.*бронеплити/u,'Готовый комплект защиты с плитами и пакетами подтверждён составом.'),
 rule('two-module-armor-kit','armor_sets',/^комплект захисту живота та паху/u,/комплект складається з двох тактичних підсумків та.*балістичних пакетів/u,'Поставщик прямо подтверждает две защитные оболочки и два пакета в комплекте; не выбирается категория одной детали.'),
 rule('ballistic-apron','armor_accessories',/^балістичний фартух/u,/захист пахово|захисту пахово|під клапан бронежилета/u,'Модуль защиты отдельной зоны тела, не отдельный мягкий вкладыш и не полный бронежилет.'),
 rule('active-earphones','communications_headsets',/^активні беруші/u,/bluetooth.*беруші|беруші.*bluetooth/u,'Электронные внутриканальные наушники подтверждены активной обработкой звука и Bluetooth, а не только назначением защиты слуха.'),
 rule('phone-communications-accessory','communications_accessories',/^портативний підсилювач зв'язку для телефону/u,/аксесуар.*сигнал|сигнал.*аксесуар/u,'Это аксессуар связи. Категория не подтверждает рекламные обещания усиления сигнала.'),
 // Broad existing categories are disclosed explicitly; a missing dedicated leaf is not a real taxonomy gap.
 rule('field-warmer','field_other',/^(?:грілк|самонагрівна грілка|пак самонагрівних термохімічних грілок)/u,/тепл|нагрів|хімічн|химическ/u,'Химический источник тепла для полевых условий; не перчатки, одежда или обычная стелька.'),
 rule('field-compass','field_other',/^компас/u,/азимут|напрям|орієнт|ориент|навігац/u,'Самостоятельный компас для полевой навигации помещается в действующую общую категорию.'),
 rule('survival-kit','field_other',/^набір для виживання/u,/дикій природі|походах.*природі/u,'Набор полевого выживания: входящий нож/фонарь/компас не подменяет весь набор.'),
 rule('paracord-bracelet','field_other',/^браслет паракорд/u,/браслет виживання|метр\S* паракорду/u,'Паракордовый браслет выживания подтверждён источником; новая узкая категория не обязательна.'),
 rule('portable-water-filter','field_other',/^портативний фільтр для очищення води/u,/кемпінгу|туризму|туриз|мембран/u,'Полевой фильтр воды, не гидратор и не ёмкость; существует допустимая общая полевая категория.'),
 rule('camp-gas-cartridge','field_other',/^балон газовий/u,/полевых условиях|туристических горелок/u,'Полевой газовый картридж — расходный материал, а не горелка; общий полевой раздел уже существует.'),
 rule('outdoor-insect-coils','field_other',/^спіралі від комарів/u,/відкритому повітрі/u,'Спирали для применения на открытом воздухе — полевое оснащение, а не одежда или лекарство.'),
 rule('tactical-timekeeping','field_other',/^(?:годинник наручний skmei|наручний годинник smael|тактичний протиударний годинник skmei|протиударний годинник skmei|skmei.*годинник)/u,/стиль:\s*армійський|армійськ\S*.*спортив|військов\S*.*(?:годинник|час)/u,'Армейский/полевой тип часов и функция времени подтверждены описанием. Общая категория полевого оснащения уже существует.'),
 rule('watch-fallback-policy','field_other',/^(?:годинник|наручний годинник|тактичний протиударний годинник|протиударний годинник|skmei.*годинник|секундомір)/u,/механізм|циферблат|час|формат|будильник|функц|секундомір/u,'В taxonomy есть общий полевой раздел. Нужно одно решение о допустимости такого раздела для часов, включая городские модели; это не доказанный пробел.', 'LIKELY'),
 rule('headwear-kit-policy','clothing_headwear',/^(?:зимовий флісовий комплект|теплий комплект шапка)/u,/шапка.*баф/u,'Комплект шапка+баф: обе существующие категории подходят компонентам. Утвердить основную категорию комплекта один раз.', 'LIKELY'),
 rule('short-sleeve-ubacs','clothing_combat_shirts',/^футболка ubacs/u,/кишені.*рукав|на рукавах.*кишені/u,'Самостоятельный UBACS подтверждён карманами на рукавах и конструкцией для ношения под бронежилетом; не классифицируется по одной ткани.', 'SAFE_AUTO'),
 rule('sleeping-bag-poncho','field_sleeping_bags',/^спальний мішок.пончо/u,/спальний мішок.*сон|сон.*20/u,'Многофункциональный мишок-пончо: реальные функции сна и одежды конкурируют. Достаточно одного решения для семейства.', 'LIKELY'),
 rule('helmet-marker-policy','helmets_accessories',/^стробоскопічний маркер/u,/ідентифікації свій.чужий|маркування розташування/u,'IFF-маячок крепится не только к шлему; согласовать шлемный аксессуар или общий световой прибор.', 'LIKELY'),
 rule('generic-belt-policy','clothing_belts',/^ремінь тактичний/u,/пряжк|довжин|длина|носіння|довжина|регульована/u,'Недостаточно конструкции, чтобы исключить разгрузочный пояс; поставщик использует общее название.', 'LIKELY'),
 rule('pest-trap-policy','field_other',/^клейова пастка/u,/гризун|щурів|миш|клейов/u,'Изделие определено как ловушка. Общий полевой раздел возможен, но описание говорит о помещениях; требуется одно решение о пределах общего раздела.', 'LIKELY')
];
const gaps = [
 {id:'armor_ballistic_blankets',name:'Балістичні ковдри',parent:'armor',title:/^бронековдра/u,facts:/балістичн.*(?:пакет|захист)|пакет.*балістичн/u,aliases:['бронековдра','баллистическое одеяло'],why:'armor_soft — отдельные вкладыши, armor_accessories — аксессуары носимой защиты; field_thermal_blankets — теплоизоляция. Бронековдра является самостоятельным переносным укрытием.',alternatives:['armor_soft','armor_accessories','field_thermal_blankets']},
 {id:'clothing_insulated_vests',name:'Утеплені жилети',parent:'clothing',title:/^(?:жилетка утеплена|зимова тактична жилетка)/u,facts:/безрукав|жилет|синтепон/u,aliases:['утеплена жилетка','жилетка утеплена','утепленный жилет'],why:'clothing_jackets — куртки, clothing_fleece — кофты; armor_vests и load_bearing_systems — защита/разгрузка. Обычный утеплённый жилет без рукавов не является ни одним из них.',alternatives:['clothing_jackets','clothing_fleece','armor_vests','load_bearing_systems']},
 {id:'footwear_care',name:'Догляд за взуттям',parent:'footwear',title:/^(?:водовідштовхуючий спрей|спрей.*(?:замші|нубук)|засіб.*(?:замші|нубук))/u,facts:/взуття|обув|замш|нубук/u,aliases:['спрей для взуття','догляд за взуттям','крем для обуви'],why:'Существующие листья footwear описывают обувь и носимые принадлежности. Спрей/пропитка — средство ухода, не обувь, не стельки и не личная полевая гигиена.',alternatives:['footwear_tactical_boots','footwear_insoles','field_hygiene']},
 {id:'footwear_shoes',name:'Туфлі та лофери',parent:'footwear',title:/^(?:(?:чоловічі|жіночі|класичні|замшеві)\s+)*(?:лофери|туфлі|туфли|лоферы)/u,facts:/лофер|туфл|замш|підошв/u,aliases:['лофери','лоферы','туфлі','туфли'],why:'footwear_boots/footwear_tactical_boots — берцы/ботинки, footwear_sneakers — кроссовки. Классические низкие лоферы не соответствуют этим типам.',alternatives:['footwear_boots','footwear_tactical_boots','footwear_sneakers']},
 {id:'communications_earplugs',name:'Пасивні беруші',parent:'communications',title:/^беруші/u,exclude:/активн|bluetooth|електронн/u,facts:/піни|блокують.*шум|ізоляції від шуму|вставити.*вух/u,aliases:['пасивні беруші','беруші багаторазові','беруши пассивные'],why:'headsets — наушники. Пассивные заглушки без воспроизведения/электроники не являются наушниками. Активные EARMOR M20T остаются кандидатом headsets.',alternatives:['communications_headsets','communications_accessories']},
 {id:'electronics_rf_detectors',name:'Детектори радіосигналів та РЕР',parent:'electronics',title:/^пристрій радіоелектронної розвідки/u,facts:/сканування|перехоплення сигналів/u,aliases:['пристрій радіоелектронної розвідки','детектор радіосигналів','детектор fpv'],why:'radios — радиостанции связи, electronics_monoculars — оптическое наблюдение, electronics_accessories — вспомогательные принадлежности. РЕР-сканер — самостоятельное устройство радионаблюдения.',alternatives:['communications_radios','electronics_monoculars','electronics_accessories']},
 {id:'symbols_flags',name:'Прапори',parent:'symbols',title:/^прапор/u,facts:/прапор|полотнище|древк|люверс/u,aliases:['прапор України','флаг Украины'],why:'camouflage_materials — материалы для скрытия объекта, не государственная символика. Нельзя считать любой флаг полевым снаряжением только по поставщику.',alternatives:['camouflage_materials','field_other']}
];
const watchRule={id:'field_watches',name:'Польові та тактичні годинники',parent:'field_gear',title:/^(?:(?:наручний|наручный|тактичний|тактический|протиударний|чоловічий|жіночий|водонепроникний)\s+)*(?:годинник|часы|watch|wristwatch)(?:\s|$)|^(?:skmei|smael)\s+[\w-]+.*(?:годинник|watch|часы)/u,facts:/циферблат|механізм|механизм|кварц|формат часу|формат времени|відображення дати|хід часу|ход времени|будильник/u,aliases:['годинник наручний','наручний годинник','тактичний годинник','наручные часы','wristwatch'],why:'Пользователь утвердил отдельную категорию для подтверждённого типа watch/годинник. Название категории не подтверждает специальные тактические свойства каждой модели.',alternatives:['field_other']};
const symbolsRoot={id:'symbols',name:'Символіка',parent:null,aliases:[],why:'Для государственных флагов требуется профильный родитель: существующие корни одежды, маскировки и полевого оснащения не описывают символику.'};
function resolve(p,taxonomy,context={}) {
 const leaves=new Set(taxonomy.filter(c=>!c.deprecated&&!taxonomy.some(ch=>ch.parent_id===c.id)).map(c=>c.id));
 const n=norm(p.name),d=norm(p.description),sources=p.sources||[];
 const sourceTitles=sources.map(s=>norm(s.original_name)).filter(Boolean);
 const evidence=(r)=>({supplier_titles:sources.filter(s=>r.title.test(norm(s.original_name))).map(s=>({supplier_id:s.supplier_id,title:s.original_name})),supplier_attributes:Object.fromEntries(Object.entries(p.attrs||{}).filter(([k])=>/^(тип|вид|призначення|система кріплення)/u.test(norm(k)))),description_excerpt:plain(p.description).slice(Math.max(0,d.search(r.facts)-100),Math.max(0,d.search(r.facts)-100)+420)});
 const locked=p.locked||p.category_locked||['category','canonical_category_id','primary_product_type'].some(k=>p.manual_locks?.[k]||p.fieldMeta?.[k]?.source==='manual')||[p.source,p.category_source,p.catSource].includes('manual')||/^(?:mapping-|exact-product:)/u.test(p.category_rule_id||'');
 const result=(tier,rule_id,reason,more={})=>({id:p.id,name:p.name,partition:'EXISTING_CATEGORY_AMBIGUOUS',tier,rule_id,reason,...more});
 if(locked)return result('AMBIGUOUS','protected-existing-decision','Подтверждённая категория/ручная блокировка сохранена.');
 const protectedMapping=(context.mappingDecisions||[]).find(m=>sources.some(s=>s.supplier_id===m.supplier_id)&&/^(?:mapping-|exact-product:)/u.test(m.category_rule_id||''));
 if(protectedMapping)return result('AMBIGUOUS','protected-supplier-mapping','Подтверждённая supplier mapping сохранена; новое правило не заменяет соответствие.',{category:protectedMapping.canonical_category_id});
 if(watchRule.title.test(n)&&leaves.has('field_watches')){
 const proven=watchRule.facts.test(d)&&sourceTitles.length&&sourceTitles.every(t=>watchRule.title.test(t));
 return result(proven?'SAFE_AUTO':'LIKELY','watch-evidence-approved-scope',proven?'Поставщик подтверждает самостоятельные часы и устройство/функции времени; применена одобренная область watch/годинник только в виртуальном dry-run.':'Название похоже на часы, но независимого подтверждения типа/функций недостаточно.',{category:'field_watches',evidence:evidence(watchRule)});
 }
 for(const g of gaps) if(g.title.test(n)&&g.facts.test(d)&&!g.exclude?.test(n+' '+d)&&sourceTitles.length&&sourceTitles.every(t=>g.title.test(t))){
 if(leaves.has(g.id)){
 const mismatch=g.id==='communications_earplugs'&&/earmor/u.test(n)&&/maxdefense/u.test(d);
 return result(mismatch?'LIKELY':'SAFE_AUTO','existing-profile-category:'+g.id,mismatch?'Пассивные беруши определены, но EARMOR в исходном названии и MaxDefense в описании не согласованы; исключение не закрывается принудительно.':'Профильная категория доступна только в виртуальной taxonomy dry-run; рабочий справочник не изменён.',{category:g.id,evidence:evidence(g),warnings:mismatch?['SOURCE_MODEL_MISMATCH: EARMOR vs MaxDefense']:[]});
 }
 return result('AMBIGUOUS','taxonomy-gap:'+g.id,g.why,{partition:'TAXONOMY_GAP',proposed_category_id:g.id,considered_categories:g.alternatives,evidence:evidence(g),warnings:g.id==='communications_earplugs'&&/earmor/u.test(n)&&/maxdefense/u.test(d)?['SOURCE_MODEL_MISMATCH: EARMOR в названии, MaxDefense в описании. Категория пассивных берушей ясна, идентичность модели требует проверки.']:[]});
 }
 // A title claiming a bundle plus source describing a separately sold cover is a genuine composition conflict.
 if(/^комплект \(захист живота/u.test(n))return result('AMBIGUOUS','armor-cover-or-complete','Название: комплект с защитой. Описание: чехол под пакет/возможность покупки отдельно. Нет однозначного SKU-level состава.',{category:'armor_accessories',considered_categories:['armor_accessories','armor_sets','armor_soft']});
 const matched=rules.filter(r=>r.title.test(n)&&r.facts.test(d)&&sourceTitles.length&&sourceTitles.every(t=>r.title.test(t))&&leaves.has(r.category));
 if(matched.length){const r=matched[0];return result(r.tier,r.id,r.reason,{category:r.category,evidence:evidence(r)});}
 if(/^ремінь (?:одно|дво)точковий/u.test(n)){
  const supplierGroup=sources.find(s=>/komplektuyuschie dlya oruzhiya/u.test(norm(s.supplier_category_path_raw||s.supplier_category_raw)));
  const neighbors=(context.neighbors||[]).filter(x=>x.supplier_id===supplierGroup?.supplier_id&&norm(x.supplier_group)===norm(supplierGroup?.supplier_category_path_raw||supplierGroup?.supplier_category_raw)&&x.category==='weapon_slings'&&x.independent_source_evidence===true);
  if(supplierGroup&&neighbors.length&&sourceTitles.some(t=>/^ремінь (?:одно|дво)точковий/u.test(t)))return result('SAFE_AUTO','point-sling-supplier-neighbors','Топология 1/2 точек + оружейная группа поставщика + независимо подтверждённые ремни этой же группы. Схожесть имени не используется.',{category:'weapon_slings',evidence:{supplier_group:supplierGroup.supplier_category_path_raw,neighbors:neighbors.map(x=>({id:x.id,category:x.category,source_excerpt:x.source_excerpt}))}});
  return result('LIKELY','point-sling-insufficient-evidence','Точечный ремень и оружейная supplier group согласуются, но SKU-level описание крайне короткое; одного раздела поставщика недостаточно.',{category:'weapon_slings'});
 }
 const titleRules=rules.filter(r=>r.title.test(n)&&leaves.has(r.category));
 return result(titleRules.length?'LIKELY':'AMBIGUOUS','insufficient-independent-evidence',titleRules.length?'Название указывает существующую категорию, но функционального подтверждения недостаточно.':'Для уверенного решения не хватает данных о самом изделии; отсутствие alias не является доказательством taxonomy gap.',{category:titleRules[0]?.category||null,considered_categories:p.candidates||[]});
}
module.exports={resolve,rules,gaps,watchRule,symbolsRoot,plain,norm};
