const {test}=require('node:test'),assert=require('node:assert/strict'),C=require('../lib/categories.js'),{createHarness}=require('./isolated-harness.cjs');
const cases=[['Куртка зимова чоловіча Soft Shell Multicam','clothing_jackets'],['Куртки тактические','clothing_jackets'],['берцы','footwear_boots'],['тактичні берці','footwear_boots'],['UBACS','clothing_combat_shirts'],['combat shirt','clothing_combat_shirts'],['боевая рубашка','clothing_combat_shirts'],['plate carrier','armor_plate_carriers'],['Кавер на шолом Fast Multicam','helmets_covers'],['Підсумок для рації','pouches_radio'],['Чохол для зброї','weapon_cases'],['Сумка для шолома','bags_tactical'],['Рюкзак для шолома','bags_backpacks'],['Сумка для аптечки','pouches_medical'],['Підсумок під 2 гранати','pouches_grenade'],['Підсумок під 2 магазини','pouches_magazine'],['Бронеплита 4 клас 25x30','armor_plates'],['Флісова куртка','clothing_fleece'],['Куртка с флисовой подкладкой','clothing_jackets'],['Штани фліс','clothing_pants'],['Ремінь для плитоноски','armor_accessories'],['Балистический пакет','armor_soft'],['Маскувальна сітка Militex Мультикам','camouflage_nets'],['Антидронова сітка','camouflage_antidrone'],['Тренувальний турнікет','medical_training'],['Налобний ліхтар','lighting_headlamps'],['Поясна сумка','bags_waist'],['Штурмовий рюкзак','bags_assault_backpacks']];for(const [name,id] of cases)test('canonical context: '+name,()=>{const d=C.classify({name});assert.equal(d.canonical_category_id,id);assert.ok(d.category_confidence>=.95);});
for(const name of ['магазин Рубіж','плита для кухні','Soft Shell Multicam','Продукт ZX-100','Кріплення для маскувальної сітки'])test('ambiguous words remain review: '+name,()=>{const d=C.classify({name});assert.equal(d.canonical_category_id,null);assert.equal(d.category_status,'NEEDS_REVIEW');});
test('requested category IDs are unique and stable when names change',()=>{assert.equal(C.defaults.length,143);assert.equal(new Set(C.defaults.map(c=>c.id)).size,143);assert.equal(C.path('clothing_jackets',[{id:'clothing_jackets',name:'Куртки нового каталогу'}]),'Одяг та форма / Куртки нового каталогу');assert.equal(C.classify({name:'Куртка'}).canonical_category_id,'clothing_jackets');});
test('normalization handles RU/UA, spaces, apostrophes, punctuation and transliteration',()=>{assert.equal(C.normalize('  Мужская одежда → Куртки  '),'чоловіча одежда / куртка');assert.equal(C.classify({name:'kurtka'}).canonical_category_id,'clothing_jackets');assert.equal(C.normalize('М’який — пакет'),'м\'який - пакет');});
test('classification extracts attributes without creating public categories',()=>{const d=C.classify({name:'Куртка зимова чоловіча Soft Shell Multicam'});assert.deepEqual(d.attributes,{gender:'male',season:'winter',material_type:'soft_shell',camouflage:'multicam'});assert.deepEqual(C.classify({name:'Бронеплита 4 клас 25x30'}).attributes,{protection_class:4,size:'25x30'});assert.equal(C.defaults.length,143);});
test('confirmed mapping outranks keywords and remains scoped to one supplier',()=>{const options={mappings:[{supplier_id:'a',supplier_category_raw:'Особлива група',canonical_category_id:'clothing_jackets',confirmed:true,confidence:1}]};assert.equal(C.classify({supplier_id:'a',supplier_category_raw:'Особлива група',name:'Рюкзак'},options).canonical_category_id,'clothing_jackets');assert.equal(C.classify({supplier_id:'b',supplier_category_raw:'Особлива група',name:'Рюкзак'},options).canonical_category_id,'bags_backpacks');});
test('confirmed supplier path mapping works when raw category changes',()=>{const d=C.classify({supplier_id:'a',supplier_category_raw:'нова назва',supplier_category_path_raw:'Мужская одежда > куртки'},{mappings:[{supplier_id:'a',supplier_category_raw:'старое',supplier_category_normalized:C.normalize('Мужская одежда / куртки'),canonical_category_id:'clothing_jackets',confidence:.9}]});assert.equal(d.canonical_category_id,'clothing_jackets');assert.equal(d.category_rule_id,'mapping-path');});
test('manual choice has priority over mapping and automatic classification',()=>{const d=C.classify({category_source:'manual',canonical_category_id:'armor_soft',name:'Бронеплита',supplier_id:'a',supplier_category_raw:'plates'},{mappings:[{supplier_id:'a',supplier_category_raw:'plates',canonical_category_id:'armor_plates'}]});assert.equal(d.canonical_category_id,'armor_soft');});
test('supplier name disagreement is a conflict with both reasons',()=>{const d=C.classify({name:'Підсумок для аптечки',supplier_category_raw:'Рюкзаки'});assert.equal(d.canonical_category_id,null);assert.equal(d.category_status,'CONFLICT_REVIEW');assert.deepEqual(d.candidates,['bags_backpacks','pouches_medical']);assert.equal(d.reasons.length,2);});
test('contradictory confirmed mappings are not arbitrarily selected',()=>{const d=C.classify({supplier_id:'a',supplier_category_raw:'x'},{mappings:['clothing_jackets','clothing_pants'].map(id=>({supplier_id:'a',supplier_category_raw:'x',canonical_category_id:id}))});assert.equal(d.category_status,'CONFLICT_REVIEW');});
test('description-only and attribute-only evidence stays a suggestion',()=>{for(const input of [{name:'ABC',description:'Тактична куртка.'},{name:'ABC',attributes:{Тип:'Куртка'}}]){const d=C.classify(input);assert.equal(d.canonical_category_id,null);assert.equal(d.suggested_category_id,'clothing_jackets');assert.ok(d.category_confidence<.8);}});
async function stored(h){await h.run('Store.init()');h.run('markAllDirty();workflowYield=async()=>{};');assert.equal(await h.run('persist()'),true);}
async function migrate(h){await stored(h);h.run('CATEGORY_UI.dry=categoryMigrationPlan()');return h.run('categoryMigrationApply()');}
function automaticProduct(h,over={}){const p=h.product(over);p.catSource='auto_name';return p;}
test('dry run is non-mutating and reports every old path',()=>{const h=createHarness();h.add(automaticProduct(h));const before=h.run('JSON.stringify(fullStateData().products)');const plan=h.run('categoryMigrationPlan()');assert.equal(h.run('JSON.stringify(fullStateData().products)'),before);assert.equal(h.run('categoriesEnabled()'),false);assert.equal(plan.summary.lost_products,0);assert.ok(plan.old_mapping.some(x=>x.old_category===h.product().category));});
test('migration keeps IDs, variant SKUs, photos, status, prices, stock, minimum margin and full backup',async()=>{const h=createHarness();h.add(automaticProduct(h));h.run("S.cfg.rules=[{scope:'category',value:S.products.get('p-a').category,markup:80,priority:100}]");const before=h.run("JSON.stringify([S.cfg.minMargin,S.cfg.rules,calc(S.products.get('p-a'),S.products.get('p-a').variants[0]).price])");const result=await migrate(h);assert.equal(result.validation.ok,true);assert.equal(result.validation.price_changes,0);assert.equal(result.validation.stock_changes,0);assert.equal(h.run("JSON.stringify([S.cfg.minMargin,S.cfg.rules,calc(S.products.get('p-a'),S.products.get('p-a').variants[0]).price])"),before);assert.equal(h.run("S.products.get('p-a').canonical_category_id"),'bags_backpacks');const backup=await h.run("Store.get('safety/before_category_migration')");assert.equal(backup.products[0].id,'p-a');assert.equal(backup.products[0].variants[0].sku,'RUB-00001');assert.equal(h.run('S.cfg.canonical_categories.length'),143);});
test('unknown and conflicting products survive migration and remain published locally',async()=>{const h=createHarness();const a=automaticProduct(h,{name:'ABC Unknown',category:'Категорія незнайома',srcCat:'Незнайома'});h.add(a);const b=automaticProduct(h,{id:'p-b',name:'Підсумок для аптечки',category:'Рюкзаки',srcCat:'Рюкзаки'});b.variants[0].sku='RUB-00002';b.variants[0].offers['supplier-a'].s='feed-b';h.add(b);await migrate(h);assert.equal(h.run('S.products.size'),2);assert.equal(h.run("S.products.get('p-a').canonical_category_id"),null);assert.equal(h.run("S.products.get('p-b').category_status"),'CONFLICT_REVIEW');assert.equal(h.run("S.products.get('p-a').pub"),true);assert.equal(h.run("S.products.get('p-a').archived"),false);assert.equal(h.run('categoryPublicationRetainedIds().length'),2);});
test('migration refuses a stale dry run or a declared data-loss risk',async()=>{const h=createHarness();h.add(automaticProduct(h));await stored(h);h.run('CATEGORY_UI.dry=categoryMigrationPlan();bumpData()');await assert.rejects(h.run('categoryMigrationApply()'),/змінився/);h.run('CATEGORY_UI.dry=categoryMigrationPlan();CATEGORY_UI.dry.summary.lost_variants=1');await assert.rejects(h.run('categoryMigrationApply()'),/заблоковано/);assert.equal(h.run('categoriesEnabled()'),false);});
test('failed backup prevents any category mutation',async()=>{const h=createHarness();h.add(automaticProduct(h));await stored(h);h.run("CATEGORY_UI.dry=categoryMigrationPlan();requireBatchBackup=async()=>{throw Error('backup unavailable');}");await assert.rejects(h.run('categoryMigrationApply()'),/backup unavailable/);assert.equal(h.run('categoriesEnabled()'),false);assert.equal(h.run("S.products.get('p-a').category"),h.product().category);});
test('failed migration commit restores original categories in memory and storage',async()=>{const h=createHarness();h.add(automaticProduct(h));await stored(h);h.run("CATEGORY_UI.dry=categoryMigrationPlan();Store.catalogCommit=async()=>{throw Error('write refused');}");await assert.rejects(h.run('categoryMigrationApply()'),/не збережено/);assert.equal(h.run('categoriesEnabled()'),false);assert.equal(h.run("S.products.get('p-a').category"),h.product().category);const old=await h.run("Store._get0('cat/'+bucketOf('p-a',NB))");assert.equal(old.products['p-a'].canonical_category_id,undefined);});
test('manual decision persists, adds history, and is never learned as a mapping implicitly',async()=>{const h=createHarness();h.add(automaticProduct(h));await migrate(h);await h.run("categoryConfirm('p-a','bags_tactical')");assert.equal(h.run("S.products.get('p-a').category_source"),'manual');assert.equal(h.run("S.products.get('p-a').category_history.at(-1).new_category"),'bags_tactical');assert.equal(h.run('S.cfg.supplier_category_mapping.length'),0);assert.equal(h.run("categoryDecisionForProduct(S.products.get('p-a')).canonical_category_id"),'bags_tactical');});
test('bulk mapping protects manual decisions and all offers and prices',async()=>{const h=createHarness();for(let i=0;i<2;i++){const p=automaticProduct(h,{id:'p-'+i,srcCat:'Спецгрупа'});p.variants[0].sku='RUB-'+i;p.variants[0].offers['supplier-a'].s='feed-'+i;h.add(p);}await migrate(h);await h.run("categoryConfirm('p-0','bags_backpacks')");const before=h.run("JSON.stringify([...S.products.values()].map(p=>p.variants))");await h.run("categoryBulk('supplier-a','Спецгрупа','bags_tactical')");assert.equal(h.run("S.products.get('p-0').canonical_category_id"),'bags_backpacks');assert.equal(h.run("S.products.get('p-1').canonical_category_id"),'bags_tactical');assert.equal(h.run("JSON.stringify([...S.products.values()].map(p=>p.variants))"),before);assert.equal(h.run('S.cfg.supplier_category_mapping[0].confidence'),1);});
function priceRows(category='Рюкзаки',sku='feed-a',id='feed-a'){return [['sku','name','price','stock','category','size','color','product_id'],[sku,'Рюкзак Test Pack',1000,5,category,'','Олива',id]];}
const map={sku:0,name:1,cost:2,stock:3,category:4,size:5,color:6,supplierProductId:7};
test('unknown changed supplier category retains last confirmed canonical ID and records original data',async()=>{const h=createHarness();h.add(automaticProduct(h));await migrate(h);h.ctx.rows=priceRows('Нова категорія');h.ctx.rows[1][1]='ABC Unknown';h.run("S.cfg.suppliers[0].auto=true;runImport(S.cfg.suppliers[0],rows,0,{sku:0,name:1,cost:2,stock:3,category:4,size:5,color:6,supplierProductId:7},{file:'test',zeroMissing:false})");assert.equal(h.run('S.products.size'),1);assert.equal(h.run("S.products.get('p-a').canonical_category_id"),'bags_backpacks');assert.match(h.run("S.products.get('p-a').category_warnings.join(' ')"),/SUPPLIER_CATEGORY_CHANGED/);assert.equal(h.run("S.products.get('p-a').supplier_category_raw"),'Нова категорія');});
test('stable supplier product ID matches an existing variant after supplier SKU changes',async()=>{const h=createHarness();const p=automaticProduct(h);p.variants[0].offers['supplier-a'].supplier_product_id='product-123';h.add(p);await migrate(h);h.ctx.rows=priceRows('Рюкзаки','new-supplier-sku','product-123');h.ctx.map=map;h.run("S.cfg.suppliers[0].auto=true;runImport(S.cfg.suppliers[0],rows,0,map,{file:'test',zeroMissing:false})");assert.equal(h.run('S.products.size'),1);assert.equal(h.run("S.products.get('p-a').variants.length"),1);assert.equal(h.run("S.products.get('p-a').variants[0].sku"),'RUB-00001');assert.equal(h.run("S.products.get('p-a').variants[0].offers['supplier-a'].s"),'new-supplier-sku');});
test('source categories, canonical categories and empty categories do not influence grouping',()=>{const h=createHarness();h.run('S.cfg.category_engine={version:1,migration_validated:true};');h.ctx.items=['Куртка Alpha','Куртка Beta'].flatMap((name,i)=>['S','M'].map((size,j)=>({k:`a|${i}-${j}`,sup:'supplier-a',s:`${i}-${j}`,n:name+' '+size,photos:['https://rubizh.shop/'+i+'.webp'],b:'TEST',sz:size,rz:size,c:'Олива',rc:'Олива',rcat:j?'Нова група':'Інша група',attrs:{},cost:1000,stock:2})));assert.equal(h.run('buildGroups(items).length'),2);assert.equal(h.run('buildGroups(items)[0].items.length'),2);});
test('new unknown products import without deletion, random category or preorder invention',async()=>{const h=createHarness();await migrate(h);h.ctx.rows=priceRows('Невідомо','unknown-a');h.ctx.rows[1][1]='Mystery ZX';h.ctx.rows[1][3]=0;h.ctx.map=map;h.run("S.cfg.suppliers[0].auto=true;runImport(S.cfg.suppliers[0],rows,0,map,{file:'test',zeroMissing:false})");assert.equal(h.run('S.products.size'),1);assert.equal(h.run('[...S.products.values()][0].canonical_category_id'),null);assert.equal(h.run('[...S.products.values()][0].category_status'),'NEEDS_REVIEW');assert.equal(h.run('[...S.products.values()][0].variants[0].offers["supplier-a"].preorder'),false);assert.equal(h.run('[...S.products.values()][0].archived'),false);});
test('feed sends canonical IDs and the approved tree while excluding supplier raw categories',async()=>{const h=createHarness();h.add(automaticProduct(h));await migrate(h);const feed=h.run('buildFeed().feed');assert.equal(feed.products[0].canonical_category_id,'bags_backpacks');assert.equal(feed.products[0].category,'Рюкзаки, сумки та баули / Рюкзаки');assert.equal(feed.products[0].supplier_category_raw,undefined);assert.ok(feed.categories.some(c=>c.id==='bags_backpacks'&&c.parent_id==='bags'));});
test('review page shows source, confidence, conflicts, confirmation and bulk mapping',()=>{const h=createHarness();h.add(automaticProduct(h,{name:'ABC',category:'Unknown',srcCat:'Test source'}));const html=h.run('vCategorization()');for(const text of ['Категоризація','Dry run','Підтвердити','Створити mapping','Test source','Низька впевненість','Застосувати до всіх'])assert.ok(html.includes(text),text);});
for(const [name,raw,id] of [['Балаклава мікрофліс','Головні убори','clothing_balaclavas'],['Кавер на шолом FAST','Шоломи','helmets_covers'],['Берці Alpha','Тактичне взуття','footwear_boots'],['Кросівки Alpha','Взуття','footwear_sneakers']])test('broad supplier group is refined by a specific product: '+name,()=>assert.equal(C.classify({name,supplier_category_raw:raw}).canonical_category_id,id));
test('explicit contradictory helmet types remain a conflict',()=>assert.equal(C.classify({name:'Кавер на шолом',supplier_category_raw:'Балістичні шоломи'}).category_status,'CONFLICT_REVIEW'));
test('secondary kit components cannot change the primary product type',()=>{assert.equal(C.classify({name:'Штани з наколінниками'}).canonical_category_id,'clothing_pants');assert.equal(C.classify({name:'Плитоноска з підсумками для магазинів'}).canonical_category_id,'armor_plate_carriers');assert.equal(C.classify({name:'Бронежилет Phantom. Плитоноска з підсумками'}).category_status,'CONFLICT_REVIEW');});
test('weapon magazine requires a concrete weapon or caliber',()=>{assert.equal(C.classify({name:'Магазин для АК 5.45'}).canonical_category_id,'weapon_magazines');assert.equal(C.classify({name:'Підсумок для магазину АК'}).canonical_category_id,'pouches_magazine');assert.equal(C.classify({name:'Магазин для речей'}).canonical_category_id,null);});
test('migration report retains original counts after dry run is cleared',async()=>{const h=createHarness();h.add(automaticProduct(h));await migrate(h);const report=h.run('categoryReport()');assert.equal(report.before.products,1);assert.equal(report.before.variants,1);assert.equal(report.migration_after.products,1);assert.equal(report.validation.ok,true);});
function queueItem(){return {k:'supplier-a|unknown-1',sup:'supplier-a',s:'unknown-1',n:'ABC Mystery',sz:'M',rz:'M',c:'Олива',rc:'Олива',cat:'',rcat:'Спецгрупа',attrs:{},cost:1000,stock:2,ig:0};}
test('failed queued manual assignment restores every item and prevents false confirmation',async()=>{const h=createHarness();await migrate(h);h.ctx.q=queueItem();h.run('S.queue.set(q.k,q);markQueue(q.k)');await h.run('persist()');const row=h.run('categoryQueueProducts()[0].id'),before=h.run('JSON.stringify([...S.queue.values()])');h.ctx.row=row;h.run("Store.catalogCommit=async()=>{throw Error('write refused');}");await assert.rejects(h.run("categoryConfirm(row,'clothing_jackets')"),/не збережено/);assert.equal(h.run('JSON.stringify([...S.queue.values()])'),before);});
test('failed bulk assignment rolls back queued decisions and supplier mapping',async()=>{const h=createHarness();await migrate(h);h.ctx.q=queueItem();h.run('S.queue.set(q.k,q);markQueue(q.k)');await h.run('persist()');const before=h.run('JSON.stringify([...S.queue.values()])');h.run("requireBatchBackup=async()=>true;Store.catalogCommit=async()=>{throw Error('write refused');}");await assert.rejects(h.run("categoryBulk('supplier-a','Спецгрупа','clothing_jackets')"));assert.equal(h.run('JSON.stringify([...S.queue.values()])'),before);assert.equal(h.run('S.cfg.supplier_category_mapping.length'),0);});
test('table category edit updates canonical ID and preserves its old pricing scope',async()=>{const h=createHarness();h.add(automaticProduct(h));await migrate(h);const pricing=h.run("S.products.get('p-a').pricing_category_path");h.run("setFieldRaw(S.products.get('p-a'),'category',canonicalPath('bags_tactical'))");assert.equal(h.run("S.products.get('p-a').canonical_category_id"),'bags_tactical');assert.equal(h.run("S.products.get('p-a').category_source"),'manual');assert.equal(h.run("S.products.get('p-a').pricing_category_path"),pricing);assert.throws(()=>h.run("setFieldRaw(S.products.get('p-a'),'category','Случайная категория')"));});
test('Armoline models with one supplier category do not merge into a giant card',()=>{const h=createHarness();h.ctx.items=Array.from({length:200},(_,i)=>['S','M'].map(size=>({k:'arm|'+i+'|'+size,sup:'supplier-a',s:'arm-'+i+'-'+size,n:'Куртка Model'+i+' '+size,sz:size,rz:size,c:'Олива',rc:'Олива',rcat:'Куртки',cat:'Одяг та форма / Куртки',m:'Model'+i,attrs:{},cost:1000,stock:2}))).flat();assert.equal(h.run('buildGroups(items).length'),200);assert.equal(h.run('Math.max(...buildGroups(items).map(g=>g.items.length))'),2);});
test('a shared parent product ID cannot silently attach an unrelated changed SKU',async()=>{const h=createHarness();for(let i=0;i<2;i++){const p=automaticProduct(h,{id:'p-'+i,name:'Куртка Model'+i});p.variants[0].sku='RUB-'+i;p.variants[0].offers['supplier-a'].s='feed-'+i;p.variants[0].offers['supplier-a'].supplier_product_id='shared-parent';h.add(p);}await migrate(h);h.ctx.rows=priceRows('Куртки','changed-unknown','shared-parent');h.ctx.rows[1][1]='Куртка New Model';h.ctx.map=map;h.run("S.cfg.suppliers[0].auto=false;runImport(S.cfg.suppliers[0],rows,0,map,{file:'test',zeroMissing:false})");assert.equal(h.run('S.products.size'),2);assert.equal(h.run('S.queue.size'),1);assert.equal(h.run('S.products.get("p-0").variants[0].offers["supplier-a"].s'),'feed-0');});
test('unsupported shop is blocked before any category or product POST',async()=>{const h=createHarness();h.add(automaticProduct(h));await migrate(h);h.run("siteReady=()=>true;pimKitPayload=()=>null;window.posts=0;siteFetch=async(path,opt)=>{if(opt?.method==='POST')posts++;return {ok:true,capabilities:{}};}");assert.equal(await h.run("sitePublish('full',{silent:true})"),null);assert.equal(h.run('posts'),0);assert.match(h.run('S.cfg.siteSync.lastError'),/canonical_category_id/);});
test('full publication protects unknown previously published IDs from deletion',async()=>{const h=createHarness();h.add(automaticProduct(h,{name:'Mystery ABC',srcCat:'Mystery'}));await migrate(h);h.run("siteReady=()=>true;pimKitPayload=()=>null;window.lastBody=null;siteFetch=async(path,opt)=>{if(path==='/pim/status')return {capabilities:{canonical_category_version:1}};lastBody=JSON.parse(opt.body);return {ok:true,category_catalog_hash:lastBody.category_catalog_hash,results:[],hidden:0};}");await h.run("Store.set('site/hashes',{'p-a':'oldhash'})");assert.ok(await h.run("sitePublish('full',{silent:true})"));assert.ok(h.run('lastBody.all_ids.includes("p-a")'));assert.equal(h.run('lastBody.hide_ids?.includes("p-a")||false'),false);});
test('shop must acknowledge the exact canonical product ID before its hash is stored',async()=>{const h=createHarness();h.add(automaticProduct(h));await migrate(h);h.run("siteReady=()=>true;pimKitPayload=()=>null;siteFetch=async(path,opt)=>{if(path==='/pim/status')return {capabilities:{canonical_category_version:1}};const b=JSON.parse(opt.body);return {ok:true,category_catalog_hash:b.category_catalog_hash,results:b.products.map(p=>({id:p.id,status:'updated',canonical_category_id:'wrong-id'})),hidden:0};}");assert.equal(await h.run("sitePublish('full',{silent:true})"),null);assert.match(h.run('S.cfg.siteSync.lastError'),/canonical_category_id/);assert.notEqual(h.run('S.products.get("p-a").syncStatus'),'synced');assert.equal(await h.run("Store.get('site/hashes')"),null);});
test('unknown products can be manually resolved in dry run without changing the live catalog',async()=>{const h=createHarness();h.add(automaticProduct(h,{name:'ABC Unknown',srcCat:'Спецгрупа'}));await stored(h);const before=h.run('JSON.stringify([...S.products.values()])');h.run('CATEGORY_UI.dry=categoryMigrationPlan()');await h.run("categoryConfirm('p-a','tools_other')");assert.equal(h.run('JSON.stringify([...S.products.values()])'),before);assert.equal(h.run('CATEGORY_UI.dry.summary.unknown'),0);assert.equal(h.run('categoryQueueProducts()[0].decision.canonical_category_id'),'tools_other');await h.run('categoryMigrationApply()');assert.equal(h.run('S.products.get("p-a").canonical_category_id'),'tools_other');assert.equal(h.run('S.products.get("p-a").category_source'),'manual');});
test('bulk dry-run mapping remains staged until migration and preserves manual proposals',async()=>{const h=createHarness();for(let i=0;i<2;i++){const p=automaticProduct(h,{id:'p-'+i,name:'ABC '+i,srcCat:'Спецгрупа'});p.variants[0].sku='RUB-'+i;p.variants[0].offers['supplier-a'].s='feed-'+i;h.add(p);}await stored(h);h.run('CATEGORY_UI.dry=categoryMigrationPlan()');await h.run("categoryConfirm('p-0','tools_other')");h.run("categoryStageMapping('supplier-a','Спецгрупа','bags_tactical',{bulk:true})");assert.equal(h.run('S.cfg.supplier_category_mapping?.length||0'),0);assert.equal(h.run('CATEGORY_UI.dry.rows.find(r=>r.id==="p-0").decision.canonical_category_id'),'tools_other');assert.equal(h.run('CATEGORY_UI.dry.rows.find(r=>r.id==="p-1").decision.canonical_category_id'),'bags_tactical');await h.run('categoryMigrationApply()');assert.equal(h.run('S.cfg.supplier_category_mapping.length'),1);assert.equal(h.run('S.products.get("p-0").canonical_category_id'),'tools_other');});
test('a stale dry run cannot be made current by confirming a category',async()=>{const h=createHarness();h.add(automaticProduct(h));await stored(h);h.run('CATEGORY_UI.dry=categoryMigrationPlan();bumpData()');await assert.rejects(h.run("categoryConfirm('p-a','bags_tactical')"),/Каталог змінився/);assert.equal(h.run('categoriesEnabled()'),false);});
test('a queued manual category survives the next supplier import',async()=>{const h=createHarness();await migrate(h);h.ctx.rows=priceRows('Невідомо','unknown-1');h.ctx.rows[1][1]='ABC Mystery';h.ctx.map=map;h.run("S.cfg.suppliers[0].auto=false;runImport(S.cfg.suppliers[0],rows,0,map,{file:'test',zeroMissing:false});S.snap=null;");h.ctx.row=h.run('categoryQueueProducts()[0].id');await h.run("categoryConfirm(row,'tools_other')");h.ctx.rows[1][4]='Куртки';h.run("runImport(S.cfg.suppliers[0],rows,0,map,{file:'test',zeroMissing:false})");assert.equal(h.run('[...S.queue.values()][0].canonical_category_id'),'tools_other');assert.equal(h.run('[...S.queue.values()][0].category_source'),'manual');assert.match(h.run('[...S.queue.values()][0].category_warnings.join(" ")'),/SUPPLIER_CATEGORY_CHANGED/);});
test('processing one old SKU does not make a shared parent ID unique for the next row',async()=>{const h=createHarness();for(let i=0;i<2;i++){const p=automaticProduct(h,{id:'p-'+i,name:'Куртка Model'+i});p.variants[0].sku='RUB-'+i;p.variants[0].offers['supplier-a'].s='feed-'+i;p.variants[0].offers['supplier-a'].supplier_product_id='shared-parent';h.add(p);}await migrate(h);h.ctx.rows=priceRows('Куртки','feed-0','shared-parent');h.ctx.rows[1][1]='Куртка Model0';h.ctx.rows.push(['new-unknown','Куртка Third Model',1000,5,'Куртки','','Олива','shared-parent']);h.ctx.map=map;h.run("S.cfg.suppliers[0].auto=false;runImport(S.cfg.suppliers[0],rows,0,map,{file:'test',zeroMissing:false})");assert.equal(h.run('S.products.size'),2);assert.equal(h.run('S.queue.size'),1);assert.equal(h.run('S.products.get("p-0").variants[0].offers["supplier-a"].s'),'feed-0');});
test('category undo restores canonical ID and automatic provenance alongside the displayed path',async()=>{const h=createHarness();h.add(automaticProduct(h));await migrate(h);const old=h.run('S.products.get("p-a").category');h.ctx.old=old;h.ctx.entry=await h.run("applyChanges('Test category edit',[{pid:'p-a',field:'category',before:old,after:canonicalPath('bags_tactical')}])");assert.equal(h.run('S.products.get("p-a").canonical_category_id'),'bags_tactical');await h.run('undoMass(entry.id)');assert.equal(h.run('S.products.get("p-a").canonical_category_id'),'bags_backpacks');assert.equal(h.run('S.products.get("p-a").category'),old);assert.notEqual(h.run('S.products.get("p-a").category_source'),'manual');});
test('invalid category mass edits are rejected before any earlier product is changed',async()=>{const h=createHarness();h.add(automaticProduct(h));await migrate(h);const before=h.run('JSON.stringify([...S.products.values()])');h.ctx.old=h.run('S.products.get("p-a").category');await assert.rejects(h.run("applyChanges('Invalid',[{pid:'p-a',field:'brand',before:'TEST',after:'CHANGED'},{pid:'p-a',field:'category',before:old,after:'Invented category'}])"));assert.equal(h.run('JSON.stringify([...S.products.values()])'),before);});
test('explicit low-confidence supplier mapping is never promoted to a confirmed assignment',()=>{const d=C.classify({supplier_id:'a',supplier_category_raw:'Unknown',name:'Mystery'},{mappings:[{supplier_id:'a',supplier_category_raw:'Unknown',canonical_category_id:'armor_plates',confidence:0,confirmed:true}]});assert.equal(d.canonical_category_id,null);assert.equal(d.category_status,'NEEDS_REVIEW');});
test('manually entered public attributes take priority over inferred values',async()=>{const h=createHarness();const p=automaticProduct(h,{name:'Куртка чоловіча',srcCat:'Куртки',attrs:{gender:'unisex'}});h.add(p);await migrate(h);assert.equal(h.run('S.products.get("p-a").canonical_attributes.gender'),'male');assert.equal(h.run('buildFeed().feed.products[0].attributes.gender'),'unisex');});
test('supported shop confirmation marks only the exact saved canonical product as synced',async()=>{const h=createHarness();h.add(automaticProduct(h));await migrate(h);h.run("siteReady=()=>true;pimKitPayload=()=>null;siteFetch=async(path,opt)=>{if(path==='/pim/status')return {capabilities:{canonical_category_version:1}};const b=JSON.parse(opt.body);return {ok:true,category_catalog_hash:b.category_catalog_hash,results:b.products.map(p=>({id:p.id,status:'updated',canonical_category_id:p.canonical_category_id})),hidden:0};}");assert.ok(await h.run("sitePublish('full',{silent:true})"));assert.equal(h.run('S.products.get("p-a").syncStatus'),'synced');const hashes=await h.run("Store.get('site/hashes')");assert.ok(hashes['p-a']);});
test('a scoped winter mapping cannot classify winter pants as winter jackets',()=>{const options={mappings:[{supplier_id:'a',supplier_category_raw:'Зимние',supplier_category_path_raw:'Одежда / Куртки / Зимние',canonical_category_id:'clothing_jackets',confidence:1,confirmed:true}]};assert.equal(C.classify({supplier_id:'a',supplier_category_raw:'Зимние',supplier_category_path_raw:'Одежда / Штани / Зимние',name:'Штани зимові'},options).canonical_category_id,'clothing_pants');assert.equal(C.classify({supplier_id:'a',supplier_category_raw:'Зимние',supplier_category_path_raw:'Одежда / Куртки / Зимние',supplier_subcategory_raw:'Зимние',name:'ABC'},options).canonical_category_id,'clothing_jackets');});
test('source groups distinguish the same leaf under different supplier paths',async()=>{const h=createHarness();for(let i=0;i<2;i++){const p=automaticProduct(h,{id:'p-'+i,name:i?'Штани':'Куртка',srcCat:'Зимние',supplier_category_path_raw:i?'Одежда / Штани / Зимние':'Одежда / Куртки / Зимние'});p.variants[0].sku='RUB-'+i;p.variants[0].offers['supplier-a'].s='feed-'+i;h.add(p);}await migrate(h);assert.equal(h.run('categoryNewSupplierGroups().length'),2);await h.run("categoryBulk('supplier-a','Зимние','clothing_jackets',{path:'Одежда / Куртки / Зимние'})");assert.equal(h.run('S.products.get("p-1").canonical_category_id'),'clothing_pants');assert.equal(h.run('S.cfg.supplier_category_mapping[0].supplier_category_path_raw'),'Одежда / Куртки / Зимние');});
test('explicit new canonical pricing rules work without migrating legacy price scopes',async()=>{const h=createHarness();h.add(automaticProduct(h));await migrate(h);h.run("S.cfg.rules=[{scope:'category',value:S.products.get('p-a').pricing_category_path,markup:40,priority:5}]");assert.equal(h.run('ruleMarkup(S.products.get("p-a"),"supplier-a",S.cfg)'),40);h.run("S.cfg.rules.push({scope:'category',value:canonicalPath('bags_backpacks'),canonical_category_id:'bags_backpacks',markup:80,priority:10})");assert.equal(h.run('ruleMarkup(S.products.get("p-a"),"supplier-a",S.cfg)'),80);assert.equal(h.run('S.cfg.rules[0].canonical_category_id'),undefined);});
test('an empty IFAK name or description cannot become a complete medical kit',()=>{assert.equal(C.classify({name:'Аптечка порожня IFAK'}).canonical_category_id,'pouches_medical');const d=C.classify({name:'Аптечка IFAK',description:'Постачається без наповнення.'});assert.equal(d.canonical_category_id,null);assert.equal(d.category_status,'CONFLICT_REVIEW');});
test('canonical kit roles keep drone-backpack exclusions and owner-specific role restrictions',()=>{const h=createHarness();h.run('S.cfg.category_engine={version:1,migration_validated:true};');h.ctx.p=h.product({name:'Рюкзак для дрона',canonical_category_id:'bags_backpacks'});assert.equal(h.run('storeRole(p)'),'');h.ctx.p.name='Рюкзак Test';h.ctx.p.pricing_category_path='Рюкзаки / Інші';h.run("S.cfg.kitRoleCategories={backpack:['Лише штурмові моделі']}");assert.equal(h.run('storeRole(p)'),'');h.run("S.cfg.kitRoleCategories={backpack:['bags_backpacks']}");assert.equal(h.run('storeRole(p)'),'backpack');});
const semanticCases=[
 ['Костюм (Кітель+Штани) ММ-14 розмір 44-46 (S)','ВІЙСЬКОВА УНІФОРМА','clothing_suits'],
 ['Комплект (Убакс+Штани) ММ-14 розмір 48 (M)','ВІЙСЬКОВА УНІФОРМА','clothing_suits'],
 ['Польовий костюм (Кітель та штани) для ЗСУ','','clothing_suits'],
 ['Утеплений зимовий костюм (куртка + штани)','','clothing_suits'],
 ['Бойовий комплект (штани та Ubacs)','','clothing_suits'],
 ['Комплект термобілизни ESDY Fleece Thermal Suit','Термобілизна','clothing_thermal'],
 ['Костюм Alpha + термобілизна','','clothing_suits'],
 ['Акумуляторний LED ліхтарик D48 з запальничкою','Тактичні ліхтарі','lighting_tactical'],
 ['Акумуляторний тактичний ліхтар','','lighting_tactical'],
 ['Акумулятор для рації Baofeng','РАДІОСТАНЦІЇ','power_batteries'],
 ['Акумуляторна батарея 5000 mAh з USB-C для радіостанцій','Аксесуари для рацій','power_batteries'],
 ['Антена тактична складна для портативних радіостанцій','Аксесуари для рацій','communications_antennas'],
 ['Зарядний пристрій універсальний для рацій','Аксесуари для рацій','communications_accessories'],
 ['Термостійкі рукавиці','Перчатки та рукавиці','clothing_gloves'],
 ['Балістичний захист 1 класу для поясу РПС','Бронепакети (1 клас захисту)','armor_soft'],
 ['Балістичний захист для плитоноски камербанд 1 шт','Бронепакети','armor_soft'],
 ['Балістичний захист для сумки під захист паху','Бронепакети','armor_soft'],
 ['Балістичний пакет (Напашник)','Балістичний захист','armor_soft'],
 ['Підсумок медичний з панеллю швидкого скидання','Підсумок-аптечки','pouches_medical'],
 ['Підсумок під аптечку швидкоскид','','pouches_medical'],
 ['Підсумок аптечка з швидким скиданням','','pouches_medical'],
 ['Підсумок медичний з турнікетом','','pouches_medical'],
 ['Підсумок тактичний напашний швидкоскидний','','pouches_dangler'],
 ['Підсумок скидання магазинів','','pouches_dump'],
 ['Підсумок під турнікет','Підсумок-аптечки','pouches_tourniquet'],
 ['Сумка - органайзер для зброї','Рюкзаки, сумки, баули','bags_organizers'],
 ['Штурмовий рюкзак','Рюкзаки, сумки','bags_assault_backpacks'],
 ['Гідратор 3 л','Рюкзаки, сумки','bags_hydration'],
 ['Рюкзак з MOLLE','Штурмові рюкзаки','bags_assault_backpacks'],
 ['Каремат-сидушка для сидіння','Каремати, сидушки','field_seats'],
 ["П'ятиточка - сидушка", "Каремати та п'ятиточки",'field_seats'],
 ['Захисні наколінники та налокітники','Наколінники та налокітники','protection_kits'],
 ['Комплект чорних наколінників та налокітників','Комплект наколінників і налокітників','protection_kits'],
 ['Ремінно-плечова система (РПС)','Ремінно-поясна система (РПС)','load_bearing_rps'],
 ['Плечові лямки до РПС','Ремінно-поясна система (РПС)','load_bearing_harness'],
 ['Футляр для навушників','Підсумки під навушники','pouches_other'],
 ['Екшн-камера на шолом','Екшн-камери','electronics_action_cameras'],
 ['Ножиці тактичні медичні','НОЖІ ТА МУЛЬТИТУЛИ','medical_scissors'],
 ['Шестигранний ключ','НОЖІ ТА МУЛЬТИТУЛИ','tools_other'],
 ['Нiж складний Alpha','НОЖІ ТА МУЛЬТИТУЛИ','tools_knives'],
 ['Точилка для ножів','НОЖІ ТА МУЛЬТИТУЛИ','tools_accessories'],
 ['Компактний маркер для турнікету','МЕДИЧНІ ТУРНІКЕТИ ТА БАНДАЖІ','medical_other'],
 ['Панель під три магазини АК','Підсумки для магазинів','pouches_panels'],
 ['Комплект адаптерів для монокулярів','Кріплення для ПНБ','electronics_mounts'],
 ['Нейтралізатор запаху для ніг та взуття','Засоби особистої гігієни','field_hygiene'],
 ['Термоковдра Medical Blizzard IFAK','Термоковдри','field_thermal_blankets'],
 ['Штани тактичні без наколінників','Військові штани','clothing_pants'],
 ['Бронежилет Modular + балістичний пакет','Бронежилети','armor_vests'],
];
for(const [name,raw,id] of semanticCases)test('whole item and source context: '+name,()=>{const d=C.classify({name,supplier_category_raw:raw});assert.equal(d.canonical_category_id,id,JSON.stringify(d));assert.equal(d.category_status,'CONFIRMED');});
for(const [name,raw] of [
 ['Бронежилет Phantom. Плитоноска з підсумками','Тактичні комплекти'],
 ['Балістичний пакет + напашник','Балістичний захист'],
 ['Рюкзак-сумка для дрона','Рюкзаки, сумки'],
 ['Костюм + ліхтар',''],
 ['Підсумок для аптечки','Рюкзаки'],
 ['Балістичний пакет 2 класу','Бронеплити'],
 ['Комплект шолом + навушники','Комплекти шоломів'],
 ['Налокітники','Комплект наколінників і налокітників']
])test('genuine ambiguity is retained: '+name,()=>{const d=C.classify({name,supplier_category_raw:raw});assert.equal(d.canonical_category_id,null,JSON.stringify(d));assert.equal(d.category_status,'CONFLICT_REVIEW');});
for(const [name,id] of [['Акумулятор 18650','power_batteries'],['Батарейка AA','power_batteries'],['Термос 1 л','field_thermos'],['Підсумок під магазини','pouches_magazine'],['Куртка для костюма','clothing_jackets'],['Мультитул 16 в 1','tools_multitools'],['Каремат туристичний','field_mats'],['Рюкзак з аптечкою','bags_backpacks']])test('counterexample retains the actual item: '+name,()=>assert.equal(C.classify({name}).canonical_category_id,id));
test('rule upgrades keep schema compatibility and manual priority for semantically corrected items',()=>{assert.equal(C.VERSION,1);assert.equal(C.RULESET_VERSION,3);const d=C.classify({name:'Костюм (Кітель+Штани)',category_source:'manual',canonical_category_id:'clothing_pants'});assert.equal(d.canonical_category_id,'clothing_pants');});
test('one clothing assembly rule covers all sizes and subsequent classifications without learning a mixed supplier mapping',()=>{for(const size of ['S','M','L','XL','XXL','44-46','48','50 long']){const input={supplier_id:'same-supplier',supplier_category_raw:'ВІЙСЬКОВА УНІФОРМА',name:'Костюм (Кітель + Штани) розмір '+size};assert.deepEqual(C.classify(input),C.classify(input));assert.equal(C.classify(input).canonical_category_id,'clothing_suits');}assert.equal(C.classify({supplier_category_raw:'ВІЙСЬКОВА УНІФОРМА',name:'Штани окремо'}).canonical_category_id,'clothing_pants');});
test('an explicit product type resolves an ambiguous name with compatible supplier context',()=>{const d=C.classify({name:'Бронежилет Phantom. Плитоноска Alpha',supplier_category_raw:'Тактичні комплекти',attributes:{'Тип виробу':'Плитоноска'}});assert.equal(d.canonical_category_id,'armor_plate_carriers');assert.equal(d.category_rule_id,'explicit-type-resolves-name');});
test('only a labeled type in a description can resolve ambiguous armor naming',()=>{assert.equal(C.classify({name:'Бронежилет. Плитоноска',description:'<p>Тип виробу: плитоноска</p><p>Можна встановити бронеплити.</p>'}).canonical_category_id,'armor_plate_carriers');assert.equal(C.classify({name:'Бронежилет. Плитоноска',description:'Плитоноска виготовлена з Cordura. Бронежилет з підсумками.'}).category_status,'CONFLICT_REVIEW');});
test('conflicting type specifications and explicit contradictory source categories still require review',()=>{for(const input of [{attributes:{Тип:'Плитоноска','Тип виробу':'Бронежилет'}},{supplier_category_raw:'Бронежилети',attributes:{Тип:'Плитоноска'}}]){const d=C.classify({name:'Бронежилет. Плитоноска',...input});assert.equal(d.category_status,'CONFLICT_REVIEW');}});
test('accessory words inside a mixed helmet kit cannot turn the whole kit into a cover or headphone case',()=>{for(const prefix of ['Комплект','Комлпект']){const d=C.classify({name:prefix+' шолом FAST + навушники + кавер та кріплення'});assert.equal(d.canonical_category_id,null);assert.equal(d.category_status,'CONFLICT_REVIEW');assert.ok(d.candidates.includes('helmets_ballistic'));assert.ok(d.candidates.includes('communications_headsets'));}});
test('winter hat and buff kit is not silently reduced to a single included garment',()=>{assert.equal(C.classify({name:'Теплий комплект шапка + баф',supplier_category_raw:'Шапки'}).category_status,'CONFLICT_REVIEW');});
test('typed supplier rules only affect the named whole-item type and never target words',()=>{const options={mappings:[{supplier_id:'a',supplier_category_raw:'Рюкзаки, сумки, баули',canonical_category_id:'bags_assault_backpacks',semantic_type_id:'bags_backpacks',confirmed:true}]};assert.equal(C.classify({supplier_id:'a',supplier_category_raw:'Рюкзаки, сумки, баули',name:'Рюкзак Test'},options).canonical_category_id,'bags_assault_backpacks');assert.equal(C.classify({supplier_id:'a',supplier_category_raw:'Рюкзаки, сумки, баули',name:'Баул Test'},options).canonical_category_id,'bags_duffels');assert.equal(C.classify({supplier_id:'b',supplier_category_raw:'Рюкзаки, сумки, баули',name:'Рюкзак Test'},options).canonical_category_id,'bags_backpacks');assert.equal(C.classify({supplier_id:'a',supplier_category_raw:'Рюкзаки, сумки, баули',name:'Сумка для рюкзака'},options).canonical_category_id,'bags_tactical');});
test('specific supplier type rule has priority over a general mapping and invalid type IDs never execute',()=>{const input={supplier_id:'a',supplier_category_raw:'Mix',name:'Рюкзак Test'},base={supplier_id:'a',supplier_category_raw:'Mix',canonical_category_id:'bags_tactical',confirmed:true};assert.equal(C.classify(input,{mappings:[base,{...base,canonical_category_id:'bags_assault_backpacks',semantic_type_id:'bags_backpacks'}]}).canonical_category_id,'bags_assault_backpacks');assert.equal(C.classify(input,{mappings:[{...base,semantic_type_id:'bags_assault'}]}).canonical_category_id,'bags_backpacks');});
function previewFixture(){const h=createHarness();for(const [i,name] of ['Рюкзак Test','Баул Test'].entries()){const p=automaticProduct(h,{id:'preview-'+i,name,srcCat:'Рюкзаки, сумки, баули'});p.variants[0].sku='RUB-PREVIEW-'+i;p.variants[0].offers['supplier-a'].s='preview-feed-'+i;h.add(p);}return h;}
test('supplier-rule preview is non-mutating, shows differing types and blocks a whole mixed section',()=>{const h=previewFixture(),before=h.run('JSON.stringify({...fullStateData(),at:0})'),p=h.run("categoryRulePreview('supplier-a','Рюкзаки, сумки, баули','bags_backpacks')");assert.equal(p.affected,2);assert.equal(p.blocked,true);assert.equal(p.types.length,2);assert.equal(h.run('JSON.stringify({...fullStateData(),at:0})'),before);assert.throws(()=>h.run("categoryRecordMapping('supplier-a','Рюкзаки, сумки, баули','bags_backpacks')"),/різні типи/);assert.equal(h.run('S.cfg.supplier_category_mapping?.length||0'),0);});
test('typed preview narrows a mixed section to matching titles',()=>{const h=previewFixture(),p=h.run("categoryRulePreview('supplier-a','Рюкзаки, сумки, баули','bags_backpacks',{type:'bags_backpacks'})");assert.equal(p.affected,1);assert.equal(p.blocked,false);assert.equal(p.details[0].name,'Рюкзак Test');});
test('rule approval rejects a stale preview before it can write or stage a mapping',async()=>{const h=previewFixture();h.run("CATEGORY_UI.rulePreview=categoryRulePreview('supplier-a','Рюкзаки, сумки, баули','bags_backpacks',{type:'bags_backpacks'});S.products.get('preview-0').name='Рюкзак Changed';bumpData()");await assert.rejects(h.run('categoryApplyRulePreview()'),/змінилися/);assert.equal(h.run('S.cfg.supplier_category_mapping?.length||0'),0);});
test('typed mapping application protects manual decisions and leaves unrelated types unchanged',async()=>{const h=previewFixture();await migrate(h);await h.run("categoryConfirm('preview-0','bags_backpacks')");h.run("CATEGORY_UI.rulePreview=categoryRulePreview('supplier-a','Рюкзаки, сумки, баули','bags_assault_backpacks',{type:'bags_backpacks',bulk:true})");assert.equal(h.run('CATEGORY_UI.rulePreview.protectedManual'),1);await h.run('categoryApplyRulePreview()');assert.equal(h.run("S.products.get('preview-0').canonical_category_id"),'bags_backpacks');assert.equal(h.run("S.products.get('preview-1').canonical_category_id"),'bags_duffels');assert.equal(h.run('S.cfg.supplier_category_mapping[0].semantic_type_id'),'bags_backpacks');});
test('confidence presentation and report never claim a measured accuracy',()=>{const h=previewFixture();assert.equal(h.run('categoryScoreLabel(.96)'),'Сильне правило');h.run("CATEGORY_UI.filter='confirmed'");const html=h.run('vCategorization()');assert.ok(html.includes('Чому обрано категорію'));assert.ok(!/96%|97%|99%/.test(html));assert.equal(h.run('categoryReport().automatic_rules.score_is_accuracy'),false);});
test('a typed mapping does not mark the whole mixed supplier section as already mapped',async()=>{const h=previewFixture();await migrate(h);h.run("categoryRecordMapping('supplier-a','Рюкзаки, сумки, баули','bags_backpacks',{type:'bags_backpacks'})");const groups=h.run('categoryNewSupplierGroups()');assert.ok(groups.some(g=>g.raw==='Рюкзаки, сумки, баули'&&g.products.includes('preview-1')));});
test('identical variant source contexts are parsed once without hiding a different supplier conflict',()=>{const h=createHarness(),p=automaticProduct(h);p.category_sources=Array.from({length:20},(_,i)=>({supplier_id:'supplier-a',supplier_sku:'same-context-'+i,supplier_category_raw:'Рюкзаки',supplier_category_path_raw:'Рюкзаки'}));h.add(p);h.run('var parseCalls=0;var realClassify=RubizhCategories.classify;RubizhCategories.classify=(...args)=>{parseCalls++;return realClassify(...args);};');assert.equal(h.run("categoryDecisionForProduct(S.products.get('p-a')).canonical_category_id"),'bags_backpacks');assert.equal(h.run('parseCalls'),1);h.run("S.products.get('p-a').category_sources.push({supplier_id:'supplier-b',supplier_category_raw:'Куртки'});");assert.equal(h.run("categoryDecisionForProduct(S.products.get('p-a')).category_status"),'CONFLICT_REVIEW');});
test('deprecated canonical IDs cannot be selected by an alias, mapping or new manual classification',()=>{const options={categories:[{id:'bags_backpacks',deprecated:true}],mappings:[{supplier_id:'a',supplier_category_raw:'x',canonical_category_id:'bags_backpacks'}]};assert.equal(C.classify({name:'Рюкзак',supplier_id:'a',supplier_category_raw:'x'},options).canonical_category_id,null);assert.equal(C.classify({name:'Рюкзак',category_source:'manual',canonical_category_id:'bags_backpacks'},options).canonical_category_id,null);assert.equal(C.leaf('bags_backpacks',options.categories),false);assert.equal(C.defaults.length,143);});
test('a mixed bags section cannot turn a generic named bag into a duffel',()=>{assert.equal(C.classify({name:'Сумка 130 л Test',supplier_category_raw:'Сумки та баули'}).canonical_category_id,'bags_tactical');});
test('a mixed supplier section with only one recognized keyword still cannot classify an unknown item',()=>{const d=C.classify({name:'XYZ Test',supplier_category_raw:'Термоси та пляшки'});assert.equal(d.canonical_category_id,null);assert.equal(d.category_status,'NEEDS_REVIEW');});
test('a seat mat name refines a broad camping mat section without needing manual work',()=>{assert.equal(C.classify({name:'Каремат для сидіння 30x40 см',supplier_category_raw:'Каремати'}).canonical_category_id,'field_seats');});
for(const [name,raw,id] of [['Бушлат зимовий','Формений одяг, комплекти, костюми','clothing_jackets'],['Анорак Alpha','Куртки літні та тактичні','clothing_jackets'],['Комплект зимовий Alpha','Зимові та утеплені костюми і комплекти','clothing_suits'],['Адаптер GoPro на dovetail','Кріплення для ПНБ та тепловізорів','electronics_mounts'],['Денна кришка для PVS-14','Кріплення для ПНБ та тепловізорів','electronics_accessories'],['Керамічні плити 6 класу NIJ IV','Плитоноски та пластини','armor_plates']])test('source-root evidence supports an explicit compatible item: '+name,()=>assert.equal(C.classify({name,supplier_category_raw:raw}).canonical_category_id,id));
test('generic kits and caps without an unambiguous supplier root remain unclassified',()=>{for(const name of ['Комплект Alpha','Денна кришка','Адаптер GoPro'])assert.equal(C.classify({name}).canonical_category_id,null);});
test('multiple adjectives before a clothing bundle cannot hide its independent components',()=>{const d=C.classify({name:'Зимовий флісовий комплект Test. Шапка + баф. Олива.',supplier_category_raw:'Шапки'});assert.equal(d.category_status,'CONFLICT_REVIEW');assert.equal(d.canonical_category_id,null);});
test('size parentheses in a named mixed garment kit do not hide the second garment',()=>{const d=C.classify({name:'Зимовий флісовий комплект Test. Шапка (розмір)+баф. Олива.',supplier_category_raw:'Шапки'});assert.equal(d.canonical_category_id,null);assert.equal(d.category_status,'CONFLICT_REVIEW');});
test('a supplier list of intended targets does not make an unambiguous net section into a mixed product group',()=>assert.equal(C.classify({name:'Сітка 11x105 м',supplier_category_raw:'Антидронові сітки для доріг і техніки'}).canonical_category_id,'camouflage_antidrone'));
test('rifle case keeps its own type under a mixed bag section',()=>assert.equal(C.classify({name:'Кейс під гвинтівку 1 м',supplier_category_raw:'Сумки та баули'}).canonical_category_id,'weapon_cases'));
