'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),Ajv=require('ajv');
const {createHarness}=require('./isolated-harness.cjs');
const schema=require('../contracts/category-size-export.schema.json'),validate=new Ajv({strict:false}).compile(schema);
function setup(){const h=createHarness({runtime:true});h.run('classificationEnable();S.cfg.category_engine={version:RubizhCategories.VERSION,migration_validated:true};');const p=h.product({canonical_category_id:'clothing_pants',category_locked:true,name:'Штани Test'});p.variants[0].size='';Object.assign(p.variants[0].offers['supplier-a'],{source_name:'Штани Test',source_description:'Розміри 42–60. Матеріал: нейлон.',size_raw:'42–60'});h.add(p);h.run('classificationApplyProduct(S.products.get("p-a"));bumpData()');return h;}
test('normalized authenticated and public exports validate against JSON schema',()=>{const h=setup();for(const publicOnly of [false,true]){const payload=JSON.parse(JSON.stringify(h.run('classificationExport(S.products.get("p-a"),{publicOnly:'+publicOnly+'})')));assert.equal(validate(payload),true,JSON.stringify(validate.errors));assert.equal(payload.variants.length,1);assert.equal(payload.size_options.length,10);assert.equal(payload.size_catalogs[0].scope,'MODEL');assert.equal(payload.size_options[0].color_id,null);if(publicOnly)assert.ok(!JSON.stringify(payload).includes('supplier_bindings'));else assert.equal(payload.variants[0].supplier_bindings[0].supplier_sku,'feed-a');}});
test('schema rejects guessed SKU, guessed stock and tradable unconfirmed size options',()=>{const h=setup(),payload=JSON.parse(JSON.stringify(h.run('classificationExport(S.products.get("p-a"))')));for(const [key,value] of [['variant_sku','FAKE-42'],['stock',3],['payment_allowed',true],['availability','IN_STOCK']]){const changed=structuredClone(payload);changed.size_options[0][key]=value;assert.equal(validate(changed),false,key);}const changed=structuredClone(payload);changed.variants[0].stock=3;assert.equal(validate(changed),false);});
test('actual buildFeed exposes normalized options and colors without private source or invented inventory',()=>{const h=setup(),feed=JSON.parse(JSON.stringify(h.run('buildFeed()')));assert.equal(feed.review_only,true);assert.equal(feed.categories.length,143);assert.equal(feed.products.length,1);assert.equal(validate(feed.products[0]),true,JSON.stringify(validate.errors));assert.ok(!JSON.stringify(feed).includes('source_row_raw'));assert.ok(!JSON.stringify(feed).includes('source_description'));assert.ok(!JSON.stringify(feed).includes('supplier_cost'));assert.ok(!JSON.stringify(feed).includes('supplier_bindings'));assert.equal(feed.products[0].variants[0].availability,'SIZE_CONFIRMATION_REQUIRED');assert.equal(feed.products[0].variants[0].payment_allowed,false);});
test('zero usable photos suppresses export without archiving or changing publication in review copy',()=>{const h=setup();h.run('S.products.get("p-a").photos=[];S.products.get("p-a").variants[0].offers["supplier-a"].photos=[];bumpData();');assert.equal(h.run('buildFeed().products.length'),0);assert.equal(h.run('S.products.get("p-a").pub'),true);assert.equal(h.run('S.products.get("p-a").archived'),false);});
test('supplier facts restore missing description safely, without archiving or invented characteristics',()=>{const h=setup();h.run('const p=S.products.get("p-a");p.desc="";p.source_description="";for(const v of p.variants)for(const o of Object.values(v.offers)){o.source_description="";o.source_attributes={Матеріал:"Нейлон"};}p.fieldMeta.desc={source:"supplier",supplierValue:""};bumpData();');assert.match(h.run('classificationDescription(S.products.get("p-a"))'),/Нейлон/);assert.equal(h.run('S.products.get("p-a").archived'),false);assert.equal(h.run('buildFeed().products.length'),1);});
test('two colors retain different galleries and all original SKU bindings',()=>{const h=setup();h.run('const p=S.products.get("p-a");const v=structuredClone(p.variants[0]);v.sku="RUB-00002";v.color="Чорний";v.offers["supplier-a"].s="black-a";v.offers["supplier-a"].photos=["https://example.test/black.jpg"];p.variants.push(v);S.cfg.model_colors_version=1;bumpData();');const payload=h.run('classificationExport(S.products.get("p-a"))');assert.equal(payload.colors.length,2);assert.equal(payload.variants.length,2);assert.notDeepEqual(payload.variants[0].photos,payload.variants[1].photos);assert.ok(payload.size_options.every(o=>o.color_id===null));});
test('simple payload retains real unconfirmed SKU and never labels it preorder',()=>{const h=setup(),payload=h.run('simpleProductPayload(simpleAssess(S.products.get("p-a")))');assert.equal(payload.variants.length,1);assert.equal(payload.availability,'SIZE_CONFIRMATION_REQUIRED');assert.equal(payload.variants[0].stock,null);assert.equal(payload.variants[0].payment_allowed,false);});
