'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createHarness}=require('./isolated-harness.cjs');
function harness(){const h=createHarness({runtime:true});h.run('render=()=>{};classificationEnable();S.cfg.category_engine={version:RubizhCategories.VERSION,migration_validated:true};');return h;}
function clothing(h,over={}){return h.product({name:'Штани Test',canonical_category_id:'clothing_pants',category:'Одяг / Штани',category_locked:false,catSource:'auto_name',category_source:'automatic',...over});}
async function preview(h,rows,map){h.ctx.rows=rows;h.ctx.map=map;h.run('S.imp={sup:"supplier-a",file:"fixture.csv",rows,hdr:0,map,zero:false};');await h.run('doImport()');assert.ok(h.run('S.imp.preview'),h.alerts.join('\n'));}
test('review artifact rejects all networking and publication before a request',async()=>{const h=harness();await assert.rejects(h.run('sitePublish()'),/REVIEW_ONLY/);await assert.rejects(h.run('fetch("https://rubizh.shop/pim/sync",{method:"POST"})'),/REVIEW_ONLY/);await assert.rejects(h.run('simpleApplyPolicy()'),/REVIEW_ONLY/);assert.equal(h.run('sbCfg()'),null);assert.match(h.run('Store.fallbackPrefix'),/review/);});
test('143 categories preserve all 134 accepted canonical entries byte-for-byte',()=>{const h=harness(),old=require('../../reviews/category-final-dry-run-2026-10-08/taxonomy-diff.json');const before=require('../../reviews/category-gaps-dry-run-2026-10-08/taxonomy-before.json');const categories=JSON.parse(JSON.stringify(h.run('S.cfg.canonical_categories')));assert.equal(categories.length,143);for(const c of before.categories||before)assert.deepEqual(categories.find(n=>n.id===c.id),c);assert.ok(!categories.some(c=>c.id==='footwear_loafers'));});
test('explicit size column outranks SKU inference and model description; import does not publish',async()=>{const h=harness();const p=clothing(h,{pub:false});p.variants[0].offers['supplier-a'].s='pants-42';p.variants[0].size='';h.add(p);await preview(h,[['SKU','Name','Size','Price','Stock','Description'],['pants-42','Штани Test','48',1000,3,'Розміри 42–60. Штани з міцної тканини.']],{sku:0,name:1,size:2,cost:3,stock:4,desc:5});const v=h.run('S.products.get("p-a").variants[0]');assert.equal(v.size,'48');assert.equal(v.size_status,'EXACT_SIZE');assert.equal(h.run('S.products.get("p-a").pub'),false);assert.equal(h.run('S.products.get("p-a").variants.length'),1);});
test('range creates allowed options and zero synthetic SKUs/stock; preview cancellation restores all data',async()=>{const h=harness();const p=clothing(h);p.variants[0].offers['supplier-a'].s='range-a';p.variants[0].size='';h.add(p);const before=JSON.stringify(h.run('[...S.products.values()]'));await preview(h,[['SKU','Name','Size','Price','Stock'],['range-a','Штани Test','42–60',1000,0]],{sku:0,name:1,size:2,cost:3,stock:4});assert.equal(h.run('S.products.get("p-a").variants.length'),1);const options=h.run('classificationOptions(S.products.get("p-a"))');assert.equal(options.length,10);for(const o of options){assert.equal(o.variant_sku,null);assert.equal(o.stock,null);assert.equal(o.payment_allowed,false);}h.run('cancelImport(true)');assert.equal(JSON.stringify(h.run('[...S.products.values()]')),before);});
test('manual category, size and allowed-size locks survive conflicting supplier import',async()=>{const h=harness();const p=clothing(h,{category_locked:true,manual_locks:{category:true,size:true,allowed_sizes:true},size_catalogs:[{catalog_id:'manual',scope:'MODEL',color_id:null,size_system:'clothing_numeric',allowed_sizes:['50']}]});p.variants[0].size='50';p.variants[0].manualFields={size:true};p.variants[0].offers['supplier-a'].s='lock-a';h.add(p);await preview(h,[['SKU','Name','Size','Price','Stock'],['lock-a','Годинник Test','48',1000,0]],{sku:0,name:1,size:2,cost:3,stock:4});assert.equal(h.run('S.products.get("p-a").canonical_category_id'),'clothing_pants');assert.equal(h.run('S.products.get("p-a").variants[0].size'),'50');assert.equal(h.run('S.products.get("p-a").size_catalogs[0].catalog_id'),'manual');});
test('LIKELY and AMBIGUOUS preserve confirmed category without granting watch by alias',()=>{const h=harness(),p=clothing(h,{name:'Годинник Test',desc:'Годинник',source_description:'Годинник',last_confirmed_category_id:'clothing_pants'});p.variants[0].offers['supplier-a'].source_name='Годинник Test';p.variants[0].offers['supplier-a'].source_description='Годинник';h.add(p);h.run('classificationApplyProduct(S.products.get("p-a"))');assert.notEqual(h.run('S.products.get("p-a").category_confidence_tier'),'SAFE_AUTO');assert.equal(h.run('S.products.get("p-a").canonical_category_id'),'clothing_pants');});
test('new approved watch category requires whole-item title plus independent functional evidence',()=>{const h=harness(),p=clothing(h,{name:'Годинник Test',desc:'Кварцовий механізм, циферблат та будильник.',category_source:'automatic'});Object.assign(p.variants[0].offers['supplier-a'],{source_name:'Годинник Test',source_description:p.desc});h.add(p);h.run('classificationApplyProduct(S.products.get("p-a"))');assert.equal(h.run('S.products.get("p-a").canonical_category_id'),'field_watches');assert.equal(h.run('S.products.get("p-a").variants[0].size_status'),'NO_SIZE_REQUIRED');assert.equal(h.run('S.products.get("p-a").variants[0].size'), '');});
test('zero stock is OUT_OF_STOCK; stale stock remains confirmed; missing size never PREORDER',()=>{const h=harness(),p=clothing(h);p.variants[0].size='48';p.variants[0].offers['supplier-a'].native_size='48';p.variants[0].offers['supplier-a'].stock=0;h.add(p);h.run('classificationApplyProduct(S.products.get("p-a"))');assert.equal(h.run('classificationAvailability(S.products.get("p-a"),S.products.get("p-a").variants[0]).availability'),'OUT_OF_STOCK');h.run('S.products.get("p-a").variants[0].offers["supplier-a"].at=Date.now()-37*3600000;bumpData()');assert.equal(h.run('classificationAvailability(S.products.get("p-a"),S.products.get("p-a").variants[0]).availability'),'OUT_OF_STOCK');h.run('S.products.get("p-a").variants[0].size_status="SIZE_CONFIRMATION_REQUIRED"');assert.equal(h.run('classificationAvailability(S.products.get("p-a"),S.products.get("p-a").variants[0]).availability'),'SIZE_CONFIRMATION_REQUIRED');});
test('two identical classifications do not duplicate catalogs/exceptions/history or alter SKU identity',()=>{const h=harness(),p=clothing(h);p.variants[0].size='';Object.assign(p.variants[0].offers['supplier-a'],{native_size:'42–60',size_raw:'42–60'});h.add(p);h.run('classificationApplyProduct(S.products.get("p-a"))');const first=JSON.stringify(h.run('[S.products.get("p-a").size_catalogs,S.products.get("p-a").classification_exceptions,S.products.get("p-a").category_history]'));h.run('classificationApplyProduct(S.products.get("p-a"))');assert.equal(JSON.stringify(h.run('[S.products.get("p-a").size_catalogs,S.products.get("p-a").classification_exceptions,S.products.get("p-a").category_history]')),first);assert.equal(h.run('S.products.get("p-a").variants.length'),1);});
test('changed raw source invalidates preview and aborts apply',async()=>{const h=harness();h.add(clothing(h));await preview(h,[['SKU','Name','Price'],['feed-a','Штани Test',1000]],{sku:0,name:1,cost:2});h.run('S.imp.rows[1][2]=999');await assert.rejects(h.run('applyImport()'),/STALE_PREVIEW/);assert.ok(h.run('S.snap'));h.run('cancelImport(true)');});
test('runtime apply persists new fields; second identical preview/apply is idempotent',async()=>{const h=harness(),p=clothing(h);p.variants[0].size='';h.add(p);await h.run('Store.init()');assert.equal(await h.run('markAllDirty();persist()'),true);const rows=[['SKU','Name','Size','Price','Stock'],['feed-a','Штани Test','42–60',1000,0]],map={sku:0,name:1,size:2,cost:3,stock:4};await preview(h,rows,map);assert.equal(await h.run('applyImport()'),true,h.alerts.join('\n'));const snapshot=JSON.stringify(h.run('[...S.products.values()].map(p=>[p.variants.map(v=>v.sku),p.size_catalogs,p.classification_exceptions])'));await preview(h,rows,map);assert.equal(await h.run('applyImport()'),true,h.alerts.join('\n'));assert.equal(JSON.stringify(h.run('[...S.products.values()].map(p=>[p.variants.map(v=>v.sku),p.size_catalogs,p.classification_exceptions])')),snapshot);});
test('failed persistent verification rolls back classifications and stock',async()=>{const h=harness();h.add(clothing(h));await h.run('Store.init()');assert.equal(await h.run('markAllDirty();persist()'),true);const before=JSON.stringify(h.run('[...S.products.values()]'));await preview(h,[['SKU','Name','Size','Price'],['feed-a','Штани Test','48',1000]],{sku:0,name:1,size:2,cost:3});h.run('verifyAppliedImport=async()=>({ok:false,reason:"injected verify failure"});');assert.notEqual(await h.run('applyImport()'),true);assert.equal(JSON.stringify(h.run('[...S.products.values()]')),before);assert.ok(h.alerts.some(x=>x.includes('НЕ применён')));});
test('source lists never manufacture colors × sizes on a new supplier row',async()=>{const h=harness();h.run('S.cfg.suppliers[0].auto=true');await preview(h,[['SKU','Name','Size','Color','Price'],['new-range','Штани Test','42–60','Black / Olive',1000]],{sku:0,name:1,size:2,color:3,cost:4});const count=h.run('[...S.products.values()].reduce((n,p)=>n+p.variants.length,0)+S.queue.size');assert.equal(count,1);});
test('a failed save restores the complete pre-import state from the internal backup',async()=>{const h=harness();h.add(clothing(h));await h.run('Store.init()');assert.equal(await h.run('markAllDirty();persist()'),true);const before=JSON.stringify(h.run('[...S.products.values()]'));await preview(h,[['SKU','Name','Size','Price'],['feed-a','Штани Test','48',1000]],{sku:0,name:1,size:2,cost:3});h.run('const originalPersist=persist;let failOnce=true;persist=async()=>{if(failOnce){failOnce=false;return false;}return originalPersist();};');assert.notEqual(await h.run('applyImport()'),true);assert.equal(JSON.stringify(h.run('[...S.products.values()]')),before);});
test('review startup cannot merge SKU, roll back data or automatically change pricing policy',async()=>{const h=harness(),p=clothing(h);p.variants.push({...structuredClone(p.variants[0]),sku:'RUB-00002'});h.add(p);const before=JSON.stringify(h.run('[...S.products.values()]'));assert.equal(h.run('repairDuplicateSupplierLinksSafe().mergedVariants'),0);await h.run('startupIntegrityCheck()');assert.equal(await h.run('ensurePricingPolicy()'),false);assert.equal(JSON.stringify(h.run('[...S.products.values()]')),before);});
test('optimized fingerprints retain published and backup hash compatibility',()=>{const h=harness();for(const [s,expected] of [['','811c9dc501000193'],['РУБІЖ — розміри 42–60','9de412a7d596dbaa'],['abcdefgh'.repeat(200000),'a4ef79c59c2cab93']]){h.ctx.hashInput=s;assert.equal(h.run('fnvHash(hashInput)'),expected);}});
test('approved supplier combined formats work but model ranges remain catalogs',()=>{const h=harness(),p=clothing(h);p.variants[0].size='L/R(48/176)';h.add(p);h.run('classificationApplyProduct(S.products.get("p-a"))');assert.equal(h.run('S.products.get("p-a").variants[0].size_status'),'EXACT_SIZE');assert.equal(h.run('S.products.get("p-a").variants[0].size'),'L/R(48/176)');});
test('explicit supplier universal size is ONE_SIZE without inventing an option or stock',()=>{const h=harness(),p=clothing(h);p.variants[0].size='';p.variants[0].offers['supplier-a'].source_description='Розмір: універсальний. Міцна тканина.';h.add(p);h.run('classificationApplyProduct(S.products.get("p-a"))');assert.equal(h.run('S.products.get("p-a").variants[0].size_status'),'ONE_SIZE');assert.equal(h.run('classificationOptions(S.products.get("p-a")).length'),0);});
test('known categories without a body size do not generate fake size questions or One Size',()=>{const h=harness();for(const category of ['weapon_slings','weapon_magazines','electronics_accessories','armor_accessories','communications_accessories','footwear_care','field_watches']){const p=clothing(h,{canonical_category_id:category,category_locked:true});p.variants[0].size='';h.ctx.p=p;h.run('classificationApplyProduct(p)');assert.equal(p.variants[0].size_status,'NO_SIZE_REQUIRED',category);assert.equal(p.variants[0].size,'',category);assert.equal(p.classification_exceptions.filter(e=>e.kind==='size').length,0,category);}});
test('mapped size column with arbitrary supplier header retains model range',async()=>{const h=harness(),p=clothing(h);p.variants[0].size='';h.add(p);await preview(h,[['SKU','Name','Сетка модели','Price'],['feed-a','Штани Test','42–60',1000]],{sku:0,name:1,size:2,cost:3});assert.equal(h.run('classificationOptions(S.products.get("p-a")).length'),10);assert.equal(h.run('S.products.get("p-a").variants.length'),1);});
test('dedicated structured value wins over a legacy derived native-size value',()=>{const h=harness(),p=clothing(h);p.variants[0].size='42';Object.assign(p.variants[0].offers['supplier-a'],{structured_size:'48',native_size:'42'});h.add(p);h.run('classificationApplyProduct(S.products.get("p-a"))');assert.equal(h.run('S.products.get("p-a").variants[0].size'),'48');});
module.exports={harness,preview};
test('identical replay keeps title-derived size evidence and fingerprints stable',async()=>{
 const h=harness(),p=clothing(h,{name:'Штани Test розмір 48'}),v=p.variants[0];v.size='';delete v.size_raw;delete v.native_size;const o=v.offers['supplier-a'];delete o.native_size;delete o.variant_size;delete o.size_raw;h.add(p);
 const rows=[['SKU','Name','__review_replay'],[o.s,p.name,{product_id:p.id,variant_sku:v.sku,variant_size:'',variant_color:v.color,offer:structuredClone(o)}]];
 await h.run('Store.init()');h.run('markAllDirty()');await h.run('persist()');
 await preview(h,rows,{sku:0,name:1});assert.equal(await h.run('applyImport()'),true);
 const first=JSON.stringify(h.run('S.products.get("p-a")'));assert.equal(h.run('S.products.get("p-a").variants[0].size'),'48');
 await preview(h,rows,{sku:0,name:1});assert.equal(await h.run('applyImport()'),true);
 const current=h.run('S.products.get("p-a")'),original=JSON.parse(first);
 for(const key of ['classification_fingerprint','classification_input_fingerprint','size_catalogs','classification_exceptions'])assert.deepEqual(JSON.parse(JSON.stringify(current[key]??null)),original[key]??null);
 assert.deepEqual(JSON.parse(JSON.stringify(current.variants[0].size_evidence)),original.variants[0].size_evidence);
 h.run('S.products.get("p-a").variants[0].offers["supplier-a"].structured_size="50";classificationApplyProduct(S.products.get("p-a"))');assert.equal(h.run('S.products.get("p-a").variants[0].size'),'50');
});
