'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),{triageConflicts,frame,skuFamily}=require('../lib/conflict-triage-v2.cjs');
function fixture(){const offers=['black','coyote'].map((c,i)=>({offer_id:'offer-'+i,supplier_sku:i?'7043-К':'7043',group_id:'group-'+i,brand:'Earmor',category_id:'hearing',name:'Earmor M20T '+c,color_values:[c],size_values:[],params:[{name:'Тип',value:'Active'},{name:'Вид изделия',value:'Earplugs'}],fields:{}}));const source={products:[{legacy_product_id:'old',source_presence:'BOTH',canonical_category_id:'hearing',protected:{name:'Earmor M20T'}}],variants:offers.map((o,i)=>({legacy_product_id:'old',legacy_sku:'RUB-'+i,size:{raw:'One',normalized:'One'}}))};const doc={feeds:[{supplier_id:'supplier',supplier_key:'synthetic',offers}]};const report={supplier_links:offers.map((o,i)=>({legacy_product_id:'old',legacy_sku:'RUB-'+i,supplier_id:'supplier',offer_id:o.offer_id,status:'CONFIRMED_SUPPLIER_LINK'})),model_groups:offers.map(o=>({model_id:o.group_id,canonical_category_ids:['hearing']})),product_groups:[{legacy_product_id:'old',model_ids:offers.map(o=>o.group_id)}]};return {source,report,doc,offers};}
const run=f=>triageConflicts(f.source,f.report,f.doc);
test('verified primary SKU family plus independent fields qualifies only as offline SAFE_AUTO',()=>{const f=fixture(),before=JSON.stringify(f),r=run(f);assert.equal(r.summary.SAFE_AUTO,1);assert.equal(r.cases[0].automatic_apply,false);assert.equal(r.cases[0].mapping_status,'UNKNOWN');assert.equal(JSON.stringify(f),before);});
test('same title, brand and category without family or technical characteristics never qualifies SAFE_AUTO',()=>{const f=fixture();f.offers[1].supplier_sku='unrelated';for(const o of f.offers)o.params=[];assert.equal(run(f).summary.SAFE_AUTO,0);assert.equal(run(f).cases[0].bucket,'LIKELY');});
test('contradictory season blocks consolidation even with identical titles and SKU family',()=>{const f=fixture();f.offers.forEach((o,i)=>o.params.push({name:'Сезон',value:i?'Summer':'Winter'}));const c=run(f).cases[0];assert.equal(c.bucket,'AMBIGUOUS');assert.ok(c.blocking_evidence.includes('TRAIT_CONTRADICTION:season'));});
test('source or canonical category contradictions override matching family',()=>{const f=fixture();f.report.model_groups[1].canonical_category_ids=['other'];assert.equal(run(f).cases[0].bucket,'AMBIGUOUS');f.report.model_groups[1].canonical_category_ids=['hearing'];f.offers[1].category_id='other';assert.equal(run(f).cases[0].bucket,'AMBIGUOUS');});
test('multiple suppliers never collapse into a confirmed family',()=>{const f=fixture();f.doc.feeds.push({supplier_id:'other',supplier_key:'other',offers:[f.offers[1]]});f.report.supplier_links[1].supplier_id='other';assert.equal(run(f).cases[0].bucket,'AMBIGUOUS');assert.equal(run(f).summary.actual_multiple_supplier_cases,1);});
test('conflicting colors and duplicate color-size SKU both prevent SAFE_AUTO without deleting a variant',()=>{const f=fixture();f.offers[1].color_values=['coyote','olive'];assert.equal(run(f).summary.SAFE_AUTO,0);f.offers[1].color_values=['black'];f.offers[1].name=f.offers[0].name;f.offers[1].supplier_sku='7043-BLK';const c=run(f).cases[0];assert.equal(c.bucket,'LIKELY');assert.equal(c.duplicate_color_size_pairs.length,1);assert.equal(f.source.variants.length,2);});
test('size removal preserves brand, manufacturer model code and model-generation differences',()=>{const a={name:'M-Tac M20T black розмір M',color_values:['black'],size_values:['M']};assert.equal(frame(a),'m tac m20t');assert.notEqual(frame({...a,name:'M-Tac M20T Pro black розмір M'}),frame(a));});
test('SKU stripping requires an explicitly observed variant suffix and cannot erase an arbitrary code',()=>{assert.equal(skuFamily({supplier_sku:'ABC-123',color_values:['black'],size_values:[]}).family,'ABC-123');assert.equal(skuFamily({supplier_sku:'ABC-BLK',color_values:['black'],size_values:[]}).family,'ABC');});
test('substantial exact technical text requires three full matching characteristics and all other guards',()=>{const f=fixture();f.offers.forEach((o,i)=>{o.supplier_sku='independent-'+i;o.name='Earmor tactical active ear protection M20T '+(i?'coyote':'black');o.params.push({name:'Материал',value:'ABS'});o.fields.description=['Technical model-specific construction and usage. '.repeat(20)];});assert.equal(run(f).summary.SAFE_AUTO,1);f.offers[1].fields.description=['Different construction. '.repeat(30)];assert.equal(run(f).summary.SAFE_AUTO,0);});
test('PIM-only conflicts are not miscounted as live shop cards',()=>{const f=fixture();f.source.products[0].source_presence='PIM_ONLY';const r=run(f);assert.equal(r.summary.current_site_cases,0);assert.equal(r.summary.pim_only_cases,1);});
