'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),I=require('../lib/inventory-policy.js'),Ajv=require('ajv'),{createHarness}=require('./isolated-harness.cjs'),{createMockShop}=require('./mock-shop-api.cjs');
const validate=new Ajv({strict:false}).compile(require('../contracts/category-size-export.schema.json'));
const status={id:'test-status-v1',mode:'STATUS',confirmed:true,source_column:'Наличие',status_map:{'есть':'IN_STOCK','нет':'OUT_OF_STOCK'}};
for(const [value,expected] of [['есть','IN_STOCK'],['нет','OUT_OF_STOCK'],['','UNKNOWN'],['unknown','UNKNOWN'],['5','UNKNOWN']])test('STATUS exact token '+value,()=>{const x=I.resolve(status,{rawAvailability:value,stock:5});assert.equal(x.availability_status,expected);assert.equal(x.stock_quantity,null);});
for(const [value,expected,days] of [['+','IN_STOCK',null],['-','OUT_OF_STOCK',null],['!','IN_STOCK',null],['3','PREORDER',3],['0','UNKNOWN',null],['-3','UNKNOWN',null],['3 pcs','UNKNOWN',null]])test('Prom field semantics '+value,()=>{const x=I.resolve(I.defaults.s2akya7xoafn,{rawAvailability:value});assert.equal(x.availability_status,expected);assert.equal(x.delivery_lead_time_days,days);assert.equal(x.stock_quantity,null);assert.equal(x.ready_to_dispatch,value==='!');});
test('Tactical candidate never interprets numeric values until confirmed',()=>{for(const value of ['0','1','1265'])assert.equal(I.resolve(I.defaults.s4p9slmnn0ki,{rawAvailability:value,stock:Number(value)}).availability_status,'UNKNOWN');});
test('QUANTITY preserves only valid actual quantities',()=>{const p={id:'q',mode:'QUANTITY',confirmed:true};for(const [quantity,expected] of [[0,'OUT_OF_STOCK'],[3,'IN_STOCK'],[null,'UNKNOWN'],[-1,'UNKNOWN'],['3','UNKNOWN'],[NaN,'UNKNOWN']])assert.equal(I.resolve(p,{stock:quantity}).availability_status,expected);});
test('quantity column parser does not coerce malformed values or status labels',()=>{for(const v of ['',null,'+',true,'3 pcs','-3','NaN'])assert.equal(I.quantity(v),null);assert.equal(I.quantity('1 265'),1265);assert.equal(I.quantity('3,5'),3.5);});
test('FEED_PRESENCE requires confirmed supplier rule and actual observed row, not mere cached offer',()=>{const p={id:'presence',mode:'FEED_PRESENCE',confirmed:true};assert.equal(I.resolve(p,{feed_presence_confirmed:true}).availability_status,'UNKNOWN');p.feed_presence_confirmed=true;assert.equal(I.resolve(p,{}).availability_status,'UNKNOWN');const x=I.resolve(p,{feed_presence_confirmed:true});assert.equal(x.availability_status,'IN_STOCK');assert.equal(x.stock_quantity,null);});
test('unknown supplier has no generic presence/quantity policy',()=>{assert.equal(I.resolve(I.policy({id:'new'}),{stock:5,rawAvailability:'есть'}).availability_status,'UNKNOWN');});
test('wrong source column is not parsed under a confirmed policy',()=>{assert.equal(I.resolve(status,{rawAvailability:'есть',inventory_source_column:'Цена'}).availability_status,'UNKNOWN');});
test('cached observation cannot cross SKU or changed policy semantics',()=>{const prior={...I.resolve(status,{rawAvailability:'есть'}),supplier_sku:'A'};assert.equal(I.observe(status,{s:'B',last_valid_inventory_observation:prior}).availability_status,'UNKNOWN');assert.equal(I.observe({...status,status_map:{}},{s:'A',last_valid_inventory_observation:prior}).availability_status,'UNKNOWN');});
function setup(policy=status){const h=createHarness({runtime:true});h.ctx.policy=policy;h.run('S.cfg.suppliers[0].inventory_policy=policy;classificationEnable();');const p=h.product({category_locked:true,canonical_category_id:'clothing_pants',name:'Штани Test'});p.variants[0].size='48';Object.assign(p.variants[0].offers['supplier-a'],{stock:null,rawAvailability:'есть'});h.add(p);h.run('classificationApplyProduct(S.products.get("p-a"))');return h;}
const available=h=>h.run('classificationAvailability(S.products.get("p-a"),S.products.get("p-a").variants[0])');
const exported=h=>JSON.parse(JSON.stringify(h.run('classificationExport(S.products.get("p-a"),{publicOnly:true})')));
async function prepare(h){h.run('render=()=>{}');await h.run('Store.init()');h.run('markAllDirty()');await h.run('persist()');return h;}
async function imported(h,value,observed=''){h.ctx.rows=[['SKU','Name','Size','Наличие','Observed','Cost'],['feed-a','Штани Test','48',value,observed,1000]];h.run('S.imp={sup:"supplier-a",file:"status.csv",rows,hdr:0,map:{sku:0,name:1,size:2,stock:3,stockObservedAt:4,cost:5},zero:true}');await h.run('doImport()');assert.equal(await h.run('applyImport()'),true);}
test('STATUS null quantity passes actual export/schema/SIMPLE and immediate mock payment',()=>{const h=setup(),p=exported(h);assert.equal(validate(p),true,JSON.stringify(validate.errors));assert.equal(p.variants[0].stock,null);assert.equal(p.variants[0].stock_quantity,null);assert.equal(p.variants[0].availability_source,'STATUS');assert.equal(p.variants[0].stock_status,'CONFIRMED_BY_STATUS');assert.equal(p.variants[0].payment_allowed,true);assert.equal(h.run('simpleProductPayload(simpleAssess(S.products.get("p-a"))).variants[0].stock_quantity'),null);const api=createMockShop();api.loadFixture([p]);const o=api.submit({product_id:p.id,sku:p.variants[0].sku});assert.equal(api.pay(o.id).status,'PAID');});
test('STATUS unknown or older records retain last valid observation and identical import is stable',async()=>{const h=await prepare(setup());await imported(h,'есть',new Date(Date.now()-3600000).toISOString());const first=JSON.stringify(h.run('S.products.get("p-a").variants[0].offers["supplier-a"].last_valid_inventory_observation'));await imported(h,'unknown');assert.equal(available(h).availability,'IN_STOCK');await imported(h,'нет',new Date(Date.now()-86400000).toISOString());assert.equal(available(h).availability,'IN_STOCK');await imported(h,'есть');assert.equal(JSON.stringify(h.run('S.products.get("p-a").variants[0].offers["supplier-a"].last_valid_inventory_observation')),first);await imported(h,'нет',new Date(Date.now()-1800000).toISOString());assert.equal(available(h).availability,'OUT_OF_STOCK');assert.equal(available(h).stock_quantity,null);});
test('confirmed quantity semantics work with generic Наличие header',async()=>{const h=await prepare(setup({id:'confirmed-q',mode:'QUANTITY',confirmed:true,source_column:'Наличие'}));await imported(h,'1265');assert.equal(available(h).stock_quantity,1265);await imported(h,'0');assert.equal(available(h).availability,'OUT_OF_STOCK');await imported(h,'bad');assert.equal(available(h).stock_quantity,0);});
test('SKU size/binding checks do not erase source availability or unlock payment',()=>{const h=setup();h.run('S.products.get("p-a").variants[0].source_binding_status="CONFIRMATION_REQUIRED"');assert.equal(available(h).availability,'UNKNOWN');assert.equal(available(h).availability_status,'IN_STOCK');assert.equal(available(h).payment_allowed,false);h.run('S.products.get("p-a").variants[0].source_binding_status="CONFIRMED";S.products.get("p-a").variants[0].size_status="SIZE_CONFIRMATION_REQUIRED"');assert.equal(available(h).availability,'SIZE_CONFIRMATION_REQUIRED');assert.equal(available(h).availability_status,'IN_STOCK');assert.equal(available(h).payment_allowed,false);});
test('Prom delivery preorder remains manager-gated, with no manufacturing term',()=>{const h=setup(I.defaults.s2akya7xoafn);h.run('S.products.get("p-a").variants[0].offers["supplier-a"].rawAvailability="3"');const p=exported(h);assert.equal(validate(p),true,JSON.stringify(validate.errors));assert.equal(p.variants[0].availability,'PREORDER');assert.equal(p.variants[0].delivery_lead_time_days,3);assert.equal(p.variants[0].lead_time_days,null);assert.equal(p.variants[0].payment_allowed,false);const api=createMockShop();api.loadFixture([p]);const o=api.submit({product_id:p.id,sku:p.variants[0].sku});assert.throws(()=>api.pay(o.id),/FORBIDDEN/);api.confirmByManager(o.id,{sku:o.sku,price:o.price});assert.equal(api.pay(o.id).status,'PAID');});
test('actual Prom import keeps delivery-day value separate from generic order-on-request parsing',async()=>{const policy={...I.defaults.s2akya7xoafn,source_column:'Наличие'},h=await prepare(setup(policy));await imported(h,'3');const a=available(h);assert.equal(a.availability,'PREORDER');assert.equal(a.delivery_lead_time_days,3);assert.equal(a.stock_quantity,null);assert.equal(a.payment_allowed,false);assert.equal(h.run('S.products.get("p-a").variants[0].offers["supplier-a"].order_on_request'),false);assert.equal(validate(exported(h)),true,JSON.stringify(validate.errors));});
test('schema and mock reject forged status proof and fake quantity',()=>{const p=exported(setup());for(const edit of [v=>v.availability_confirmation='UNKNOWN',v=>v.inventory_policy_confirmed=false,v=>v.stock=5,v=>v.stock_quantity=5]){const x=structuredClone(p);edit(x.variants[0]);assert.equal(validate(x),false);}const api=createMockShop();api.loadFixture([p]);const o=api.submit({product_id:p.id,sku:p.variants[0].sku});p.variants[0].availability='OUT_OF_STOCK';p.variants[0].availability_status='OUT_OF_STOCK';Object.assign(p.variants[0],{order_submission_allowed:false,payment_allowed:false,requires_order_confirmation:false});Object.assign(p,{availability:'OUT_OF_STOCK',order_submission_allowed:false,payment_allowed:false,requires_order_confirmation:false});api.loadFixture([p]);assert.throws(()=>api.pay(o.id),/FORBIDDEN/);});
test('unknown inventory questions group once per supplier policy, not once per SKU',()=>{const h=setup({...I.defaults.s4p9slmnn0ki});h.run('const p=S.products.get("p-a");for(let i=0;i<20;i++){const v=structuredClone(p.variants[0]);v.sku="RUB-X"+i;v.offers["supplier-a"].s="FEED-X"+i;p.variants.push(v);}');const groups=h.run('classificationInventoryGroups()');assert.equal(groups.length,1);assert.equal(groups[0].count,21);assert.equal(groups[0].examples.length,3);});

test('manual stock correction outranks a cached quantity observation and reimport',async()=>{const h=await prepare(setup({id:'q',mode:'QUANTITY',confirmed:true,source_column:'Наличие'}));await imported(h,'5');h.run('S.products.get("p-a").variants[0].manualFields={stock:true};S.products.get("p-a").variants[0].offers["supplier-a"].stock=9');assert.equal(available(h).stock_quantity,9);assert.equal(available(h).availability_source,'MANUAL');await imported(h,'0');assert.equal(available(h).stock_quantity,9);});
test('manual availability override outranks confirmed supplier status',async()=>{const h=await prepare(setup());h.run('S.products.get("p-a").variants[0].manualFields={availability:true};S.products.get("p-a").variants[0].offers["supplier-a"].availability="out"');assert.equal(available(h).availability,'OUT_OF_STOCK');assert.equal(available(h).availability_source,'MANUAL');await imported(h,'есть');assert.equal(available(h).availability,'OUT_OF_STOCK');});
test('manual PREORDER status does not reuse supplier quantity as stock proof',()=>{const h=setup({id:'q',mode:'QUANTITY',confirmed:true,source_column:'Наличие'});h.run('const v=S.products.get("p-a").variants[0];v.offers["supplier-a"].stock=5;v.manualFields={availability:true};v.offers["supplier-a"].availability="order"');const a=available(h);assert.equal(a.availability,'PREORDER');assert.equal(a.stock_quantity,null);assert.equal(a.payment_allowed,false);assert.equal(validate(exported(h)),true,JSON.stringify(validate.errors));});
test('new queued model retains mapped size, status column and actual observation provenance',async()=>{
 const h=createHarness({runtime:true});h.ctx.policy=status;h.run('S.cfg.suppliers[0].inventory_policy=policy;S.cfg.suppliers[0].auto=true;');await prepare(h);
 h.ctx.rows=[['SKU','Name','Custom size','Наличие','Observed','Cost'],['new-sku','Штани New Model','48','есть','2026-10-01T12:00:00Z',1000]];
 h.run('S.imp={sup:"supplier-a",file:"new.csv",rows,hdr:0,map:{sku:0,name:1,size:2,stock:3,stockObservedAt:4,cost:5}}');await h.run('doImport()');assert.equal(await h.run('applyImport()'),true);
 assert.equal(h.run('S.products.size'),1);const p=h.run('[...S.products.values()][0]'),o=p.variants[0].offers['supplier-a'];assert.equal(o.inventory_source_column,'Наличие');assert.equal(o.structured_size,'48');assert.equal(o.size_input_provenance,'DEDICATED_COLUMN');assert.equal(o.stock_observed_at,Date.parse('2026-10-01T12:00:00Z'));assert.notEqual(o.imported_at,o.stock_observed_at);
 assert.equal(h.run('classificationAvailability([...S.products.values()][0],[...S.products.values()][0].variants[0]).payment_allowed'),true);assert.equal(p.variants[0].size,'48');
 h.run('S.cfg.suppliers[0].inventory_policy.source_column="Другой статус"');assert.equal(h.run('classificationAvailability([...S.products.values()][0],[...S.products.values()][0].variants[0]).availability'),'UNKNOWN');
});
