'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),V2=require('../lib/model-contract-v2.js'),{fixture}=require('./fixtures/model-v2.cjs');
const codes=b=>b.report.errors.map(e=>e.code);
test('explicit mapping builds one MODEL / three COLOR / six exact SKU without mutating sources',()=>{
 const {source,registry}=fixture(),before=V2.stable({source,registry}),bundle=V2.build(source,registry);
 assert.equal(bundle.report.ready_for_migration,true);assert.deepEqual(bundle.report.errors,[]);assert.ok(Object.values(bundle.report.summary).every(n=>n===0));
 assert.equal(bundle.models.length,1);assert.equal(bundle.models[0].colors.length,3);assert.equal(bundle.legacy_mapping.variant_mappings.length,6);assert.equal(V2.stable({source,registry}),before);
 const variants=bundle.models[0].colors.flatMap(c=>c.variants);assert.deepEqual(variants.map(v=>v.sku).sort(),source.variants.map(v=>v.legacy_sku).sort());
 for(const v of variants){const old=source.variants.find(o=>o.legacy_sku===v.sku);assert.equal(v.price,old.price);assert.equal(v.stock,old.stock);assert.deepEqual(v.supplier_links,old.supplier_links);assert.equal(v.legacy_variant_id,old.legacy_variant_id);}
 assert.deepEqual(bundle.categories,source.categories);assert.deepEqual(bundle.taxonomy_state,source.taxonomy_state);
});
test('similar titles create separate UNKNOWN drafts and never infer colors or photo ownership',()=>{const {source}=fixture(),r=V2.draft(source),b=V2.build(source,r);assert.equal(r.models.length,3);assert.equal(r.colors.length,0);assert.ok(r.variant_mappings.every(m=>m.color_id===null&&m.mapping_status==='UNKNOWN'));assert.ok(r.photo_mappings.every(m=>m.color_id===null));assert.equal(b.report.ready_for_migration,false);assert.equal(b.unmapped_variants.length,6);assert.ok(Object.values(b.report.summary).every(n=>n===0));});
test('unknown photos remain archived with null color and never reach public gallery',()=>{const {source,registry}=fixture();source.photos.push({...source.photos[0],legacy_photo_id:'ambiguous',url:'https://images.test/ambiguous.jpg'});registry.photo_mappings.push({legacy_photo_id:'ambiguous',photo_id:'ph_unknown',model_id:'mdl_husky',color_id:null,mapping_status:'UNKNOWN'});const b=V2.build(source,registry);assert.equal(b.report.ready_for_migration,true);assert.equal(b.models[0].unassigned_photos.length,1);assert.equal(JSON.stringify(V2.publicExport(b)).includes('ambiguous.jpg'),false);});
test('UNKNOWN photo with a guessed color is rejected',()=>{const {source,registry}=fixture();registry.photo_mappings[0].mapping_status='UNKNOWN';assert.ok(codes(V2.build(source,registry)).includes('UNKNOWN_PHOTO_COLOR'));});
test('missing SKU, variant, price, stock and provider lineage block migration with losses',()=>{const {source,registry}=fixture();registry.variant_mappings.pop();const b=V2.build(source,registry);for(const key of ['LOST_SKU','LOST_VARIANTS','LOST_PRICES','LOST_STOCK','LOST_SUPPLIER_LINKS'])assert.equal(b.report.summary[key],1);assert.equal(b.report.ready_for_migration,false);});
test('missing photo mapping reports a real lost reference',()=>{const {source,registry}=fixture();registry.photo_mappings.pop();assert.equal(V2.build(source,registry).report.summary.LOST_PHOTOS,1);});
test('duplicate target SKU/variant IDs never collapse into a single record',()=>{const {source,registry}=fixture();registry.variant_mappings[1].sku=registry.variant_mappings[0].sku;registry.variant_mappings[1].variant_id=registry.variant_mappings[0].variant_id;const b=V2.build(source,registry);assert.ok(codes(b).includes('DUPLICATE_ID'));assert.ok(codes(b).includes('SKU_IDENTITY_CHANGED'));});
test('two SKUs of the same color and size require review instead of duplicate size buttons',()=>{const {source,registry}=fixture();registry.variant_mappings[1].size.normalized='M';assert.ok(codes(V2.build(source,registry)).includes('DUPLICATE_COLOR_SIZE'));});
test('canonical ID changes, category parents and cycles block exports',()=>{const {source,registry}=fixture();registry.models[0].canonical_category_id='clothing';const b=V2.build(source,registry);assert.ok(codes(b).includes('CATEGORY_NOT_LEAF'));assert.equal(b.report.summary.LOST_CANONICAL_CATEGORIES,3);source.categories[0].parent_id='clothing_jackets';assert.ok(codes(V2.build(source,registry)).includes('CATEGORY_CYCLE'));});
test('grouping locks survive the new registry',()=>{const {source,registry}=fixture();source.products[0].protected.model_grouping_locked=true;assert.ok(codes(V2.build(source,registry)).includes('GROUPING_LOCK'));});
test('confirmed identities cannot move after import',()=>{const {source,registry}=fixture(),previous=structuredClone(registry);registry.variant_mappings[0].variant_id='different';assert.ok(codes(V2.build(source,registry,{previous})).includes('CONFIRMED_ID_CHANGED'));});
test('required empty size blocks active availability, never inventing one size',()=>{const {source,registry}=fixture();registry.variant_mappings[0].size.normalized=null;assert.ok(codes(V2.build(source,registry)).includes('REQUIRED_SIZE'));});
test('unconfirmed preorder, stale/unknown inventory and request deadlines are rejected',()=>{const {source,registry}=fixture();source.variants[0].availability='PREORDER';assert.ok(codes(V2.build(source,registry)).includes('PREORDER_NOT_CONFIRMED'));source.variants[0].availability='IN_STOCK';source.variants[0].stock_stale=true;assert.ok(codes(V2.build(source,registry)).includes('STOCK_NOT_CONFIRMED'));source.variants[0].stock_stale=false;source.variants[0].stock=null;assert.ok(codes(V2.build(source,registry)).includes('STOCK_NOT_CONFIRMED'));source.variants[0].availability='ORDER_ON_REQUEST';source.variants[0].lead_time_days=3;assert.ok(codes(V2.build(source,registry)).includes('REQUEST_DEADLINE'));});
test('all six availability states stay separate and nullable stock remains unknown',()=>{const {source,registry}=fixture();for(const [i,state] of V2.AVAILABILITY.entries()){Object.assign(source.variants[i],{availability:state,stock:state==='IN_STOCK'?4:null,preorder_confirmed:state==='PREORDER',lead_time_days:state==='PREORDER'?14:null});}const b=V2.build(source,registry);assert.equal(b.report.ready_for_migration,true);assert.deepEqual(new Set(b.models[0].colors.flatMap(c=>c.variants).map(v=>v.availability)),new Set(V2.AVAILABILITY));});
test('private exports retain supplier links while public exports exclude them and costs',()=>{const {source,registry}=fixture(),b=V2.build(source,registry),pub=JSON.stringify(V2.publicExport(b));assert.equal(pub.includes('supplier'),false);assert.equal(pub.includes('cost'),false);assert.equal(pub.includes('TEST_SECRET'),false);assert.equal(JSON.stringify(source).includes('TEST_SECRET'),false);assert.equal(b.source_archive.variants[0].supplier_links[0].raw.cost,1500);});
test('public color with no confirmed gallery cannot publish',()=>{const {source,registry}=fixture();for(const m of registry.photo_mappings){m.mapping_status='UNKNOWN';m.color_id=null;}assert.ok(codes(V2.build(source,registry)).includes('PUBLIC_COLOR_EMPTY'));});
test('old URLs yield explicit redirects and unknown URLs block site migration',()=>{const {source,registry}=fixture(),b=V2.build(source,registry);assert.equal(b.legacy_mapping.product_mappings[0].redirect_url,'/product/archon-husky?color=clr_black');source.products[0].legacy_urls=[];const blocked=V2.build(source,registry);assert.equal(blocked.report.ready_for_migration,false);assert.ok(blocked.report.warnings.some(w=>w.code==='LEGACY_URL_UNKNOWN'));});
test('external redirect paths and unsafe photo schemes are rejected',()=>{const {source,registry}=fixture();source.products[0].legacy_urls=['https://evil.test'];source.photos[0].url='javascript:alert(1)';const b=V2.build(source,registry);assert.ok(codes(b).includes('LEGACY_URL'));assert.ok(codes(b).includes('PHOTO_URL'));});
test('repeated export is deterministic; malformed schema is blocked',()=>{const {source,registry}=fixture();assert.equal(V2.stable(V2.build(source,registry)),V2.stable(V2.build(source,registry)));assert.equal(V2.build({},{}).report.ready_for_migration,false);});
test('photo identity survives reorder and cannot silently point to a replacement URL',()=>{const {products,source}=fixture();products[0].legacy_urls=['/product/'+products[0].slug];products[0].photos.push('https://images.test/additional.jpg');const a=V2.source({products},source.categories);products[0].photos.reverse();const b=V2.source({products},source.categories);assert.deepEqual(new Map(a.photos.map(p=>[p.url,p.legacy_photo_id])),new Map(b.photos.map(p=>[p.url,p.legacy_photo_id])));products[0].photos[0]='https://images.test/replacement.jpg';const c=V2.source({products},source.categories);assert.equal(c.photos.find(p=>p.url.endsWith('replacement.jpg')).legacy_photo_id===a.photos.find(p=>p.url.endsWith('additional.jpg')).legacy_photo_id,false);});
test('invalid exports cannot produce a public catalog and arbitrary private attributes are omitted',()=>{const {source,registry}=fixture();registry.models[0].attributes={season:'winter',supplier_cost:1500};let b=V2.build(source,registry);assert.deepEqual(V2.publicExport(b).models[0].attributes,{season:'winter'});registry.variant_mappings.pop();b=V2.build(source,registry);assert.deepEqual(V2.publicExport(b).models,[]);assert.equal(V2.publicExport(b).publication_blocked,true);});
test('complete 10000-model / 20000-SKU mapping preserves every value and gallery',()=>{
 const products=Array.from({length:10000},(_,i)=>({id:'p-'+i,name:'Model '+i,desc:'Description',canonical_category_id:'clothing_jackets',legacy_urls:['/product/old-'+i],photos:['https://images.test/'+i+'.jpg'],variants:['M','L'].map((size,j)=>({sku:'RUB-'+i+'-'+j,size,price:1000+i,stock:j+1,availability:'IN_STOCK'}))}));
 const source=V2.source({products},[{id:'clothing',parent_id:null},{id:'clothing_jackets',parent_id:'clothing'}]),r=V2.draft(source);
 const targets=new Map();for(const m of r.models){Object.assign(m,{slug:'new-'+m.model_id,size_policy:'REQUIRED',publication_status:'PUBLISHED',mapping_status:'CONFIRMED'});targets.set(m.model_id,'clr-'+m.model_id);r.colors.push({color_id:targets.get(m.model_id),model_id:m.model_id,color:'black',camouflage:null,mapping_status:'CONFIRMED'});}
 for(const mappings of [r.product_mappings,r.variant_mappings,r.photo_mappings])for(const m of mappings){m.color_id=targets.get(m.model_id);m.mapping_status='CONFIRMED';}
 const b=V2.build(source,r);assert.equal(b.report.ready_for_migration,true);assert.equal(b.models.length,10000);assert.equal(b.legacy_mapping.variant_mappings.length,20000);assert.equal(b.legacy_mapping.photo_mappings.length,10000);assert.ok(Object.values(b.report.summary).every(n=>n===0));
});
