'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{createService,digest}=require('../server/model-v2-server.cjs'),{fixture}=require('./fixtures/model-v2.cjs');
const token='local-test-token-for-isolated-v2-api-only-12345';
async function start(directory){const service=createService({directory,token});await new Promise(r=>service.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+service.server.address().port;return {...service,call:async(method,url,data,headers={})=>{const res=await fetch(base+url,{method,headers:{authorization:'Bearer '+token,'content-type':'application/json',...headers},...(data?{body:JSON.stringify(data)}:{})});return {status:res.status,data:await res.json()};},stop:()=>new Promise(r=>service.server.close(r))};}
test('durable API validates source, commits one batch atomically, survives restart and retries safely',async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pim-v2-api-'));let api=await start(dir);t.after(async()=>{if(api.server.listening)await api.stop();fs.rmSync(dir,{recursive:true,force:true});});
 const {source,registry}=fixture();let response=await api.call('POST','/api/pim/catalog-snapshots',{base_revision:0,source});assert.equal(response.status,201);
 const request={batch_id:'batch-1',base_revision:1,source_sha256:response.data.source_sha256,registry};request.request_hash=digest({base_revision:request.base_revision,source_sha256:request.source_sha256,registry});
 response=await api.call('POST','/api/pim/publish-batches',request);assert.equal(response.status,201);assert.equal(response.data.status,'READY_FOR_SITE');assert.equal(response.data.site_modified,false);assert.equal(response.data.result_revision,2);
 assert.equal((await api.call('POST','/api/pim/publish-batches',request)).status,200);assert.equal((await api.call('GET','/api/pim/export/models')).data.models.length,1);assert.equal((await api.call('GET','/api/pim/export/legacy-mapping')).data.variant_mappings.length,6);
 await api.stop();api=await start(dir);assert.equal((await api.call('GET','/api/pim/publish-batches/batch-1')).data.result_revision,2);assert.equal((await api.call('GET','/api/pim/status')).data.revision,2);
 assert.equal(fs.statSync(path.join(dir,'state.json')).mode&0o777,0o600);assert.equal(fs.statSync(dir).mode&0o777,0o700);
});
test('unauthorized, browser-origin and large/malformed requests never mutate state',async t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pim-v2-sec-'));const api=await start(dir);t.after(async()=>{await api.stop();fs.rmSync(dir,{recursive:true,force:true});});assert.equal((await api.call('GET','/api/pim/status',null,{authorization:'Bearer wrong'})).status,401);assert.equal((await api.call('GET','/api/pim/status',null,{origin:'https://evil.test'})).status,403);assert.equal((await api.call('POST','/api/pim/catalog-snapshots',{base_revision:0,source:{}})).status,422);assert.equal((await api.call('GET','/api/pim/status')).data.revision,0);});
test('two competing publishes cannot acknowledge two revisions from the same base',async t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pim-v2-race-'));const api=await start(dir);t.after(async()=>{await api.stop();fs.rmSync(dir,{recursive:true,force:true});});const {source,registry}=fixture();const s=await api.call('POST','/api/pim/catalog-snapshots',{base_revision:0,source});const data={base_revision:1,source_sha256:s.data.source_sha256,registry};const request_hash=digest(data);const responses=await Promise.all([api.call('POST','/api/pim/publish-batches',{...data,request_hash,batch_id:'a'}),api.call('POST','/api/pim/publish-batches',{...data,request_hash,batch_id:'b'})]);assert.deepEqual(responses.map(r=>r.status).sort(),[201,409]);assert.equal((await api.call('GET','/api/pim/status')).data.revision,2);});
test('missing mapping aborts entire batch and produces no active export',async t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pim-v2-block-'));const api=await start(dir);t.after(async()=>{await api.stop();fs.rmSync(dir,{recursive:true,force:true});});const {source,registry}=fixture();registry.variant_mappings.pop();const s=await api.call('POST','/api/pim/catalog-snapshots',{base_revision:0,source});const data={base_revision:1,source_sha256:s.data.source_sha256,registry};const response=await api.call('POST','/api/pim/publish-batches',{...data,batch_id:'blocked',request_hash:digest(data)});assert.equal(response.status,422);assert.equal((await api.call('GET','/api/pim/status')).data.revision,1);assert.equal((await api.call('GET','/api/pim/export/models')).status,409);});
test('source change marks previous batch stale and requires a new verified export',async t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pim-v2-stale-'));const api=await start(dir);t.after(async()=>{await api.stop();fs.rmSync(dir,{recursive:true,force:true});});const {source,registry}=fixture();const s=await api.call('POST','/api/pim/catalog-snapshots',{base_revision:0,source});const data={base_revision:1,source_sha256:s.data.source_sha256,registry};await api.call('POST','/api/pim/publish-batches',{...data,batch_id:'b',request_hash:digest(data)});source.variants[0].price=4500;assert.equal((await api.call('POST','/api/pim/catalog-snapshots',{base_revision:2,source})).status,201);assert.equal((await api.call('GET','/api/pim/publish-batches/b')).data.status,'STALE');assert.equal((await api.call('GET','/api/pim/export/models')).status,409);});
test('single writer lock and outside-web-root restriction protect private state',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pim-v2-lock-'));try{const first=createService({directory:dir,token});assert.throws(()=>createService({directory:dir,token}),/EEXIST/);first.close();assert.throws(()=>createService({directory:path.resolve(__dirname,'..','.private'),token}),/outside/);assert.throws(()=>createService({directory:dir,token:'short'}),/32/);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('a refresh cannot delete an existing source SKU or photo lineage',async t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pim-v2-refresh-'));const api=await start(dir);t.after(async()=>{await api.stop();fs.rmSync(dir,{recursive:true,force:true});});const {source}=fixture();await api.call('POST','/api/pim/catalog-snapshots',{base_revision:0,source});source.variants.pop();source.photos.pop();const r=await api.call('POST','/api/pim/catalog-snapshots',{base_revision:1,source});assert.equal(r.status,422);assert.equal(r.data.error,'SOURCE_LOSS_BLOCKED');assert.equal((await api.call('GET','/api/pim/status')).data.revision,1);});
