const {test}=require('node:test'),assert=require('node:assert/strict'),{createHarness}=require('./isolated-harness.cjs');
function family({codes=true}={}){const h=createHarness();h.run('S.cfg.category_engine={version:1,migration_validated:true};S.cfg.simple_mode_version=1;');for(const [i,color] of ['Black','Multicam','Olive'].entries()){const p=h.product({id:'p-'+i,name:'Куртка Archon Husky Extreme '+color,canonical_category_id:'clothing_jackets',last_confirmed_category_id:'clothing_jackets',primary_product_type:'clothing',created:i+1,photos:['https://images.test/'+color+'.jpg'],desc:'<p>'+('Утеплена зимова куртка з кишенями і капюшоном. '.repeat(8))+'</p>'});p.variants=['M','L'].map((size,j)=>({sku:'RUB-'+i+'-'+j,color,size,offers:{'supplier-a':{s:'SUP-'+i+'-'+j,source_model:codes?'HUSKY-EXTREME':null,cost:1000,payout:1000,stock:i+2,availability:'in',at:Date.now(),photos:p.photos}}}));h.add(p);}return h;}
test('explicit manual legacy merge preserves three colors and six SKUs; inference never auto-applies',()=>{const h=family();const before=h.run('stableValue105([...S.products.values()].flatMap(p=>p.variants).sort((a,b)=>a.sku.localeCompare(b.sku)))');const plan=h.run('mcPlan()');assert.equal(plan.automatic.length,0);h.run('if(mcPlan().groups.length)mcMergeGroup(mcPlan().groups[0],{manual:true});mcMigrate([])');assert.equal(h.run('[...S.products.values()].filter(p=>!p.archived).length'),1);assert.equal(h.run('S.products.get("p-0").variants.length'),6);assert.equal(h.run('mcColors(S.products.get("p-0")).length'),3);assert.equal(h.run('stableValue105([...S.products.values()].flatMap(p=>p.variants).sort((a,b)=>a.sku.localeCompare(b.sku)))'),before);assert.equal(h.run('mcResolveId("p-2")'),'p-0');});
test('matching rich titles and full descriptions never authorize an automatic merge',()=>{const h=family({codes:false});assert.equal(h.run('mcPlan().automatic.length'),0);h.run('S.products.get("p-2").desc="Інша модель: ізольована підкладка, інший матеріал.";S.products.get("p-2").fieldMeta.desc.supplierOriginal=S.products.get("p-2").desc;markProduct(S.products.get("p-2"));');assert.equal(h.run('mcPlan().automatic.length'),0);});
test('generic similar names are one optional family question and never automatic joins',()=>{const h=family({codes:false});h.run('for(const p of S.products.values()){p.name="Футболка Kiborg "+p.variants[0].color;markProduct(p);}');assert.equal(h.run('mcPlan().automatic.length'),0);assert.equal(h.run('mcPlan().review.length'),1);});
test('different explicit model codes are never merged',()=>{const h=family();h.run('for(const v of S.products.get("p-2").variants)v.offers["supplier-a"].source_model="HUSKY-OTHER";markProduct(S.products.get("p-2"));');assert.equal(h.run('mcPlan().automatic.length'),0);assert.throws(()=>h.run('mcMergeGroup(mcPlan().groups[0],{manual:true})'),/разные коды/);});
test('different category, technical specification and manual descriptions preserve separate products',()=>{const h=family();h.run('S.products.get("p-2").attrs.Protection="NIJ IV";markProduct(S.products.get("p-2"));');assert.equal(h.run('mcPlan().automatic.length'),0);assert.throws(()=>h.run('mcMergeGroup(mcPlan().groups[0],{manual:true})'),/характеристики/);});
test('same color and size in different source products are never collapsed by accident',()=>{const h=family();h.run('for(const p of S.products.values()){for(const v of p.variants)v.color="Black";markProduct(p);}');assert.equal(h.run('mcPlan().automatic.length'),0);assert.equal(h.run('[...S.products.values()].flatMap(p=>p.variants).length'),6);});
test('changing color changes gallery and available sizes; changing size chooses exact SKU',()=>{const h=family();h.run('if(mcPlan().groups.length)mcMergeGroup(mcPlan().groups[0],{manual:true});mcMigrate([])');const colors=h.run('mcColors(S.products.get("p-0"))');h.ctx.colorId=colors.find(c=>c.camouflage==='Мультикам').id;const select=h.run('mcSelect(S.products.get("p-0"),colorId,"RUB-1-1")');assert.equal(select.variant.sku,'RUB-1-1');assert.deepEqual(Array.from(select.photos),['https://images.test/Multicam.jpg']);assert.deepEqual(Array.from(select.size_options,v=>v.sku),['RUB-1-0','RUB-1-1']);h.ctx.colorId=colors.find(c=>c.color==='Чорний').id;assert.deepEqual(Array.from(h.run('mcSelect(S.products.get("p-0"),colorId,"RUB-1-1").photos')),['https://images.test/Black.jpg']);assert.equal(h.run('mcSelect(S.products.get("p-0"),colorId,"RUB-1-1").variant.sku'),'RUB-0-0');});
test('ambiguous multi-color master photos are never assigned to every color',()=>{const h=family();h.run('var p=S.products.get("p-0");p.variants[1].color="Olive";for(const v of p.variants)v.offers["supplier-a"].photos=[];markProduct(p);');const colors=h.run('mcColors(p)');assert.ok(colors.every(c=>c.photos.length===0&&c.photo_assignment==='unknown'));});
test('model feed has stable colors and color-specific photos through legacy publication adapter',()=>{const h=family();h.run('if(mcPlan().groups.length)mcMergeGroup(mcPlan().groups[0],{manual:true});mcMigrate([])');const feed=h.run('buildFeed().feed.products');assert.equal(feed.length,1);const x=h.run('sitePayloadProduct(buildFeed().feed.products[0])');assert.equal(x.model_colors_version,1);assert.equal(x.colors.length,3);assert.equal(x.variants.length,6);assert.equal(x.source_product_ids.length,3);for(const v of x.variants){const c=x.colors.find(c=>c.id===v.color_id);assert.ok(c);assert.ok(c.variant_skus.includes(v.sku));assert.deepEqual(Array.from(v.photos),Array.from(c.photos));assert.equal(v.cost,undefined);}});
test('merged cards are explicitly hidden without local publication hashes and not hidden again after acknowledgement',async()=>{const h=family();await h.run('Store.init()');h.run('if(mcPlan().groups.length)mcMergeGroup(mcPlan().groups[0],{manual:true});mcMigrate([])');const plan=await h.run('simplePublicationPlan()');assert.deepEqual([...plan.hide].sort(),['p-1','p-2']);h.ctx.hide=plan.hide;await h.run('simpleConfirmHide(hide,{hidden_ids:hide})');assert.equal((await h.run('simplePublicationPlan()')).hide.length,0);});
test('SIMPLE apply retains separate source cards and rollback restores original records',async()=>{const h=family();h.ctx.setTimeout=setTimeout;h.ctx.clearTimeout=clearTimeout;await h.run('Store.init();markAllDirty();persist()');const before=h.run('stableValue105([...S.products.values()].map(p=>[p.id,p.name,p.desc,p.photos,p.variants]))');h.run('SIMPLE_UI.preview=simplePolicyPreview()');await h.run('simpleApplyPolicy()');assert.equal(h.run('S.products.get("p-0").variants.length'),2);const data=await h.run('persistedStateData("verify")');assert.equal(data.products.find(p=>p.id==='p-0').variants.length,2);const backup=await h.run('Store.get("safety/before_simple")');h.ctx.backup=backup;h.run('loadStateData(backup);markAllDirty()');await h.run('persist()');assert.equal(h.run('stableValue105([...S.products.values()].map(p=>[p.id,p.name,p.desc,p.photos,p.variants]))'),before);});
test('repeated migration changes neither variant counts nor source color galleries',()=>{const h=family();h.run('if(mcPlan().groups.length)mcMergeGroup(mcPlan().groups[0],{manual:true});mcMigrate([])');const before=h.run('stableValue105([...S.products.values()])');h.run('if(mcPlan().groups.length)mcMergeGroup(mcPlan().groups[0],{manual:true});mcMigrate([])');assert.equal(h.run('stableValue105([...S.products.values()])'),before);});
test('shop without model color capability is blocked before POST',async()=>{const h=family();h.run('mcMigrate();S.cfg.siteApi={url:"https://shop.test",key:"test"};var posts=[];siteFetch=async(path,opt)=>{posts.push(path);return {ok:true,capabilities:{canonical_category_version:1,product_model_version:1,order_on_request_version:1}}};');await h.run('sitePublish("delta")');assert.equal(h.run('posts.includes("/pim/sync")'),false);assert.match(h.run('S.cfg.siteSync.lastError'),/model_colors/);});
test('supplier SKU, title, price and camouflage attributes do not pretend to be physical model differences',()=>{const h=family();h.run('for(const p of S.products.values()){p.attrs.Артикул=p.id;p.attrs.Назва=p.name;p.attrs.Ціна=p.id;p.canonical_attributes={camouflage:p.variants[0].color};markProduct(p);}');assert.equal(h.run('mcPlan().automatic.length'),0);});
test('clear specification conflict does not ask the owner to approve an impossible merge',()=>{const h=family();h.run('S.cfg.model_colors_version=1;S.products.get("p-2").attrs.Protection="NIJ IV";markProduct(S.products.get("p-2"));');assert.equal(h.run('simpleDecisions().filter(t=>t.kind==="model").length'),0);assert.equal(h.run('[...S.products.values()].filter(p=>!p.archived).length'),3);});
test('manual product photo choices are not replaced by supplier galleries',()=>{const h=family();h.run('var p=S.products.get("p-0");p.photos=["https://images.test/manual.jpg"];p.fieldMeta.photos.source="manual";markProduct(p);');assert.deepEqual(Array.from(h.run('mcColors(p)[0].photos')),['https://images.test/manual.jpg']);});
test('manual grouping locks prevent rejoining separated products',()=>{const h=family();h.run('for(const p of S.products.values()){p.model_grouping_locked=true;markProduct(p);}');assert.equal(h.run('mcPlan().groups.length'),0);});
