'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),Ajv=require('ajv');
const {createHarness}=require('./isolated-harness.cjs'),{createMockShop}=require('./mock-shop-api.cjs');
const validate=new Ajv({strict:false}).compile(require('../contracts/category-size-export.schema.json'));
function setup(){const h=createHarness({runtime:true});h.run('classificationEnable();S.cfg.suppliers.find(s=>s.id==="supplier-a").stock_freshness_hours=72;');const p=h.product({name:'Штани Test',canonical_category_id:'clothing_pants',category_locked:true});p.variants[0].size='48';h.add(p);h.run('classificationApplyProduct(S.products.get("p-a"))');return h;}
const available=h=>h.run('classificationAvailability(S.products.get("p-a"),S.products.get("p-a").variants[0])');
const exported=h=>JSON.parse(JSON.stringify(h.run('classificationExport(S.products.get("p-a"),{publicOnly:true})')));
const offer=(h,code)=>h.run('Object.assign(S.products.get("p-a").variants[0].offers["supplier-a"],'+JSON.stringify(code)+');bumpData()');
test('separate permission truth table, schema and SIMPLE payload for every availability',()=>{
 for(const [status,changes,submit,payment,confirm] of [
 ['IN_STOCK',{stock:3},true,true,false],['OUT_OF_STOCK',{stock:0},false,false,false],
 ['PREORDER',{availability:'order',preorder:true,preorder_confirmed:true},true,false,true],
 ['ORDER_ON_REQUEST',{availability:'order',preorder:false,order_on_request:true},true,false,true],
 ['UNKNOWN',{stock:null},false,false,true],['SIZE_CONFIRMATION_REQUIRED',{stock:3},true,false,true]]){
  const h=setup();offer(h,changes);if(status==='SIZE_CONFIRMATION_REQUIRED')h.run('S.products.get("p-a").variants[0].size_status="SIZE_CONFIRMATION_REQUIRED"');
  const a=available(h);assert.equal(a.availability,status);for(const [key,val] of Object.entries({order_submission_allowed:submit,payment_allowed:payment,requires_order_confirmation:confirm}))assert.equal(a[key],val,status+':'+key);
  const p=exported(h);assert.equal(validate(p),true,JSON.stringify(validate.errors));assert.equal('checkout_allowed' in p.variants[0],false);
  const simple=h.run('simpleProductPayload(simpleAssess(S.products.get("p-a")))');assert.equal(simple.variants[0].payment_allowed,payment);assert.equal(simple.variants[0].order_submission_allowed,submit);
 }
});
test('PREORDER submits a pending order; forged client permissions cannot unlock payment',()=>{const h=setup();offer(h,{availability:'order',preorder:true,preorder_confirmed:true});const api=createMockShop();api.loadFixture([exported(h)]);assert.equal(api.status().capabilities.order_policy_version,1);assert.throws(()=>api.sync(),/blocked/);const o=api.submit({product_id:'p-a',sku:'RUB-00001',payment_allowed:true,requires_order_confirmation:false});assert.equal(o.status,'PENDING_MANAGER');assert.throws(()=>api.pay(o.id),/PAYMENT_FORBIDDEN/);api.confirmByManager(o.id,{sku:o.sku,price:o.price});assert.equal(api.pay(o.id).status,'PAID');});
test('ORDER_ON_REQUEST stays distinct and waits for manager; UNKNOWN cannot pay',()=>{const h=setup();offer(h,{order_on_request:true});const api=createMockShop();api.loadFixture([exported(h)]);const o=api.submit({product_id:'p-a',sku:'RUB-00001'});assert.throws(()=>api.pay(o.id),/FORBIDDEN/);assert.equal(exported(h).variants[0].availability,'ORDER_ON_REQUEST');offer(h,{order_on_request:false,stock:null});api.loadFixture([exported(h)]);assert.throws(()=>api.submit({product_id:'p-a',sku:'RUB-00001'}),/FORBIDDEN/);});
test('size option permits only a request and cannot be paid or confirmed as a fake SKU',()=>{const h=setup();h.run('S.products.get("p-a").size_catalogs=[{catalog_id:"test",scope:"MODEL",color_id:null,size_system:"clothing_numeric",allowed_sizes:["50"]}]');const p=exported(h),api=createMockShop();api.loadFixture([p]);const o=api.submit({product_id:p.id,option_id:p.size_options[0].option_id});assert.equal(o.sku,null);assert.equal(o.status,'PENDING_MANAGER');assert.throws(()=>api.pay(o.id),/FORBIDDEN/);assert.throws(()=>api.confirmByManager(o.id,{sku:'FAKE-50',price:1000}),/INVALID/);assert.throws(()=>api.confirmByManager(o.id,{sku:'RUB-00001',price:p.variants[0].price}),/INVALID/);});
test('confirmed in-stock SKU can proceed directly to payment; zero cannot submit',()=>{const h=setup(),api=createMockShop();api.loadFixture([exported(h)]);const o=api.submit({product_id:'p-a',sku:'RUB-00001'});assert.equal(api.pay(o.id).status,'PAID');offer(h,{stock:0});api.loadFixture([exported(h)]);assert.throws(()=>api.submit({product_id:'p-a',sku:'RUB-00001'}),/FORBIDDEN/);});
test('schema rejects payment on preorder, unknown, requests and size options and obsolete checkout_allowed',()=>{for(const availability of ['PREORDER','ORDER_ON_REQUEST','UNKNOWN','SIZE_CONFIRMATION_REQUIRED']){const h=setup();offer(h,availability==='PREORDER'?{availability:'order',preorder:true,preorder_confirmed:true}:availability==='ORDER_ON_REQUEST'?{order_on_request:true}:{stock:null});if(availability==='SIZE_CONFIRMATION_REQUIRED')h.run('S.products.get("p-a").variants[0].size_status="SIZE_CONFIRMATION_REQUIRED"');const p=exported(h);p.variants[0].payment_allowed=true;assert.equal(validate(p),false,availability);}const p=exported(setup());p.variants[0].checkout_allowed=true;assert.equal(validate(p),false);});
test('age and supplier warning thresholds never change valid stock or payment',()=>{const h=setup();offer(h,{stock_observed_at:Date.now()-90*24*3600000});assert.equal(available(h).availability,'IN_STOCK');assert.equal(available(h).payment_allowed,true);assert.equal(available(h).stale_source,true);h.run('S.cfg.suppliers.find(s=>s.id==="supplier-a").stock_freshness_hours=1');assert.equal(available(h).availability,'IN_STOCK');offer(h,{stock_observed_at:null,imported_at:Date.now()});assert.equal(available(h).availability,'IN_STOCK');assert.equal(available(h).stock_data_age_hours,null);});
test('missing or invalid stock is UNKNOWN, confirmed zero is OUT, expiry only follows explicit source expiry',()=>{const h=setup();for(const stock of [null,-1,'3']){offer(h,{stock});assert.equal(available(h).availability,'UNKNOWN');}offer(h,{stock:0,stock_observed_at:Date.now()-90*24*3600000});assert.equal(available(h).availability,'OUT_OF_STOCK');offer(h,{stock:3,expires_at:Date.now()-3600000});assert.equal(available(h).availability,'UNKNOWN');offer(h,{expires_at:Date.now()+3600000});assert.equal(available(h).payment_allowed,true);});
test('import timestamps do not manufacture observation metadata and absence of that metadata does not invalidate numeric stock',async()=>{const h=setup();h.run('render=()=>{}');await h.run('Store.init()');h.run('markAllDirty()');await h.run('persist()');for(const observed of ['',new Date(Date.now()-3600000).toISOString()]){h.ctx.rows=[['SKU','Name','Size','Stock','Observed','Cost'],['feed-a','Штани Test','48',3,observed,1000]];h.run('S.imp={sup:"supplier-a",file:"test.csv",rows,hdr:0,map:{sku:0,name:1,size:2,stock:3,stockObservedAt:4,cost:5},zero:false}');await h.run('doImport()');assert.equal(await h.run('applyImport()'),true);const o=h.run('S.products.get("p-a").variants[0].offers["supplier-a"]');assert.ok(o.imported_at);assert.equal(o.stock_observed_at,observed?Date.parse(observed):null);assert.equal(available(h).availability,'IN_STOCK');}});
test('supplier freshness control renders and zero stock/default preorder settings never manufacture preorder',()=>{const h=setup();assert.match(h.run('vSupplier("supplier-a")'),/data-sf="stock_freshness_hours"/);offer(h,{stock:0,preorder:true,availability:'out'});assert.equal(available(h).availability,'OUT_OF_STOCK');offer(h,{availability:'order',stock_observed_at:null,preorder:true,preorder_confirmed:false,rawAvailability:''});assert.equal(available(h).availability,'OUT_OF_STOCK');});
test('mock payment ignores mere ageing after submission but respects explicit expiry',()=>{const h=setup();let clock=Date.now();const api=createMockShop({now:()=>clock});api.loadFixture([exported(h)]);const o=api.submit({product_id:'p-a',sku:'RUB-00001'});clock+=90*24*3600000;assert.equal(api.pay(o.id).status,'PAID');const p=exported(h);p.variants[0].expires_at=clock+3600000;api.loadFixture([p]);const q=api.submit({product_id:'p-a',sku:'RUB-00001'});clock+=2*3600000;assert.throws(()=>api.pay(q.id),/PAYMENT_FORBIDDEN/);});

test('mock rejects SKU/size/color mismatch supplied by the buyer',()=>{const h=setup(),api=createMockShop();api.loadFixture([exported(h)]);assert.throws(()=>api.submit({product_id:'p-a',sku:'RUB-00001',size:'50'}),/SELECTION_MISMATCH/);assert.throws(()=>api.submit({product_id:'p-a',sku:'RUB-00001',color_id:'FAKE-COLOR'}),/SELECTION_MISMATCH/);});
test('changed selected size invalidates payment after order creation',()=>{const h=setup(),api=createMockShop();const p=exported(h);api.loadFixture([p]);const o=api.submit({product_id:p.id,sku:p.variants[0].sku});p.variants[0].size='50';api.loadFixture([p]);assert.throws(()=>api.pay(o.id),/PAYMENT_FORBIDDEN/);});

test('release restores production namespace and never trusts processing time as observation',()=>{const h=setup();assert.equal(h.run('Store.fallbackPrefix'),'rubizh_pim_v7_launch:');const at=Date.now()-3600000;offer(h,{at,imported_at:at,stock_observed_at:at});assert.equal(available(h).availability,'IN_STOCK');assert.equal(available(h).stock_observed_at,null);offer(h,{stock_observation_provenance:'SUPPLIER_FIELD'});assert.equal(available(h).availability,'IN_STOCK');});

test('old backup cannot export the obsolete payment contract before runtime classification',()=>{const h=setup();h.run('delete S.cfg.classification_version');assert.equal(h.run('buildFeed().version'),3);assert.equal(h.run('buildFeed().classification_pending'),true);assert.equal(h.run('buildFeed().products.length'),0);assert.throws(()=>h.run('classificationExport(S.products.get("p-a"))'),/RC_IMPORT_REQUIRED/);assert.throws(()=>h.run('simpleProductPayload(simpleAssess(S.products.get("p-a")))'),/RC_IMPORT_REQUIRED/);});
async function stockImport(h,stock,observed=''){h.ctx.rows=[['SKU','Name','Size','Stock','Observed','Cost'],['feed-a','Штани Test','48',stock,observed,1000]];h.run('S.imp={sup:"supplier-a",file:"observation.csv",rows,hdr:0,map:{sku:0,name:1,size:2,stock:3,stockObservedAt:4,cost:5},zero:false}');await h.run('doImport()');assert.equal(await h.run('applyImport()'),true);}
async function storedHarness(){const h=setup();h.run('render=()=>{}');await h.run('Store.init()');h.run('markAllDirty()');await h.run('persist()');return h;}
test('missing and invalid stock updates keep the last confirmed observation until a valid zero arrives',async()=>{const h=await storedHarness();for(const bad of ['',-1,'unparseable']){await stockImport(h,bad);assert.equal(available(h).stock,5);assert.equal(available(h).payment_allowed,true);assert.equal(h.run('S.products.get("p-a").variants[0].offers["supplier-a"].stock_input_warning'),'INVALID_OR_MISSING_STOCK_RETAINED');}await stockImport(h,0);assert.equal(available(h).availability,'OUT_OF_STOCK');assert.equal(available(h).payment_allowed,false);});
test('older or conflicting dated observation cannot overwrite a newer valid observation',async()=>{const h=await storedHarness(),newer=new Date(Date.now()-3600000).toISOString(),older=new Date(Date.now()-86400000).toISOString();await stockImport(h,7,newer);await stockImport(h,0,older);assert.equal(available(h).stock,7);await stockImport(h,0,newer);assert.equal(available(h).stock,7);await stockImport(h,0,new Date(Date.now()-1800000).toISOString());assert.equal(available(h).stock,0);});
test('manual stock correction outranks supplier update and no new source never changes the last stock',async()=>{const h=await storedHarness();h.run('S.products.get("p-a").variants[0].manualFields={stock:true};S.products.get("p-a").variants[0].offers["supplier-a"].stock=9');await stockImport(h,0,new Date(Date.now()-3600000).toISOString());assert.equal(available(h).stock,9);h.run('S.cfg.freshHours=0.001;S.products.get("p-a").variants[0].offers["supplier-a"].stock_observed_at=Date.now()-365*24*3600000;bumpData()');assert.equal(available(h).stock,9);assert.equal(available(h).payment_allowed,true);});
test('global legacy freshHours cannot remove an aged confirmed stock from the runtime pricing/availability path',()=>{const h=setup();offer(h,{at:Date.now()-365*24*3600000,stock_observed_at:Date.now()-365*24*3600000});h.run('S.cfg.freshHours=1;bumpData()');assert.equal(available(h).stock,5);assert.equal(available(h).payment_allowed,true);assert.equal(h.run('calc(S.products.get("p-a"),S.products.get("p-a").variants[0]).o.stock_stale'),false);});

test('older explicit preorder observation cannot change availability of a newer stocked observation',async()=>{const h=await storedHarness();await stockImport(h,7,new Date(Date.now()-3600000).toISOString());h.ctx.rows=[['SKU','Name','Size','Stock','Observed','Cost','Preorder'],['feed-a','Штани Test','48',0,new Date(Date.now()-86400000).toISOString(),1000,'true']];h.run('S.imp={sup:"supplier-a",file:"older.csv",rows,hdr:0,map:{sku:0,name:1,size:2,stock:3,stockObservedAt:4,cost:5,preorder:6},zero:false}');await h.run('doImport()');assert.equal(await h.run('applyImport()'),true);assert.equal(available(h).availability,'IN_STOCK');assert.equal(available(h).stock,7);assert.equal(available(h).payment_allowed,true);});

test('manual unknown stock remains unknown on supplier reimport',async()=>{const h=await storedHarness();h.run('S.products.get("p-a").variants[0].manualFields={stock:true};S.products.get("p-a").variants[0].offers["supplier-a"].stock=null');await stockImport(h,3,new Date(Date.now()-3600000).toISOString());assert.equal(available(h).availability,'UNKNOWN');assert.equal(h.run('S.products.get("p-a").variants[0].offers["supplier-a"].stock'),null);assert.equal(available(h).payment_allowed,false);});

test('classified pipeline keeps the same age-independent stock rule outside the review mode flag',()=>{const h=setup();h.run('classificationReviewMode=()=>false;S.cfg.freshHours=1');offer(h,{at:Date.now()-365*24*3600000,stock_observed_at:Date.now()-365*24*3600000});assert.equal(h.run('offerStale(S.products.get("p-a").variants[0].offers["supplier-a"])'),false);assert.equal(available(h).payment_allowed,true);});
