const {test}=require('node:test'),assert=require('node:assert/strict'),{createHarness}=require('./isolated-harness.cjs');
function fixture(cost=1000){const h=createHarness(),p=h.product({canonical_category_id:'bags_backpacks',last_confirmed_category_id:'bags_backpacks'});p.variants[0].offers['supplier-a'].cost=p.variants[0].offers['supplier-a'].payout=cost;h.add(p);h.run('Object.assign(S.cfg,OWNER_PRICE_POLICY);S.cfg.simple_mode_version=1;S.cfg.category_engine={version:1,migration_validated:true};bumpData();var p=S.products.get("p-a"),v=p.variants[0];');return h;}
for(const [cost,price,margin] of [[1000,1590,30],[9999,15880,30],[10000,14710,25]])test('retail policy uses supplier payout threshold: '+cost,()=>{const h=fixture(cost),c=h.run('calc(p,v)');assert.equal(c.price,price);assert.ok(c.margin>=margin);assert.ok(h.run('marginAfterDonation(p,v).leftPct')>=margin-3-0.1);});
test('RRPs may raise automatic prices; mandatory RRP also protects discounts',()=>{const h=fixture();h.run('v.offers["supplier-a"].rrp=2000;S.cfg.suppliers[0].terms.rrp="Да, обязательно";bumpData();');assert.equal(h.run('calc(p,v).price'),2000);assert.equal(h.run('tierPrices(2000,S.cfg,p,v).length'),0);assert.ok(h.run('kitFloor(p,v)')>=2000);});
test('12 and 18 percent requests are capped to a verified price and labelled with actual discount',()=>{const h=fixture(),tiers=h.run('tierPrices(calc(p,v).price,S.cfg,p,v)');assert.equal(tiers.length,2);assert.equal(tiers[0].requested_discount,12);assert.equal(tiers[0].capped,false);assert.equal(tiers[1].requested_discount,18);assert.equal(tiers[1].capped,true);assert.ok(tiers[1].discount<18);for(const t of tiers){h.ctx.price=t.price;assert.ok(h.run('priceFinancial(price,calc(p,v).payout).margin')>=15);assert.ok(Math.abs(t.discount-(1-t.price/1590)*100)<.101);}});
test('expensive item discounts cannot repeat the former loss-making 18 percent price',()=>{const h=fixture(10000),tiers=h.run('tierPrices(calc(p,v).price,S.cfg,p,v)');assert.equal(tiers.length,1);assert.equal(tiers[0].capped,true);assert.ok(tiers[0].discount<10);h.ctx.price=tiers[0].price;assert.ok(h.run('priceFinancial(price,10000).margin')>=15);});
test('protected wholesale prices fail closed without a supplier-backed variant',()=>{const h=fixture();assert.equal(h.run('tierPrices(1590).length'),0);h.run('v.offers={};bumpData();');assert.equal(h.run('tierPrices(1590,S.cfg,p,v).length'),0);assert.equal(h.run('discountedPriceFloor(p,v)'),null);});
test('kit floor preserves 20 percent before donation and 15 percent after all specified costs',()=>{const h=fixture();h.run('S.cfg.deliveryCost=80;S.cfg.extraCost=20;S.cfg.roundMode="nine";bumpData();');const floor=h.run('kitFloor(p,v)');h.ctx.floor=floor;assert.ok(h.run('(floor-1000-floor*.07-100)/floor*100')>=20);assert.ok(h.run('priceFinancial(floor,1000).margin')>=15);assert.ok(floor<=h.run('calc(p,v).price'));});
test('kit catalog actually uses safe kit prices rather than standalone retail prices',()=>{const h=fixture(),vs=Object.values(h.run('pimKitProducts()[0].variants'));assert.equal(vs[0].price,h.run('kitFloor(p,v)'));assert.equal(vs[0].retail_price,1590);});
test('below-floor manual prices are preserved but cannot acquire wholesale or kit discounts',()=>{const h=fixture();h.run('v.price=1100;v.marginOverride=true;v.marginOverrideReason="Ручная цена";v.margin_override_authorized=true;bumpData();');assert.equal(h.run('calc(p,v).price'),1100);assert.equal(h.run('tierPrices(1100,S.cfg,p,v).length'),0);assert.equal(h.run('kitFloor(p,v)'),null);assert.equal(h.run('pimKitProducts().length'),0);});
test('mixed order enforces 15 percent even if an old UI target is 8 and donation is unchecked',()=>{const h=fixture();h.run('S.ui.quoteTarget=8;S.ui.quoteDon=false;S.cfg.deliveryCost=100;S.cfg.extraCost=50;');const q=h.run('quoteCalc(quoteParse("RUB-00001 10"))');assert.equal(q.targetPct,15);assert.equal(q.fixed,150);assert.ok(q.donation>0);assert.ok(q.profitPct>=15);assert.ok(q.targetMet);assert.ok(h.run('vQuote()').includes('checked disabled'));});
test('unresolved SKU prevents a partial order from becoming a valid customer quote',()=>{const h=fixture();const q=h.run('quoteCalc(quoteParse("RUB-00001 1\\nUNKNOWN 2"))');assert.equal(q.notFound,1);assert.equal(q.targetMet,false);});
test('public payload exports sale-price floors and contains no purchase cost or profit',()=>{const h=fixture(),x=h.run('sitePayloadProduct(buildFeed().feed.products[0])'),v=x.variants[0];assert.equal(x.pricing_policy_version,1);assert.equal(v.pricing_policy_version,1);assert.equal(v.discount_margin_floor_pct,15);assert.ok(v.minimum_sale_price>1000);for(const key of ['cost','payout','supplier_cost','netProfit','profit'])assert.equal(v[key],undefined);assert.equal(h.run('siteSettings104(buildFeed().feed).pricing_policy_version'),1);});
test('shop without pricing capability is rejected before any synchronization POST',async()=>{const h=fixture();h.run('S.cfg.siteApi={url:"https://shop.test",key:"test"};var posts=[];siteFetch=async(path,opt)=>{posts.push(path);return {ok:true,capabilities:{canonical_category_version:1,product_model_version:1,model_colors_version:1,order_on_request_version:1}}};');await h.run('sitePublish("delta")');assert.equal(h.run('posts.includes("/pim/sync")'),false);assert.match(h.run('S.cfg.siteSync.lastError'),/pricing_policy_version/);});
test('missing server pricing acknowledgement cannot create a successful product hash',async()=>{const h=fixture();await h.run('Store.init()');h.run('S.cfg.siteApi={url:"https://shop.test",key:"test"};siteFetch=async(path,opt)=>path==="/pim/status"?{ok:true,capabilities:{pricing_policy_version:1,canonical_category_version:1,product_model_version:1}}:{ok:true,category_catalog_hash:JSON.parse(opt.body).category_catalog_hash,results:JSON.parse(opt.body).products.map(p=>({id:p.id,status:"updated",canonical_category_id:p.canonical_category_id,product_model_version:1})),hidden_ids:[]};');await h.run('sitePublish("delta")');assert.match(h.run('S.cfg.siteSync.lastError'),/правила цен/);const hashes=await h.run('Store.get("site/hashes")');assert.ok(!hashes||!hashes['p-a']);});
test('supported shop acknowledges and saves the exact protected payload',async()=>{const h=fixture();await h.run('Store.init()');h.run('S.cfg.siteApi={url:"https://shop.test",key:"test"};siteFetch=async(path,opt)=>path==="/pim/status"?{ok:true,capabilities:{pricing_policy_version:1,canonical_category_version:1,product_model_version:1}}:{ok:true,category_catalog_hash:JSON.parse(opt.body).category_catalog_hash,results:JSON.parse(opt.body).products.map(p=>({id:p.id,status:"updated",canonical_category_id:p.canonical_category_id,product_model_version:1,pricing_policy_version:1})),hidden_ids:[]};');await h.run('sitePublish("delta")');assert.ok((await h.run('Store.get("site/hashes")'))['p-a']);});
function legacy(){const h=fixture();h.ctx.setTimeout=setTimeout;h.ctx.clearTimeout=clearTimeout;h.run('Object.assign(S.cfg,{pricing_policy_version:0,minMargin:24,bigPriceMargin:15,kitMargin:15,taxPct:5,acquiringPct:2});v.price=1490;markProduct(p);');return h;}
test('automatic upgrade backs up original settings and preserves all supplier offers and manual prices',async()=>{const h=legacy();await h.run('Store.init()');await h.run('persist()');const before=h.run('stableValue105([...S.products.values()])');assert.equal(await h.run('ensurePricingPolicy()'),true);assert.equal(h.run('stableValue105([...S.products.values()])'),before);const backup=await h.run('Store.get("safety/before_pricing_30_25_20")');assert.equal(backup.cfg.minMargin,24);assert.equal(backup.cfg.bigPriceMargin,15);assert.equal(h.run('S.cfg.minMargin'),30);assert.equal(h.run('S.cfg.bigPriceMargin'),25);assert.equal(h.run('S.cfg.kitMargin'),20);assert.equal(h.run('S.cfg.taxPct'),5);assert.equal(h.run('S.cfg.acquiringPct'),2);await h.run('load()');assert.equal(h.run('S.cfg.pricing_policy_version'),1);assert.equal(h.run('S.cfg.bigPriceMargin'),25);assert.equal(h.run('S.products.get("p-a").variants[0].price'),1490);});
test('upgrade is idempotent and does not reset later deliberate settings or overwrite first backup',async()=>{const h=legacy();await h.run('Store.init()');await h.run('persist()');await h.run('ensurePricingPolicy()');h.run('S.cfg.minMargin=35;S.cfgDirty=true;');await h.run('persist()');const backup=await h.run('Store.get("safety/before_pricing_30_25_20")');assert.equal(await h.run('ensurePricingPolicy()'),false);assert.equal(h.run('S.cfg.minMargin'),35);assert.equal((await h.run('Store.get("safety/before_pricing_30_25_20")')).at,backup.at);});
test('failed backup prevents any price policy change',async()=>{const h=legacy();await h.run('Store.init()');await h.run('persist()');h.run('requireBatchBackup=async()=>{throw Error("Storage full")};');await assert.rejects(h.run('ensurePricingPolicy()'),/Storage full/);assert.equal(h.run('S.cfg.minMargin'),24);assert.equal(h.run('S.cfg.pricing_policy_version'),0);});
test('failed save restores original policy and allows a verified retry',async()=>{const h=legacy();await h.run('Store.init()');await h.run('persist()');h.run('var originalPersist=persist;persist=async()=>false;');await assert.rejects(h.run('ensurePricingPolicy()'),/не сохранены/);assert.equal(h.run('S.cfg.bigPriceMargin'),15);assert.equal(h.run('S.cfg.pricing_policy_version'),0);h.run('persist=originalPersist');assert.equal(await h.run('ensurePricingPolicy()'),true);});
test('discounted prices remain safe across costs, fees, fixed expenses and rounding modes',()=>{const h=fixture();for(const cost of [1,9.99,100,9999,10000,30000])for(const mode of ['up','nine'])for(const fixed of [0,79]){h.ctx.setting={cost,mode,fixed};h.run('v.offers["supplier-a"].cost=v.offers["supplier-a"].payout=setting.cost;S.cfg.roundMode=setting.mode;S.cfg.extraCost=setting.fixed;bumpData();');const c=h.run('calc(p,v)'),tiers=h.run('tierPrices(calc(p,v).price,S.cfg,p,v)');for(const t of tiers){h.ctx.price=t.price;assert.ok(h.run('priceFinancial(price,calc(p,v).payout).margin')>=15,JSON.stringify({cost,mode,fixed,t}));assert.ok(t.price<=c.price);}}});

test('price settings save failure keeps old policy and retains draft for retry',async()=>{const h=fixture();await h.run('Store.init()');await h.run('persist()');h.run('S.priceDraft=priceSlice(S.cfg);S.priceDraft.extraCost=100;requireBatchBackup=async()=>true;var oldPersist=persist;persist=async()=>false;');await assert.rejects(h.run('savePriceSettings()'),/не сохранены/);assert.equal(h.run('S.cfg.extraCost'),0);assert.equal(h.run('S.priceDraft.extraCost'),100);h.run('persist=oldPersist');assert.equal(await h.run('savePriceSettings()'),true);assert.equal((await h.run('Store.get("meta/config")')).extraCost,100);});
 test('invalid price percentages are rejected before backup or mutation',async()=>{const h=fixture();h.run('S.priceDraft=priceSlice(S.cfg);S.priceDraft.taxPct=80;requireBatchBackup=async()=>{throw Error("BACKUP REACHED")};');await assert.rejects(h.run('savePriceSettings()'),/не оставляют/);assert.equal(h.run('S.cfg.taxPct'),5);});

test('failed pricing upgrade prevents publication of the old unconditional discounts',async()=>{const h=legacy();await h.run('Store.init()');h.run('requireBatchBackup=async()=>{throw Error("Storage full")};S.cfg.siteApi={url:"https://shop.test",key:"test"};var requests=[];siteFetch=async(path)=>{requests.push(path);return {ok:true}};');await assert.rejects(h.run('ensurePricingPolicy()'),/Storage full/);await h.run('sitePublish("delta")');assert.equal(h.run('requests.length'),0);assert.match(h.run('S.cfg.siteSync.lastError'),/Правила цен не применены/);});
