'use strict';const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{appRequire}=require('./isolated-harness.cjs');
function page(){const {document}=appRequire('linkedom').parseHTML(fs.readFileSync(path.join(__dirname,'../release-recovery.html'),'utf8')),m=new Map(),downloads=[],localStorage={getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k),key:i=>[...m.keys()][i],get length(){return m.size;}};const ctx={document,indexedDB:new(appRequire('fake-indexeddb').IDBFactory)(),localStorage,Blob,Response,TextEncoder,TextDecoder,ReadableStream,TextDecoderStream,CompressionStream,DecompressionStream,structuredClone,crypto:require('node:crypto').webcrypto,console,URL,confirm:()=>true,setTimeout:()=>{},btoa:s=>Buffer.from(s,'binary').toString('base64'),atob:s=>Buffer.from(s,'base64').toString('binary'),fetch:()=>{throw Error('NETWORK_FORBIDDEN');},showSaveFilePicker:async opt=>({createWritable:async()=>({write:async blob=>downloads.push({name:opt.suggestedName,blob}),close:async()=>{}})})};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'../lib/release-storage.js'),'utf8'),ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'../release-recovery.html'),'utf8').match(/<script>\s*([\s\S]*?)<\/script>/)[1],ctx);return {ctx,document,downloads,run:s=>vm.runInContext(s,ctx)};}
async function seed(h){await h.run('R.openDatabase().then(db=>R.write(db,[],[{key:"meta/config",data:{owner:"old",siteApi:{auto:true}}},{key:"cat/b01",data:{products:{old:{id:"old",variants:[]}}}},{key:"owner/unknown",data:{keep:true}}]))');}
async function choose(h){const d={format:'rubizh-pim-backup',cfg:{owner:'new',siteApi:{auto:true}},products:[{id:'new',photos:['photo.webp'],variants:[{sku:'SKU1',stock:null}]}],docs:[],logs:[]};h.document.getElementById('file').files=[new Blob([JSON.stringify(d)])];await h.document.getElementById('preview').onclick();assert.equal(h.document.getElementById('apply').disabled,false,h.document.getElementById('status').textContent);}
const capture=h=>h.run('R.openDatabase().then(db=>R.capture(db))');
test('standalone recovery preview is read-only; successful restore saves verified rescue and preserves exact payload',async()=>{const h=page();await seed(h);const before=JSON.stringify(await capture(h));await choose(h);assert.equal(JSON.stringify(await capture(h)),before);await h.document.getElementById('apply').onclick();const rows=await capture(h);assert.equal(rows.find(r=>r.key==='meta/config').data.owner,'new');assert.equal(rows.find(r=>r.key==='meta/config').data.siteApi.auto,false);assert.ok(rows.some(r=>r.key.startsWith('cat/')&&r.data.products?.new));assert.equal(h.downloads.length,1);h.ctx.file=h.downloads[0].blob;const b=await h.run('R.readFile(file)');assert.ok(b.rows.some(r=>r.key==='owner/unknown'));assert.match(h.document.getElementById('status').textContent,/Відновлено/);});
test('standalone recovery download cancellation leaves database unchanged',async()=>{const h=page();await seed(h);const before=JSON.stringify(await capture(h));await choose(h);h.ctx.showSaveFilePicker=async()=>{throw Object.assign(Error('cancel'),{name:'AbortError'});};await h.document.getElementById('apply').onclick();assert.equal(JSON.stringify(await capture(h)),before);assert.match(h.document.getElementById('status').textContent,/RESCUE_DOWNLOAD_CANCELLED/);});
test('standalone recovery rejects a source edit after preview',async()=>{const h=page();await seed(h);await choose(h);await h.run('R.openDatabase().then(async db=>R.write(db,await R.capture(db),[{key:"concurrent/edit",data:42}]))');const before=JSON.stringify(await capture(h));await h.document.getElementById('apply').onclick();assert.equal(JSON.stringify(await capture(h)),before);assert.equal(h.downloads.length,0);assert.match(h.document.getElementById('status').textContent,/STALE_RECOVERY/);});
test('failed recovery readback automatically restores exact rescue rows',async()=>{const h=page();await seed(h);await choose(h);const before=JSON.stringify(await capture(h));h.run('const actual=R.capture;let reads=0;R.capture=async db=>{const rows=await actual(db);if(++reads===4)rows.find(x=>x.key==="meta/config").data.owner="injected";return rows;};');await h.document.getElementById('apply').onclick();assert.match(h.document.getElementById('status').textContent,/RECOVERY_READBACK_FAILED/);assert.equal(JSON.stringify(await h.run('R.openDatabase().then(actual)')),before);});
