'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{createHarness}=require('./isolated-harness.cjs');
async function fixture({manual=true}={}){
 const h=createHarness({runtime:true,production:true});h.run('render=()=>{};S.cfg.siteApi={url:"https://shop.invalid",auto:true};S.cfg.suppliers[0].source={url:"https://supplier.invalid/file.xlsx",enabled:true,autoApply:true};');
 const p=h.product({canonical_category_id:'clothing_pants',category_locked:true,name:'Штани Test',desc:'<p>Описание поставщика без изменений</p>',manual_locks:manual?{name:true,desc:true}:undefined});p.variants[0].size='48';p.variants[0].manualFields=manual?{price:true}:undefined;h.add(p);
 await h.run('Store.init()');h.run('markAllDirty()');assert.equal(await h.run('productionPersist()'),true);
 await h.run('Store._set0("owner/custom",{value:42});Store._set0("docs/index",[{id:"proof",title:"Certificate"}]);Store._set0("docfile/proof",{blob:new Blob(["binary certificate"],{type:"application/pdf"})});');
 await h.run('productionLoad()');return h;
}
const rows=h=>h.run('productionCapture()'),text=(h,x)=>{h.ctx.rowsInput=x;return h.run('releaseStorage.rowText(rowsInput)');};
async function migrated(h){const r=await h.run('productionPreview()');assert.equal(r.LOST_SKU,0);assert.equal((await h.run('productionApply()')).PERSISTED_VERIFIED,true);return h;}
test('production uses the existing database and auth names, with no review namespace',async()=>{const h=await fixture();assert.equal(h.run('Store.db.name'),'rubizh_pim_v7_launch');assert.equal(h.run('SB_LS.cfg'),'rubizh_sb');assert.equal(h.run('classificationReviewMode()'),false);assert.equal(h.run('PRODUCTION_MIGRATION.state'),'pending');});
test('load/startup cannot silently rewrite, merge, publish, migrate pricing or fall back to old health snapshot',async()=>{const h=await fixture(),before=text(h,await rows(h));await h.run('load();startupIntegrityCheck();ensurePricingPolicy();v10Startup()');assert.equal(text(h,await rows(h)),before);assert.equal(h.run('S.products.get("p-a").desc'),'<p>Описание поставщика без изменений</p>');assert.equal(h.run('S.cfg.siteApi.auto'),true);});
test('migration preview is read-only, with 143 categories and all protected values unchanged',async()=>{const h=await fixture(),before=text(h,await rows(h));const r=await h.run('productionPreview()');assert.equal(r.categories_after,143);assert.equal(r.SYNC_ENABLED,false);assert.equal(r.AUTOPRICES_ENABLED,false);assert.equal(r.MANUAL_LOCKS_UNCHANGED,true);assert.equal(text(h,await rows(h)),before);assert.equal(h.downloads.length,0);});
test('full backup includes unknown KV records, logs/docs/binary files and real source state; backup hash is verified',async()=>{const h=await migrated(await fixture()),r=h.run('PRODUCTION_MIGRATION.lastReport');h.ctx.backupId=h.run('PRODUCTION_MIGRATION.backupId');const data=await h.run('(async()=>releaseStorage.readBackup(await releaseStorage.getBackup(backupId)))()');assert.equal(data.format,'rubizh-pim-production-snapshot');assert.equal(data.rows.find(x=>x.key==='owner/custom').data.value,42);assert.equal(await data.rows.find(x=>x.key==='docfile/proof').data.blob.text(),'binary certificate');assert.equal(data.rows.find(x=>x.key==='meta/config').data.siteApi.auto,true);assert.equal(r.PERSISTED_VERIFIED,true);assert.match(r.BACKUP_PATH,/rubizh_pim_release_backups/);assert.equal(h.downloads.length,1);});
test('apply keeps all IDs/SKU/photos/prices/stock/manual locks, disables operational gates and resumes ordinary PIM storage',async()=>{const h=await migrated(await fixture());assert.equal(h.run('S.products.get("p-a").variants[0].sku'),'RUB-00001');assert.equal(h.run('S.products.get("p-a").variants[0].offers["supplier-a"].stock'),5);assert.equal(h.run('S.products.get("p-a").pub'),true);assert.equal(h.run('S.products.get("p-a").manual_locks.desc'),true);assert.equal(h.run('S.cfg.siteApi.auto'),false);assert.equal(h.run('S.cfg.suppliers[0].source.enabled'),false);h.run('S.products.get("p-a").note="user edit";markProduct(S.products.get("p-a"))');assert.equal(await h.run('persist()'),true);await h.run('load()');assert.equal(h.run('S.products.get("p-a").note'),'user edit');});
test('restart and second identical migration are idempotent and produce no second backup or database write',async()=>{const h=await migrated(await fixture()),before=text(h,await rows(h));await h.run('productionLoad()');assert.equal(h.run('PRODUCTION_MIGRATION.state'),'ready');await h.run('productionPreview()');const r=await h.run('productionApply()');assert.equal(r.ALREADY_MIGRATED,true);assert.equal(text(h,await rows(h)),before);assert.equal(h.downloads.length,1);});
test('refused external backup download prevents migration',async()=>{const h=await fixture(),before=text(h,await rows(h));await h.run('productionPreview()');h.run('offerDownload=async()=>false');await assert.rejects(h.run('productionApply()'),/EXTERNAL_BACKUP_REQUIRED/);assert.equal(text(h,await rows(h)),before);});
test('backup storage failure prevents any migration write',async()=>{const h=await fixture(),before=text(h,await rows(h));await h.run('productionPreview()');h.run('releaseStorage.saveBackup=async()=>{throw Error("quota failure")};');await assert.rejects(h.run('productionApply()'),/quota failure/);assert.equal(text(h,await rows(h)),before);});
test('stale preview cannot overwrite another tab edit',async()=>{const h=await fixture();await h.run('productionPreview()');h.run('S.products.get("p-a").note="newer";markProduct(S.products.get("p-a"))');await h.run('productionPersist()');const before=text(h,await rows(h));await assert.rejects(h.run('productionApply()'),/STALE_MIGRATION/);assert.equal(text(h,await rows(h)),before);assert.equal(h.downloads.length,0);});
test('atomic write rechecks source inside the transaction and cannot partially replace records',async()=>{const h=await fixture();h.ctx.stale=await rows(h);await h.run('Store._set0("concurrent/edit",1)');const before=text(h,await rows(h));await assert.rejects(h.run('releaseStorage.write(Store.db,stale,[{key:"owner/custom",data:{value:0}}])'),/STALE_MIGRATION/);assert.equal(text(h,await rows(h)),before);});
test('failed persisted verification restores exact pre-migration KV state',async()=>{const h=await fixture(),before=text(h,await rows(h));await h.run('productionPreview()');h.run('const originalCapture=productionCapture;let reads=0;productionCapture=async()=>{const r=await originalCapture();if(++reads===2){const row=r.find(x=>x.key.startsWith("cat/")&&Object.keys(x.data.products).length);Object.values(row.data.products)[0].name="injected corruption";}return r;};');await assert.rejects(h.run('productionApply()'),/PROTECTED_DATA_CHANGED/);assert.equal(text(h,await h.run('releaseStorage.capture(Store.db)')),before);});
test('explicit data rollback restores catalog and binaries, saves rescue copy and keeps publication/feeds disabled',async()=>{const h=await fixture(),before=await rows(h);await migrated(h);h.run('S.products.get("p-a").name="later user edit";markProduct(S.products.get("p-a"))');await h.run('persist()');await h.run('productionRollback()');const after=await rows(h);h.ctx.before=before;h.ctx.after=after;assert.equal(h.run('stableValue105(productionProtected(productionRowsData(before)))===stableValue105(productionProtected(productionRowsData(after)))'),true);assert.equal(h.run('S.cfg.siteApi.auto'),false);assert.equal(h.downloads.length,2);assert.equal(h.run('PRODUCTION_MIGRATION.state'),'rolled-back');assert.equal(await after.find(x=>x.key==='docfile/proof').data.blob.text(),'binary certificate');});
test('empty migration never creates a blank migrated catalog',async()=>{const h=createHarness({runtime:true,production:true});await h.run('Store.init()');await assert.rejects(h.run('productionPreview()'),/EXISTING_DATABASE_EMPTY/);assert.equal((await rows(h)).length,0);});
test('missing binary for a referenced document blocks full migration backup',async()=>{const h=await fixture();await h.run('Store._del0("docfile/proof")');const before=text(h,await rows(h));await assert.rejects(h.run('productionPreview()'),/FULL_DOCUMENT_BACKUP_REQUIRED/);assert.equal(text(h,await rows(h)),before);});
test('corrupt archive bytes are rejected before restoration',async()=>{const h=await migrated(await fixture());await h.run('(async()=>{const backup=await releaseStorage.getBackup(PRODUCTION_MIGRATION.backupId);backup.blob=new Blob(["corrupt"]);window.badBackup=backup})()');await assert.rejects(h.run('releaseStorage.readBackup(badBackup)'),/BACKUP_CHECKSUM_FAILED/);});
test('production network is usable for PIM; raw sync requests stay blocked and the publisher refuses without negotiated contract v3; autoprices cannot start',async()=>{const h=await fixture();await assert.rejects(h.run('fetch("https://shop.invalid/pim/sync",{method:"POST"})'),/SYNC_DISABLED/);await assert.rejects(h.run('sitePublish("delta")'),/SYNC_DISABLED/);await assert.rejects(h.run('workflowFetchSource("supplier-a")'),/AUTOPRICES_DISABLED/);assert.equal(h.run('workflowSchedulerStart()'),false);assert.equal(h.run('siteAutoTick()'),false);await assert.rejects(h.run('fetch("https://pim-data.invalid/status")'),/Real network disabled in audit/);});
test('ordinary local feed import remains available after production migration and retains accepted inventory/size logic',async()=>{const h=await migrated(await fixture());h.ctx.inputRows=[['SKU','Name','Price','Stock','Size'],['feed-a','Штани Test',1000,3,'48']];h.run('S.imp={sup:"supplier-a",file:"local.csv",rows:inputRows,hdr:0,map:{sku:0,name:1,cost:2,stock:3,size:4}}');await h.run('doImport()');assert.equal(await h.run('applyImport()'),true);assert.equal(h.run('classificationAvailability(S.products.get("p-a"),S.products.get("p-a").variants[0]).payment_allowed'),true);assert.equal(h.run('S.products.get("p-a").pub'),true);assert.equal(h.run('S.products.size'),1);});

test('pending migration blocks persistence and server pulls, while retaining source flags and pending changes',async()=>{const h=await fixture(),before=text(h,await rows(h));await assert.rejects(h.run('persist()'),/MIGRATION_PENDING/);assert.equal((await h.run('sbPull()')).migration_pending,true);assert.equal(text(h,await rows(h)),before);});
test('portable recovery preserves IDs, original values and requires full document files',async()=>{const h=await fixture();h.ctx.d={format:'rubizh-pim-backup',cfg:h.run('S.cfg'),products:h.run('[...S.products.values()]'),docs:[]};const r=h.run('releaseStorage.portableRows(d)');h.ctx.r=r;assert.equal(h.run('productionRowsData(r).products[0].id'),'p-a');h.ctx.d.docs=[{id:'missing'}];assert.throws(()=>h.run('releaseStorage.portableRows(d)'),/FULL_DOCUMENT_BACKUP_REQUIRED/);});

test('a download click without owner confirmation cannot authorize migration',async()=>{const h=await fixture(),before=text(h,await rows(h));await h.run('productionPreview()');h.run('confirm=()=>false');await assert.rejects(h.run('productionApply()'),/EXTERNAL_BACKUP_REQUIRED/);assert.equal(text(h,await rows(h)),before);});
test('existing canonical IDs, aliases, supplier mappings and normalized catalogs/exceptions remain byte-equivalent',async()=>{const h=await fixture();h.run('classificationEnable();classificationApplyProduct(S.products.get("p-a"));const p=S.products.get("p-a");p.size_catalogs=[{catalog_id:"confirmed",allowed_sizes:["46","48"],scope:"MODEL"}];p.classification_exceptions=[{exception_id:"owner-confirmed",status:"RESOLVED",resolution:{confirmed:true}}];S.cfg.aliases={owner:"rule"};S.cfg.supplier_category_mapping={custom:{target:"clothing_pants"}};markAllDirty()');await h.run('productionPersist()');await h.run('productionLoad()');const before=h.run('structuredClone({categories:S.cfg.canonical_categories,catalogs:S.products.get("p-a").size_catalogs,exceptions:S.products.get("p-a").classification_exceptions,aliases:S.cfg.aliases,mapping:S.cfg.supplier_category_mapping})');await migrated(h);h.ctx.expected=before;assert.equal(h.run('stableValue105(expected)===stableValue105({categories:S.cfg.canonical_categories,catalogs:S.products.get("p-a").size_catalogs,exceptions:S.products.get("p-a").classification_exceptions,aliases:S.cfg.aliases,mapping:S.cfg.supplier_category_mapping})'),true);});
test('migration preserves existing PIM server connection and auth/CAS keys',async()=>{const h=await fixture();h.run('localStorage.setItem("rubizh_sb",JSON.stringify({url:"https://pim.invalid",anonKey:"fixture-key"}));localStorage.setItem("rubizh_sb_session",JSON.stringify({fixture:true}));localStorage.setItem("rubizh_sb_known",JSON.stringify({"meta/config":"version-1"}))');const before=['rubizh_sb','rubizh_sb_session','rubizh_sb_known'].map(k=>h.local.get(k));await migrated(h);assert.deepEqual(['rubizh_sb','rubizh_sb_session','rubizh_sb_known'].map(k=>h.local.get(k)),before);assert.equal(h.run('sbCfg().url'),'https://pim.invalid');});
test('production export retains separate submission/payment/confirmation contract v3',async()=>{const h=await migrated(await fixture());const feed=h.run('buildFeed()');assert.equal(feed.version,3);assert.equal(feed.review_only,false);assert.equal(feed.sync_enabled,false);const v=feed.products[0].variants[0];assert.equal(v.payment_allowed,true);assert.equal(v.requires_order_confirmation,false);assert.equal(v.order_submission_allowed,true);const {appRequire}=require('./isolated-harness.cjs'),schema=require('../contracts/category-size-export.schema.json'),validate=new(appRequire('ajv'))({strict:false}).compile(schema);assert.equal(validate(JSON.parse(JSON.stringify(h.run('classificationExport(S.products.get("p-a"))')))),true,JSON.stringify(validate.errors));});

test('explicit server restore cannot overwrite an existing local catalog',async()=>{const h=await fixture(),before=text(h,await rows(h));await assert.rejects(h.run('productionRestoreServer()'),/EXISTING_LOCAL_DATA/);assert.equal(text(h,await rows(h)),before);});
test('empty-device restore reads existing server only on explicit action and does not auto-migrate',async()=>{const h=createHarness({runtime:true,production:true});await h.run('productionLoad()');h.ctx.inputProduct=h.product();h.run('localStorage.setItem("rubizh_sb",JSON.stringify({url:"https://pim.invalid",anonKey:"fixture"}));const remoteRows=[{key:"meta/config",data:structuredClone(DEFAULT_CFG),updated_at:"2026-10-09T00:00:00Z"},{key:"cat/test",data:{products:{"p-a":inputProduct}},updated_at:"2026-10-09T00:00:00Z"}];sbFetch=async(path,opt={})=>{if(opt.method&&opt.method!=="GET")throw Error("REMOTE_WRITE_FORBIDDEN");return {json:async()=>path.includes("select=key,data,")?structuredClone(remoteRows):remoteRows.map(({key,updated_at})=>({key,updated_at}))}}');h.ctx.inputProduct=h.product();const r=await h.run('productionRestoreServer()');assert.equal(r.products,1);assert.equal(r.REMOTE_WRITES,0);assert.equal(h.run('PRODUCTION_MIGRATION.state'),'pending');assert.equal((await rows(h)).some(x=>x.key==='meta/production_release_10_9_3'),false);});

test('archived empty model aliases are carried over verbatim without forced categorization',async()=>{const h=await fixture();h.ctx.alias=h.product({id:'merged-alias',archived:true,archiveReason:'MODEL: объединена с p-a',variants:[]});h.run('S.products.set(alias.id,alias);markAllDirty()');await h.run('productionPersist()');await h.run('productionLoad()');const before=h.run('stableValue105(S.products.get("merged-alias"))');await migrated(h);assert.equal(h.run('stableValue105(S.products.get("merged-alias"))'),before);assert.equal(h.run('PRODUCTION_MIGRATION.lastReport.category.UNTOUCHED'),1);});
test('a second apply click during full backup cannot start another backup or migration',async()=>{const h=await fixture();await h.run('productionPreview()');let release;h.ctx.backupGate=new Promise(r=>release=r);h.run('const realEncodeForClickTest=releaseStorage.encodeBlob;releaseStorage.encodeBlob=async(...args)=>{await backupGate;return realEncodeForClickTest(...args)}');const handler=h.listeners.get('click').find(fn=>fn.toString().includes('data-release-action')),button=h.document.createElement('button');button.dataset.releaseAction='apply';const event={target:button,preventDefault(){},stopImmediatePropagation(){}};const first=handler(event);await handler(event);assert.equal(h.downloads.length,0);assert.equal(h.run('PRODUCTION_MIGRATION.busy'),true);release();await first;assert.equal(h.downloads.length,1);assert.equal(h.run('PRODUCTION_MIGRATION.busy'),false);assert.equal(h.run('PRODUCTION_MIGRATION.state'),'ready');});
