const {test}=require('node:test'),assert=require('node:assert/strict'),M=require('../lib/product-model.js'),C=require('../lib/categories.js'),{createHarness}=require('./isolated-harness.cjs');
for(const input of ['black','BLACK','чорний','черный'])test('color alias '+input,()=>assert.deepEqual(M.palette(input),{color:'Чорний',camouflage:null,unknown:[]}));
for(const input of ['olive','olive drab','олива'])test('olive alias '+input,()=>assert.equal(M.palette(input).color,'Олива'));
for(const input of ['Multicam','мультикам','MULTICAM'])test('camouflage separate '+input,()=>{const p=M.palette(input);assert.equal(p.color,null);assert.equal(p.camouflage,'Мультикам');});
test('pixel remains distinct from MM14 and woodland',()=>{assert.equal(M.palette('Піксель').camouflage,'Піксель');assert.equal(M.palette('ММ14').camouflage,'ММ14');assert.notEqual(M.palette('Піксель').camouflage,M.palette('ММ14').camouflage);assert.equal(M.palette('Multicam Black').camouflage,'Мультикам Black');});
test('one variant can have a color and camouflage',()=>assert.deepEqual(M.palette('Олива / Multicam'),{color:'Олива',camouflage:'Мультикам',unknown:[]}));
test('unknown patterns retained for review, not coerced',()=>assert.deepEqual(M.palette('MM15'),{color:null,camouflage:null,unknown:['MM15']}));
test('structured fields convert numbers and retain false',()=>{const a=M.attributes({'Об’єм':'30 л','MOLLE':'ні',Капюшон:'так',Матеріал:'Cordura'});assert.deepEqual(a.values,{volume_l:30,molle:false,hood:true,material:'Cordura'});});
test('contradictory aliases are omitted rather than arbitrarily chosen',()=>assert.deepEqual(M.attributes({material:'Cotton',Матеріал:'Nylon'}).conflicts,[{field:'material',raw:'Nylon'}]));
test('manual structured attributes win over supplier updates',()=>assert.equal(M.attributes({Матеріал:'Nylon'},{material:'Cordura'}).values.material,'Cordura'));
for(const [raw,type,system,value] of [['XXL','combat_shirt','clothing_alpha','2XL'],['M/L','gloves','gloves','M/L'],['42','boots','eu_shoes',42],['48-50','pants','clothing_numeric','48-50'],['56-58 см','helmet','helmet_cm','56-58']])test('size '+raw+' '+type,()=>{const z=M.size(raw,type);assert.equal(z.size_system,system);assert.equal(z.size_normalized,value);assert.equal(z.size_unconfirmed,false);assert.equal(z.size_raw,raw);});
for(const type of ['pants','boots','combat_shirt','helmet','gloves'])test('missing or fake one-size blocked for '+type,()=>{assert.equal(M.size('',type).size_unconfirmed,true);assert.equal(M.size('Один розмір',type).size_unconfirmed,true);assert.equal(M.size('Один розмір',type,{universalConfirmed:true}).size_unconfirmed,false);});
test('small accessories do not invent sizes',()=>{assert.equal(M.size('','pouch').size_unconfirmed,false);assert.equal(M.size('','pouch').size_display,null);});
test('manual incompatibility dominates positive and dimensional matches',()=>{const a={id:'a',primary_product_type:'plate_carrier',compatibility:{plate_size_supported:['25x30'],compatible_product_ids:['b'],incompatible_product_ids:['b']}},b={id:'b',primary_product_type:'armor_plate',compatibility:{plate_size:'25x30'}};assert.equal(M.compatibility(a,b).status,'incompatible');});
test('dimensional comparison handles cm and mm and reversible orientation',()=>{const a={id:'a',primary_product_type:'plate_carrier',compatibility:{plate_size_supported:['250x300 mm']}},b={id:'b',primary_product_type:'armor_plate',compatibility:{plate_size:'30x25 cm'}};assert.equal(M.compatibility(a,b).status,'compatible');assert.equal(M.compatibility(b,a).status,'compatible');b.compatibility.plate_size='20x25 cm';assert.equal(M.compatibility(a,b).status,'incompatible');});
test('missing compatibility data is unknown, never positive',()=>assert.equal(M.compatibility({id:'a',primary_product_type:'plate_carrier'},{id:'b',primary_product_type:'armor_plate'}).status,'unknown'));
test('radio connector mismatch detected',()=>assert.equal(M.compatibility({id:'a',primary_product_type:'radio',compatibility:{radio_connector:'Kenwood 2pin'}},{id:'b',primary_product_type:'radio_ptt',compatibility:{ptt_connector:'Motorola'}}).status,'incompatible'));
test('quality is completeness, independent from classifier confidence',()=>{const p={id:'a',name:'Рюкзак',brand:'TEST',canonical_category_id:'bags_backpacks',category_status:'CONFIRMED',category_confidence:.4,photos:['p'],desc:'Опис',attrs:{Матеріал:'Cordura'},variants:[{}]},v=[{site_price:100,availability:'in_stock'}];assert.equal(M.quality(p,v).quality_score,100);assert.equal(M.quality(p,v).publication_readiness,'READY');});
for(const [field,code] of [['photos','missing_photos'],['canonical_category_id','missing_category'],['name','missing_name']])test('critical field '+field+' blocks publication',()=>{const p={name:'Рюкзак',photos:['p'],canonical_category_id:'bags_backpacks',variants:[{}]};delete p[field];assert.ok(M.quality(p,[{site_price:100,availability:'in_stock'}]).critical_errors.includes(code));});
test('all unavailable variants block readiness without creating preorder',()=>{const p={name:'Рюкзак',photos:['p'],canonical_category_id:'bags_backpacks',variants:[{}]};const q=M.quality(p,[{site_price:100,availability:'out_of_stock'}]);assert.equal(q.publication_readiness,'BLOCKED');assert.ok(q.critical_errors.includes('missing_availability'));});
test('category review with last confirmed category can remain publishable',()=>{const p={name:'Рюкзак',photos:['p'],last_confirmed_category_id:'bags_backpacks',category_status:'NEEDS_REVIEW',variants:[{}]};const q=M.quality(p,[{site_price:100,availability:'in_stock'}]);assert.equal(q.publication_readiness,'READY_WITH_WARNINGS');assert.ok(q.warnings.includes('category_review'));});
test('duplicate detector only proposes; never combines variants',()=>{const p=[{id:'a',name:'Test',brand:'A',variants:[{offers:{s:{s:'SKU1'}}}]},{id:'b',name:'Test',brand:'A',variants:[{offers:{s:{s:'SKU1'}}}]}],before=JSON.stringify(p),d=M.duplicateCandidates(p);assert.equal(d.length,1);assert.equal(d[0].status,'POSSIBLE_DUPLICATE');assert.equal(JSON.stringify(p),before);});
test('taxonomy never turns color or brand into a category',()=>{const schema=M.filterSchema('footwear_boots');assert.ok(schema.includes('size'));assert.ok(schema.includes('color'));assert.ok(schema.includes('brand'));assert.equal(C.defaults.length,134);});
function fixture(){const h=createHarness();h.add(h.product({category:'Рюкзаки, сумки та баули / Рюкзаки',canonical_category_id:'bags_backpacks',last_confirmed_category_id:'bags_backpacks',category_source:'automatic',category_status:'CONFIRMED',catSource:'auto_name'}));h.run('S.cfg.category_engine={version:1,migration_validated:true};S.cfg.canonical_categories=RubizhCategories.defaults;');return h;}
function importRows(h,{stock=5,cost=1000,name='Рюкзак Test Pack',extra=[]}={}){h.ctx.rows=[['Артикул','Назва','Ціна','Stock','Категорія','Розмір','Колір','Фото','Опис','Модель','Бренд'],['feed-a',name,cost,stock,'Рюкзаки','','Олива','https://rubizh.shop/media/test.webp','Матеріал: Нейлон','TEST-PACK','TEST'],...extra];return h.run("runImport(S.cfg.suppliers[0],rows,0,{sku:0,name:1,cost:2,stock:3,category:4,size:5,color:6,photos:7,desc:8,model:9,brand:10},{file:'test.csv',headers:rows[0],zeroMissing:false})");}
test('model preview does not mutate a single product or config',()=>{const h=fixture(),before=h.run('stableValue105([S.cfg,[...S.products.values()]])');h.run('MODEL_UI.preview=modelPreview()');assert.equal(h.run('stableValue105([S.cfg,[...S.products.values()]])'),before);assert.equal(h.run('MODEL_UI.preview.rows.length'),1);});
test('normalization preserves raw, prices, stock, photos, IDs and can be restored',async()=>{const h=fixture();h.ctx.setTimeout=setTimeout;h.ctx.clearTimeout=clearTimeout;await h.run('Store.init();persist()');const before=h.run('JSON.stringify([...S.products.values()].map(p=>[p.id,p.name,p.photos,p.variants.map(v=>[v.sku,v.offers,v.price])]))');h.run('MODEL_UI.preview=modelPreview()');await h.run('modelApplyPreview()');assert.equal(h.run('modelEnabled()'),true);assert.equal(h.run('JSON.stringify([...S.products.values()].map(p=>[p.id,p.name,p.photos,p.variants.map(v=>[v.sku,v.offers,v.price])]))'),before);assert.ok(await h.run("Store.get('safety/before_product_model')"));assert.equal(h.run("S.products.get('p-a').variants[0].supplier_cost"),1000);await h.run("restoreSafetyKey('safety/before_product_model',false)");assert.equal(h.run('modelEnabled()'),false);assert.equal(h.run('JSON.stringify([...S.products.values()].map(p=>[p.id,p.name,p.photos,p.variants.map(v=>[v.sku,v.offers,v.price])]))'),before);});
test('stale preview cannot be applied after manual changes',async()=>{const h=fixture();h.run('MODEL_UI.preview=modelPreview();S.products.get("p-a").name="Changed"');await assert.rejects(h.run('modelApplyPreview()'),/Каталог змінився/);});
test('failed persistence restores catalog and model configuration',async()=>{const h=fixture();h.ctx.setTimeout=setTimeout;h.ctx.clearTimeout=clearTimeout;await h.run('Store.init();persist()');const before=h.run('JSON.stringify([...S.products.values()])');h.run('MODEL_UI.preview=modelPreview();requireBatchBackup=async()=>true;persist=async()=>false');await assert.rejects(h.run('modelApplyPreview()'),/не збережено/);assert.equal(h.run('JSON.stringify([...S.products.values()])'),before);assert.equal(h.run('modelEnabled()'),false);});
test('explicit category lock survives supplier update and stores suggestion',()=>{const h=fixture();h.run('S.products.get("p-a").category_locked=true');h.run("categoryApplyDecision(S.products.get('p-a'),RubizhCategories.classify({name:'Штани'}))");assert.equal(h.run("S.products.get('p-a').canonical_category_id"),'bags_backpacks');assert.equal(h.run("S.products.get('p-a').category_suggestion_id"),'clothing_pants');});
test('exact SKU rule stays scoped and below supplier mapping priority',()=>{const rules=[{id:'a1',supplier_id:'a',supplier_sku:'SKU1',canonical_category_id:'medical_ifak',confirmed:true}];assert.equal(C.classify({supplier_id:'a',supplier_sku:'SKU1',name:'ZX'},{productRules:rules}).canonical_category_id,'medical_ifak');assert.equal(C.classify({supplier_id:'b',supplier_sku:'SKU1',name:'ZX'},{productRules:rules}).canonical_category_id,null);assert.equal(C.classify({supplier_id:'a',supplier_sku:'SKU1',supplier_category_raw:'Z',name:'ZX'},{productRules:rules,mappings:[{supplier_id:'a',supplier_category_raw:'Z',canonical_category_id:'bags_backpacks',confirmed:true}]}).canonical_category_id,'bags_backpacks');});
test('repeat import preserves all manual normalized fields and relations',()=>{const h=fixture();h.run('Object.assign(S.products.get("p-a"),{marketing_name_uk:"Мій рюкзак",normalized_attributes:{material:"Cordura"},compatibility:{mount_standard:"TEST",compatible_product_ids:[],incompatible_product_ids:[]},relations:[{type:"recommended_with",product_id:"p-b"}],recommended_with:["p-b"],alternative_group:"PACKS",recommendation_locked:true,kit_eligible:false,kit_priority:90,category_locked:true});');const before=h.run('stableValue105(modelEditorValues(S.products.get("p-a")))');importRows(h);importRows(h);assert.equal(h.run('S.products.size'),1);assert.equal(h.run('S.products.get("p-a").variants.length'),1);assert.equal(h.run('stableValue105(modelEditorValues(S.products.get("p-a")))'),before);});
test('supplier raw text is retained on the offer and source description',()=>{const h=fixture();importRows(h,{name:'Рюкзак черный Test Pack'});assert.equal(h.run('S.products.get("p-a").variants[0].offers["supplier-a"].source_name_raw'),'Рюкзак черный Test Pack');assert.equal(h.run('S.products.get("p-a").variants[0].offers["supplier-a"].source_description'),'Матеріал: Нейлон');});
test('negative stock is recorded as invalid instead of becoming preorder',()=>{const h=fixture();importRows(h,{stock:-5});assert.equal(h.run('S.products.get("p-a").variants[0].offers["supplier-a"].invalid_stock'),true);assert.equal(h.run('modelVariant(S.products.get("p-a"),S.products.get("p-a").variants[0]).availability'),'out_of_stock');});
test('supplier price history records changes but repeated identical import is idempotent',()=>{const h=fixture();importRows(h,{cost:1010});const count=h.run('S.products.get("p-a").variants[0].price_history.length');assert.equal(count,1);importRows(h,{cost:1010});assert.equal(h.run('S.products.get("p-a").variants[0].price_history.length'),count);});
test('manager archive survives reimport',()=>{const h=fixture();h.run('Object.assign(S.products.get("p-a"),{archived:true,pub:false,archiveReason:"Ручний архів"})');importRows(h);assert.equal(h.run('S.products.get("p-a").archived'),true);assert.equal(h.run('S.products.get("p-a").pub'),false);});
test('supplier inactivity archive recovers when offer returns',()=>{const h=fixture();h.run('Object.assign(S.products.get("p-a"),{archived:true,pub:false,archivePrevPub:true,archiveReason:"Нет ни у одного поставщика"})');importRows(h);assert.equal(h.run('S.products.get("p-a").archived'),false);});
test('one name alone cannot combine unrelated cards',()=>{const h=fixture();h.ctx.items=['A','B'].map((s,i)=>({sup:'supplier-a',s,k:s,n:'Куртка Test',sz:i?'M':'S',rz:i?'M':'S',c:'Олива',rc:'Олива',attrs:{}}));assert.equal(h.run('buildGroups(items).length'),2);});
test('verified model plus matching name keeps variants in one group despite raw category change',()=>{const h=fixture();h.ctx.items=['A','B'].map((s,i)=>({sup:'supplier-a',s,k:s,m:'TEST-1',n:'Куртка Test',sz:i?'M':'S',rz:i?'M':'S',c:'Олива',rc:'Олива',rcat:i?'Unknown':'Куртки',attrs:{}}));assert.equal(h.run('buildGroups(items).length'),1);});
test('new SKU appends to an existing verified model, never creates a new card',()=>{const h=fixture();h.run('S.cfg.product_model_version=1;S.cfg.suppliers[0].auto=true;S.products.get("p-a").variants[0].offers["supplier-a"].source_model="TEST-PACK"');importRows(h,{extra:[['feed-b','Рюкзак Test Pack',1000,3,'Рюкзаки','','Чорний','https://rubizh.shop/media/test.webp','Матеріал: Нейлон','TEST-PACK','TEST']]});assert.equal(h.run('S.products.size'),1);assert.equal(h.run('S.products.get("p-a").variants.length'),2);});
test('more than 50 new variants are parked without losing rows or making a giant card',()=>{const h=fixture();h.run('S.products.clear();S.cfg.suppliers[0].auto=true;');const rows=Array.from({length:51},(_,i)=>['SKU-'+i,'Куртка Test',1000,5,'Куртки','S','Олива','https://rubizh.shop/test.webp','Матеріал: Нейлон','TEST-X','TEST']);const st=importRows(h,{extra:rows});assert.equal(h.run('[...S.products.values()].some(p=>p.variants.length>50)'),false);assert.ok(h.run('[...S.queue.values()].filter(q=>q.review?.type==="variant_explosion").length')>=51);assert.ok(st.variantExplosionBlocked>=1);});
test('feed sends authoritative fields while supplier raw and costs remain private',()=>{const h=fixture(),x=h.run('buildFeed().feed.products[0]');assert.equal(x.product_model_version,1);assert.equal(x.primary_product_type,'backpack');assert.equal(x.quality_score,100);assert.equal(x.filter_attributes.volume_l,30);assert.equal(x.variants[0].camouflage,null);assert.equal(x.variants[0].color,'Олива');assert.equal(x.variants[0].supplier_cost,undefined);assert.equal(x.source_description,undefined);assert.equal(x.source_name_raw,undefined);});
test('strict publication blocks fictitious clothing size and stock zero',()=>{const h=fixture();h.run('S.cfg.product_model_version=1;Object.assign(S.products.get("p-a"),{name:"Штани Test",canonical_category_id:"clothing_pants",last_confirmed_category_id:"clothing_pants"});bumpData()');assert.equal(h.run('buildFeed().feed.products.length'),0);});
test('site publication requires normalized model support before any POST',async()=>{const h=fixture();h.run('S.cfg.product_model_version=1;S.cfg.siteApi={url:"https://shop.test",key:"test"};var posts=[];siteFetch=async(path,opt)=>{posts.push({path,method:opt?.method||"GET"});return {ok:true,capabilities:{canonical_category_version:1}}};');await h.run('sitePublish("full")');assert.equal(h.run('posts.some(x=>x.method==="POST")'),false);assert.match(h.run('S.cfg.siteSync.lastError'),/product_model_version/);});
test('manual relation IDs reject missing products, self-links and contradictory relations',()=>{const h=fixture();h.run('var p=S.products.get("p-a");p.normalized_attributes={};p.compatibility={};p.recommended_with=[];p.relations=[{type:"compatible",product_id:"p-a"}]');assert.throws(()=>h.run('modelValidateEditor(p)'),/Некоректний/);});
test('new data view renders capped examples and actionable reasons',()=>{const h=fixture();h.run('MODEL_UI.preview=modelPreview()');const html=h.run('vDataModel()');assert.ok(html.includes('PREVIEW'));assert.ok(html.includes('APPLY'));assert.ok(html.includes('0–100'));assert.ok(html.includes('Не синхронізовано'));});

test('unitless plate dimensions do not prove compatibility',()=>assert.equal(M.compatibility({id:'a',primary_product_type:'plate_carrier',compatibility:{plate_size_supported:['25x30']}},{id:'b',primary_product_type:'armor_plate',compatibility:{plate_size:'25x30'}}).status,'unknown'));
test('numeric glove sizes are supported',()=>assert.equal(M.size('9','gloves').size_normalized,9));

test('card cache invalidates when stock, manual priority or marketing name changes',()=>{const h=fixture();h.run('modelView(S.products.get("p-a"));S.products.get("p-a").kit_priority=72;S.products.get("p-a").marketing_name_uk="Моя назва";S.products.get("p-a").variants[0].offers["supplier-a"].stock=0;S.products.get("p-a").variants[0].offers["supplier-a"].availability="out";markProduct(S.products.get("p-a"));');assert.equal(h.run('modelView(S.products.get("p-a")).kit_priority'),72);assert.equal(h.run('modelView(S.products.get("p-a")).marketing_name_uk'),'Моя назва');assert.equal(h.run('modelView(S.products.get("p-a")).publication_readiness'),'BLOCKED');});

test('undoing manual category change restores the automatic lock state',async()=>{const h=fixture();h.ctx.setTimeout=setTimeout;h.ctx.clearTimeout=clearTimeout;await h.run('Store.init();persist();');h.run('requireBatchBackup=async()=>true');const entry=await h.run('applyChanges("Test",[{pid:"p-a",field:"category",before:S.products.get("p-a").category,after:canonicalPath("bags_tactical")}])');assert.equal(h.run('S.products.get("p-a").category_locked'),true);h.ctx.entryId=entry.id;await h.run('undoMass(entryId)');assert.notEqual(h.run('S.products.get("p-a").category_locked'),true);assert.equal(h.run('S.products.get("p-a").canonical_category_id'),'bags_backpacks');});

test('source fit and clothing height are retained without inventing universal sizes',()=>{const a=M.size('2XL(LONG)','pants');assert.equal(a.size_normalized,'2XL');assert.equal(a.size_fit,'long');assert.equal(a.size_unconfirmed,false);const n=M.size('50/4','pants');assert.equal(n.size_system,'clothing_numeric');assert.equal(n.size_normalized,'50');assert.equal(n.size_height,'4');});
test('supplier named camouflage variants stay distinct',()=>{assert.equal(M.palette('Темний мультикам').camouflage,'Темний мультикам');assert.notEqual(M.palette('Темний мультикам').camouflage,M.palette('Multicam Black').camouflage);assert.equal(M.palette('Камуфляж').unknown.length,1);});


test('review filter matches dashboard and excludes stock-only blockers',()=>{const h=fixture();h.run('S.products.get("p-a").variants[0].offers["supplier-a"].stock=0;S.products.get("p-a").variants[0].offers["supplier-a"].availability="out";markProduct(S.products.get("p-a"));MODEL_UI.filter="review";');assert.equal(h.run('modelStats().counts.review'),0);assert.equal(h.run('modelRows().length'),0);assert.equal(h.run('modelView(S.products.get("p-a")).publication_readiness'),'BLOCKED');h.run('S.products.get("p-a").variants[0].color="UNRESOLVED COLOR";S.products.get("p-a").variants[0].offers["supplier-a"].native_color="UNRESOLVED COLOR";markProduct(S.products.get("p-a"));');assert.equal(h.run('modelStats().counts.review'),1);assert.equal(h.run('modelRows().length'),1);});
