const {test}=require('node:test'),assert=require('node:assert/strict'),{createHarness}=require('./isolated-harness.cjs'),Model=require('../lib/product-model.js');
for(const [raw,num,alpha] of [['48 M','48','M'],['44-46 (S)','44-46','S'],['52 (L)','52','L'],['60 2XL','60','2XL']])test('supplier numeric and letter size is already a valid clothing size: '+raw,()=>{const s=Model.size(raw,'pants');assert.equal(s.size_raw,raw);assert.equal(s.size_normalized,num);assert.equal(s.size_alpha,alpha);assert.equal(s.size_unconfirmed,false);});
test('combined clothing labels are not accepted as shoe or helmet sizes',()=>{for(const type of ['boots','shoes','helmet'])assert.equal(Model.size('48 M',type).size_unconfirmed,true);assert.equal(Model.size('48x52 см','pants').size_unconfirmed,true);});
test('ordinary colors are recognized while separate shades and unknown patterns stay separate',()=>{for(const raw of ['Червоний','Помаранчевий','Beige','Рожевий','Ranger Green','OD Green','Хакi','Камуфляж Піксель'])assert.equal(Model.palette(raw).unknown.length,0);assert.notEqual(Model.palette('Ranger Green').color,Model.palette('Olive').color);assert.notEqual(Model.palette('Beige').color,Model.palette('Coyote').color);assert.equal(Model.palette('Камуфляж').unknown[0],'Камуфляж');});
function fixture(){const h=createHarness();h.run('S.cfg.simple_mode_version=1;S.cfg.category_engine={version:1,migration_validated:true};S.cfg.bigPriceFrom=500;S.cfg.bigPriceMargin=15;');for(let i=0;i<3;i++){const p=h.product({id:'p-'+i,canonical_category_id:'bags_backpacks',last_confirmed_category_id:'bags_backpacks'});p.variants[0].sku='Q-'+i;p.variants[0].offers['supplier-a'].s='SUP-'+i;h.add(p);}return h;}
test('three automatic prices with one conflicting policy make one actionable question',()=>{const h=fixture(),tasks=h.run('simpleDecisions()');assert.equal(tasks.length,1);assert.equal(tasks[0].kind,'price_policy');assert.equal(tasks[0].ids.length,3);assert.ok(h.run('vSimplePublication()').includes('Публикация'));});
test('manual color alias overrides newly recognized dictionary spelling',()=>{const h=fixture();h.run('S.cfg.simple_color_aliases={"червоний":{value:"Мій кораловий",kind:"color"}};S.products.get("p-0").variants[0].color="Червоний";');assert.equal(h.run('simplePalette(S.products.get("p-0").variants[0]).color'),'Мій кораловий');});
test('blank historical size_raw does not erase a nonempty variant size; manual blank stays blank',()=>{const h=fixture();h.run('var p=S.products.get("p-0");p.primary_product_type="pants";p.canonical_category_id="clothing_pants";var v=p.variants[0];v.size="M";v.size_raw="";');assert.equal(h.run('simpleSize(p,v).size_normalized'),'M');h.run('v.manualFields={size:true};v.size="";v.size_raw="L";');assert.equal(h.run('simpleSize(p,v).size_unconfirmed'),true);});
test('price policy preview is nonmutating and does not change manual prices',()=>{const h=fixture();h.run('S.products.get("p-0").variants[0].price=1199;markProduct(S.products.get("p-0"));');const before=h.run('simpleFingerprint()'),plan=h.run('simplePricePolicyPreview()');assert.equal(h.run('simpleFingerprint()'),before);assert.equal(plan.rows.length,2);assert.ok(plan.rows.every(r=>r.after>r.before));});
test('apply one price rule stores a backup and preserves every supplier offer and manual price',async()=>{const h=fixture();h.ctx.setTimeout=setTimeout;h.ctx.clearTimeout=clearTimeout;h.run('S.products.get("p-0").variants[0].price=1199;markProduct(S.products.get("p-0"));');await h.run('Store.init();persist()');const before=h.run('stableValue105([...S.products.values()].flatMap(p=>p.variants))');h.run('SIMPLE_UI.pricePreview=simplePricePolicyPreview()');await h.run('simpleApplyPricePolicy()');assert.equal(h.run('S.cfg.bigPriceMargin'),25);assert.equal(h.run('stableValue105([...S.products.values()].flatMap(p=>p.variants))'),before);assert.ok(await h.run('Store.get("safety/before_pricing_30_25_20")'));assert.ok(h.run('calc(S.products.get("p-1"),S.products.get("p-1").variants[0]).margin>=25'));});
test('stale price policy preview refuses mutation',async()=>{const h=fixture();h.run('SIMPLE_UI.pricePreview=simplePricePolicyPreview();S.cfg.bigPriceFrom=900;S.cfgDirty=true;bumpData();');await assert.rejects(h.run('simpleApplyPricePolicy()'),/изменился/);assert.equal(h.run('S.cfg.bigPriceMargin'),15);});
