'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const XLSX=require('../vendor/xlsx-0.20.3.min.js'),{checkSource,runCompatibility}=require('../../audit/real-source-compatibility.cjs');
const rows=[['SKU','Name','Price','Stock','Size','Color','stock_observed_at','preorder'],['shoe-42','Тактичні черевики Test',1000,3,'42','Black','2026-10-01T12:00:00Z','false'],['shoe-range','Тактичні черевики Test',1000,0,'40–46','Olive','','true']];
test('compatibility is BLOCKED for all five without real originals; saved replay is not a PASS',async()=>{const r=await runCompatibility([]);assert.equal(r.REAL_SOURCE_COMPATIBILITY,'BLOCKED');assert.equal(r.production_autoprices_allowed,false);assert.equal(r.results.length,5);assert.ok(r.results.every(x=>!x.checks_executed));});
for(const ext of ['csv','xls','xlsx'])test('parser compatibility fixture '+ext+' exercises sheet/header, SKU, exact/range/color/stock/preorder',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pim-parser-fixture-'));try{const file=path.join(dir,'fixture.'+ext),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(rows),'Products');fs.writeFileSync(file,XLSX.write(wb,{bookType:ext,type:"buffer"}));const r=await checkSource({file,real_supplier_source:true,profile_confirmed:false});assert.equal(r.status,'NEEDS_PROFILE_CONFIRMATION');assert.equal(r.checks.rows,2);assert.equal(r.checks.exact_sizes,1);assert.equal(r.checks.size_ranges,1);assert.equal(r.checks.color_rows,2);assert.equal(r.checks.numeric_stock_rows,2);assert.equal(r.checks.explicit_preorder_rows,1);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('XML fixture preserves numerical stock, explicit preorder and observation timestamp; unknown size stays separate',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pim-xml-fixture-'));try{const file=path.join(dir,'fixture.xml');fs.writeFileSync(file,'<?xml version="1.0"?><yml_catalog><shop><offers><offer id="shoe-42"><name>Тактичні черевики Test</name><price>1000</price><stock>3</stock><stock_observed_at>2026-10-01T12:00:00Z</stock_observed_at><preorder>true</preorder><param name="size">42</param><param name="color">Black</param></offer></offers></shop></yml_catalog>');const r=await checkSource({file,real_supplier_source:true,profile_confirmed:false,mapping:{stock:'Stock'}});assert.equal(r.checks.numeric_stock_rows,1);assert.equal(r.checks.exact_sizes,1);assert.equal(r.checks.explicit_preorder_rows,1);assert.equal(r.checks.stock_observation_rows,1);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('Prom compatibility fixture reads supplier STATUS semantics without inventing quantities',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pim-prom-fixture-'));try{const file=path.join(dir,'fixture.csv');fs.writeFileSync(file,'SKU,Name,Price,Наявність\nA,Рюкзак Test,1000,+\nB,Рюкзак Test,1000,-\nC,Рюкзак Test,1000,!\nD,Рюкзак Test,1000,3\n');const r=await checkSource({file,supplier_id:'s2akya7xoafn',real_supplier_source:true,profile_confirmed:false});assert.equal(r.status,'NEEDS_PROFILE_CONFIRMATION');assert.equal(r.inventory_mode,'STATUS');assert.equal(r.checks.unknown_quantity_rows,4);assert.deepEqual(r.checks.availability,{IN_STOCK:2,OUT_OF_STOCK:1,PREORDER:1,ORDER_ON_REQUEST:0,UNKNOWN:0});}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('compatibility accepts absent stock column without pretending the feed proves availability',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pim-no-stock-fixture-'));try{const file=path.join(dir,'fixture.csv');fs.writeFileSync(file,'SKU,Name,Price\nA,Рюкзак Test,1000\n');const r=await checkSource({file,real_supplier_source:true,profile_confirmed:false});assert.equal(r.status,'NEEDS_PROFILE_CONFIRMATION');assert.equal(r.checks.availability.UNKNOWN,1);assert.equal(r.inventory_mode,'NO_AVAILABILITY_SIGNAL');}finally{fs.rmSync(dir,{recursive:true,force:true});}});
