const {test}=require('node:test'),assert=require('node:assert/strict');
const {createHarness}=require('./isolated-harness.cjs');
function simple(h,extra={}){h.add(h.product());h.ctx.settings=extra;h.run('Object.assign(S.cfg,{taxPct:0,acquiringPct:0,deliveryCost:0,extraCost:0,defaultMarkup:0,minMargin:24},settings);S.ui.quoteTarget=8;S.ui.quoteDon=false;bumpData();');}
for(const dimension of ['size','height'])test('shared supplier article preserves distinct '+dimension+' during merge',()=>{const h=createHarness(),a=h.product({id:'a'}),b=h.product({id:'b'});a.variants[0][dimension]='M';b.variants[0][dimension]='L';b.variants[0].sku='RUB-00002';for(const p of [a,b]){p.variants[0].offers['supplier-a'].sharedSku=true;h.add(p);}const r=h.run("(()=>{mergeDuplicateProductInto(S.products.get('a'),S.products.get('b'));return S.products.get('a').variants.map(v=>v.sku);})()");assert.deepEqual(Array.from(r),['RUB-00001','RUB-00002']);});
test('same shared variant still merges and retains SKU alias',()=>{const h=createHarness(),a=h.product({id:'a'}),b=h.product({id:'b'});b.variants[0].sku='RUB-00002';h.add(a);h.add(b);h.run("mergeDuplicateProductInto(S.products.get('a'),S.products.get('b'))");assert.equal(h.run("S.products.get('a').variants.length"),1);assert.ok(h.run("S.products.get('a').variants[0].skuAliases.includes('RUB-00002')"));});
test('automatic price ending in nine meets minimum margin and remains publishable',()=>{const h=createHarness(),p=h.product();p.variants[0].offers['supplier-a'].cost=p.variants[0].offers['supplier-a'].payout=1064;h.add(p);h.run("Object.assign(S.cfg,{defaultMarkup:0,minMargin:24,taxPct:0,acquiringPct:0,deliveryCost:0,extraCost:0,round:10,roundMode:'nine'});bumpData()");const c=h.run("calc(S.products.get('p-a'),S.products.get('p-a').variants[0])");assert.ok(c.margin>=24);assert.equal(c.lowMargin,false);assert.equal(c.price,1409);assert.equal(h.run('buildFeed().feed.products.length'),1);});
test('price rounding never crosses mandatory RRP floor',()=>{const h=createHarness();simple(h,{round:10,roundMode:'nine'});h.run("S.cfg.suppliers[0].terms.rrp='Да, обязательно';S.products.get('p-a').variants[0].offers['supplier-a'].rrp=2000;bumpData()");assert.ok(h.run("calc(S.products.get('p-a'),S.products.get('p-a').variants[0]).price")>=2000);});
test('quote accounts for order fixed expenses once and meets real net margin',()=>{const h=createHarness();simple(h,{deliveryCost:200,extraCost:100});const q=h.run("quoteCalc(quoteParse('RUB-00001 10'))");assert.equal(q.fixed,300);assert.ok(q.targetMet);assert.ok(q.profitPct>=8-1e-8);assert.ok(Math.abs(q.profit-(q.quoted-q.payout-300))<1e-8);});
test('quote cannot discount below mandatory RRP',()=>{const h=createHarness();simple(h);h.run("S.cfg.suppliers[0].terms.rrp='Да, обязательно';S.products.get('p-a').variants[0].offers['supplier-a'].rrp=2000;bumpData()");const q=h.run("quoteCalc(quoteParse('RUB-00001 1'))");assert.ok(q.quoted>=2000);assert.ok(q.targetMet);});
test('quote uses progressive donation settings and verifies margin after donation',()=>{const h=createHarness();simple(h,{donPct:3,donPctBig:7,donFrom:5000,donProgressive:true,donCapPct:20});h.run('S.ui.quoteDon=true');const q=h.run("quoteCalc(quoteParse('RUB-00001 10'))");h.ctx.q=q;assert.equal(q.donation,h.run('donationFor(q.quoted,q.quoted-q.payout-q.fees-q.fixed).donation'));assert.ok(q.targetMet);assert.ok(q.profitPct>=8-1e-8);});
test('unachievable quote margin disables client copy and explains reason',()=>{const h=createHarness();simple(h);h.run("S.products.get('p-a').variants[0].price=1000;S.ui.quoteText='RUB-00001 1';S.ui.quoteTarget=40;bumpData()");const q=h.run("quoteCalc(quoteParse(S.ui.quoteText))");assert.equal(q.targetMet,false);assert.match(h.run('vQuote()'),/маржа недосяжна/);assert.match(h.run('vQuote()'),/data-act="quoteCopy" disabled/);});
test('shared article is ambiguous in quote; primary RUB SKU resolves exact size',()=>{const h=createHarness(),p=h.product();p.variants[0].size='M';p.variants.push(structuredClone(p.variants[0]));p.variants[1].size='L';p.variants[1].sku='RUB-00002';h.add(p);assert.equal(h.run("quoteFindVariant('feed-a')"),null);assert.equal(h.run("quoteParse('feed-a 2')[0].ambiguous"),true);assert.equal(h.run("quoteFindVariant('RUB-00002').v.size"),'L');});
test('edit made while Supabase batch is prepared remains pending',async()=>{const h=createHarness();await h.run('Store.init()');await h.run("Store._set0('cat/a',{value:'old'});Store._set0('cat/b',{value:'b'});");h.run("sbReady=()=>true;SB.ver['cat/a']=1;SB.ver['cat/b']=1;sbSavePending(new Set(['cat/a','cat/b']));sbUploadDocs=async()=>{};sbWriteCAS104=async r=>({key:r.key,updated_at:'server-new'});const originalRead=Store._get0;Store._get0=async k=>{if(k==='cat/b'){await Store._set0('cat/a',{value:'new'});SB.ver['cat/a']++;const p=sbPending();p.add('cat/a');sbSavePending(p);}return originalRead(k);};");await h.run('sbPush()');assert.equal(h.run("sbPending().has('cat/a')"),true);});
test('missing document bytes prevent a supposedly complete downloaded backup',async()=>{const h=createHarness();await h.run('Store.init()');h.run("S.docs=new Map([['d-a',{id:'d-a',title:'Протокол',fileName:'protocol.pdf',remote:false}]]);sbReady=()=>false;");assert.equal(await h.run("backupDl('test')"),false);assert.equal(h.downloads.length,0);assert.equal(h.run('!!S.cfg.lastExternalBackup'),false);});
test('missing document bytes prevent a supposedly complete Drive backup before network',async()=>{const h=createHarness();await h.run('Store.init()');h.run("S.docs=new Map([['d-a',{id:'d-a',title:'Протокол',fileName:'protocol.pdf',remote:false}]]);sbReady=()=>false;driveFolderId=()=>{throw Error('NETWORK REACHED');};");await assert.rejects(h.run('uploadBackupToDrive()'),/Не найден файл документа/);});
test('custom dictionary takes precedence over built-in supplier title',()=>{const h=createHarness();h.run("const title=[...SOURCE_TITLES104.keys()].find(k=>!/[0-9<>]|\\bне\\b/iu.test(k));S.cfg.translationGlossary=ceParseGlossary(title+' => Власна назва');");assert.equal(h.run('autoUkText(title)'),'Власна назва');});
test('shared stock pool is counted once while separate pool rows are added',()=>{const h=createHarness(),p=h.product();p.variants.push(structuredClone(p.variants[0]));p.variants[0].size='M';p.variants[1].size='L';p.variants[1].sku='RUB-00002';for(const v of p.variants){v.offers['supplier-a'].sharedSku=true;v.offers['supplier-a'].native_size='M,L';}h.add(p);assert.equal(h.run("summary(S.products.get('p-a')).stock"),5);h.run("S.products.get('p-a').variants[0].offers['supplier-a'].native_size='M';S.products.get('p-a').variants[1].offers['supplier-a'].native_size='L';bumpData()");assert.equal(h.run("summary(S.products.get('p-a')).stock"),10);});
test('failed save preserves editor and original product for retry',async()=>{const h=createHarness();h.add(h.product());h.run("S.edit=structuredClone(S.products.get('p-a'));S.edit.name='Нова назва';readDrawer=()=>{};persist=async()=>false;");assert.equal(await h.run('saveProduct()'),false);assert.equal(h.run("S.products.get('p-a').name"),'Рюкзак Test Pack');assert.equal(h.run('S.edit.name'),'Нова назва');h.run('persist=async()=>true');assert.equal(await h.run('saveProduct()'),true);assert.equal(h.run("S.products.get('p-a').name"),'Нова назва');assert.equal(h.run('S.edit'),null);});
function matchedOptions(h,reason){const p=h.product();p.variants.push(structuredClone(p.variants[0]));p.variants[1].sku='RUB-00002';p.variants[1].offers['supplier-a'].s='feed-b';for(const v of p.variants){v.size='M';if(reason){v.source_review=true;v.source_review_reason=reason;}}h.add(p);return p;}
test('same size and colour in different cards is allowed without a collision',()=>{const h=createHarness();h.add(h.product());const p=h.product({id:'p-b',name:'Інший рюкзак'});p.variants[0].sku='RUB-00002';p.variants[0].offers['supplier-a'].s='feed-b';h.add(p);assert.equal(h.run('computeIssues().duplicateModels.length'),0);assert.equal(h.run('buildFeed().feed.products.length'),2);});
test('matching options inside one card are informational and both SKU are published',()=>{const h=createHarness();matchedOptions(h);assert.equal(h.run('computeIssues().duplicateModels.length'),1);assert.equal(h.run('S.issueCount'),0);assert.equal(h.run('buildFeed().feed.products[0].variants.length'),2);});
test('legacy duplicate_source flags alone no longer block publication or kit catalog',()=>{const h=createHarness();matchedOptions(h,'duplicate_source');assert.equal(h.run('buildFeed().feed.products[0].variants.length'),2);assert.equal(h.run('buildFeed().skipped.source_review'),0);assert.equal(h.run('pimKitProducts()[0].variants["1"].sku'),'RUB-00002');});
test('independent unconfirmed source review still blocks publication',()=>{const h=createHarness();matchedOptions(h,'unknown_measurements');assert.equal(h.run('buildFeed().feed.products.length'),0);assert.equal(h.run('buildFeed().skipped.source_review'),2);});
test('informational section is collapsed, non-error and explicitly limited to one card',()=>{const h=createHarness();matchedOptions(h);h.document.getElementById('view').innerHTML=h.run('vCheck()');const section=[...h.document.querySelectorAll('details')].find(d=>d.querySelector('summary')?.textContent.includes('Совпадения размера и цвета внутри одной карточки'));assert.ok(section);assert.equal(section.hasAttribute('open'),false);assert.equal(section.querySelector('.tag.bad'),null);assert.match(section.textContent,/не блокируют выгрузку/);assert.equal(h.run('S.issueCount'),0);});
test('price import keeps distinct articles without automatically requesting source review',()=>{const h=createHarness();matchedOptions(h);h.run(`(()=>{const headers=['sku','name','price','size','color','stock'];runImport(S.cfg.suppliers[0],[headers,['feed-a','Рюкзак Test Pack',1000,'M','Олива','В наявності'],['feed-b','Рюкзак Test Pack',1000,'M','Олива','В наявності']],0,{sku:0,name:1,cost:2,size:3,color:4,stock:5},{headers,zeroMissing:false,file:'synthetic'});})()`);assert.equal(h.run('[...S.products.values()].flatMap(p=>p.variants).filter(v=>v.source_review).length'),0);assert.equal(h.run('[...S.products.values()].flatMap(p=>p.variants).length'),2);});
test('price import does not overwrite an independent source review reason',()=>{const h=createHarness();matchedOptions(h,'unknown_measurements');h.run(`(()=>{const headers=['sku','name','price','size','color','stock'];runImport(S.cfg.suppliers[0],[headers,['feed-a','Рюкзак Test Pack',1000,'M','Олива','В наявності'],['feed-b','Рюкзак Test Pack',1000,'M','Олива','В наявності']],0,{sku:0,name:1,cost:2,size:3,color:4,stock:5},{headers,zeroMissing:false,file:'synthetic'});})()`);assert.equal(h.run('[...S.products.values()].flatMap(p=>p.variants).every(v=>v.source_review_reason==="unknown_measurements")'),true);});
