'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),{fixture}=require('./fixtures/model-v2.cjs'),{reconcile}=require('../lib/site-reconciliation-v2.cjs');
const V2=require('../lib/model-contract-v2.js'),{prepareReconciledSource,digestPHP}=require('../lib/site-reconciliation-v2.cjs');
function fullFixture(){
 const {source}=fixture();
 const tables={products:source.products.map(p=>({id:p.legacy_product_id,slug:p.legacy_product_id,name:p.protected.name,brand:p.protected.brand,description:p.protected.desc,visible:1})),variants:source.variants.map(v=>({sku:v.legacy_sku,product_id:v.legacy_product_id,price:v.price,size:v.size.normalized,color:v.protected.color,barcode:null,availability:'in',data:JSON.stringify({stock:v.stock,size_native:v.size.raw})})),photos:source.photos.map((p,i)=>({id:i+1,product_id:p.legacy_product_id,pos:0,src_url:p.url,status:'pending',file:'',thumb:''})),rubizh_product_categories:source.products.map(p=>({product_id:p.legacy_product_id,category_id:p.canonical_category_id,reason:'manual',locked:true})),rubizh_canonical_categories:source.categories.map(c=>({category_id:c.id,parent_id:c.parent_id,display_name_uk:c.name,status:'active'})),rubizh_category_aliases:[{legacy_id:'old-category',category_id:'clothing_jackets',filter_attributes:'{"manual":true}'}],rubizh_category_decisions:[{product_id:'old-black',locked:true}],rubizh_supplier_category_rules:[{id:'rule-1',locked:true}]};
 const site={export_version:'rubizh-model-source-v1',contains_customer_data:false,created_at:'2026-10-08T18:15:55+00:00',snapshot:{tables,meta:{taxonomy_version:'current'},asset_fingerprints:{taxonomy:'checked'},usable_photo_ids:[]}};
 function sign(){site.snapshot.fingerprints=Object.fromEntries(Object.entries(tables).map(([k,v])=>[k,digestPHP(v)]));}
 sign();return {source,site,tables,sign};
}
test('exact SKU and product identity recover site URLs and canonical IDs without title inference',()=>{const {source}=fixture();const site={export_version:'rubizh-model-source-v1',snapshot:{tables:{products:source.products.map(p=>({id:p.legacy_product_id,slug:p.legacy_product_id})),variants:source.variants.map(v=>({sku:v.legacy_sku,product_id:v.legacy_product_id,price:v.price,data:JSON.stringify({variant_id:'site-'+v.legacy_sku,stock:v.stock})})),rubizh_product_categories:source.products.map(p=>({product_id:p.legacy_product_id,canonical_category_id:p.canonical_category_id})),rubizh_category_decisions:[{product_id:'old-black',locked:true}]}}};const before=JSON.stringify({source,site}),r=reconcile(source,site);assert.equal(r.summary.matched_skus,6);assert.equal(r.summary.price_differences,0);assert.equal(r.summary.stock_differences,0);assert.equal(r.rows[0].canonical_category_id,'clothing_jackets');assert.equal(r.rows[0].legacy_url,'/product/old-black');assert.equal(r.protected_site_taxonomy.rubizh_category_decisions[0].locked,true);assert.equal(r.ready_for_migration,false);assert.equal(JSON.stringify({source,site}),before);});
test('visible-only API reading is marked partial; owner mismatch and price differences are explicit',()=>{const {source}=fixture();const r=reconcile(source,{items:[{id:'different',slug:'other',variants:[{sku:source.variants[0].legacy_sku,price:5000,stock:0}]}]});assert.equal(r.full_site_snapshot,false);assert.equal(r.summary.product_owner_conflicts,1);assert.equal(r.summary.price_differences,1);assert.equal(r.summary.pim_only_skus,5);assert.equal(r.ready_for_migration,false);});
test('equal missing quantities remain unknown rather than successful stock verification',()=>{
 const {source,site,tables,sign}=fullFixture();for(const v of source.variants)v.stock=null;for(const v of tables.variants)v.data=JSON.stringify({size_native:v.size});sign();
 const r=reconcile(source,site);assert.equal(r.summary.stock_compared,0);assert.equal(r.summary.stock_unknown_both,6);assert.equal(r.summary.stock_differences,0);assert.ok(r.rows.every(v=>v.stock_status==='UNKNOWN_BOTH'));assert.ok(r.warnings.some(w=>w.code==='QUANTITY_UNKNOWN'));
});
test('financial formatting differences preserve exact prices and measured stock',()=>{
 const {source,site,tables,sign}=fullFixture();for(const v of tables.variants){v.price=v.price+'.00';const data=JSON.parse(v.data);data.stock=String(data.stock)+'.0';v.data=JSON.stringify(data);}sign();
 const r=reconcile(source,site);assert.equal(r.summary.price_differences,0);assert.equal(r.summary.stock_differences,0);assert.equal(r.summary.price_compared,6);assert.equal(r.summary.stock_compared,6);
});
test('source preparation rejects a stale or tampered table fingerprint',()=>{
 const {source,site,tables}=fullFixture();tables.variants[0].price+=1;const r=reconcile(source,site);assert.equal(r.integrity.all_verified,false);assert.ok(r.errors.some(e=>e.code==='SITE_FINGERPRINT_MISMATCH'));assert.throws(()=>prepareReconciledSource(source,site),/fingerprint/);
});
test('union retains unmatched records, raw offers, current taxonomy and every photo without grouping',()=>{
 const {source,site,tables,sign}=fullFixture(),removed='old-multicam';
 tables.products=tables.products.filter(p=>p.id!==removed);tables.variants=tables.variants.filter(v=>v.product_id!==removed);tables.photos=tables.photos.filter(p=>p.product_id!==removed);tables.rubizh_product_categories=tables.rubizh_product_categories.filter(p=>p.product_id!==removed);
 tables.products.push({id:'new-site',slug:'new-site',name:'Куртка Archon Husky Extreme black',brand:'Archon',description:'Explicit site data',visible:1});tables.variants.push({sku:'NEW-SKU',product_id:'new-site',price:900,size:'M',color:'black',data:JSON.stringify({size_native:'M'}),availability:'in'});tables.photos.push({id:100,product_id:'new-site',pos:0,src_url:'https://images.test/new.jpg',status:'pending',file:''});tables.rubizh_product_categories.push({product_id:'new-site',category_id:'clothing_jackets'});sign();
 const before=JSON.stringify({source,site}),combined=prepareReconciledSource(source,site);assert.equal(JSON.stringify({source,site}),before);assert.equal(combined.products.length,4);assert.equal(combined.variants.length,7);assert.equal(combined.photos.length,6);
 assert.deepEqual(combined.products.find(p=>p.legacy_product_id==='old-black').protected,source.products[0].protected);assert.equal(combined.products.find(p=>p.legacy_product_id===removed).source_presence,'PIM_ONLY');assert.deepEqual(combined.taxonomy_state.current_site.tables.rubizh_category_aliases,tables.rubizh_category_aliases);assert.deepEqual(combined.taxonomy_state.current_site.tables.rubizh_category_decisions,tables.rubizh_category_decisions);assert.deepEqual(combined.taxonomy_state.current_site.tables.rubizh_supplier_category_rules,tables.rubizh_supplier_category_rules);assert.deepEqual(combined.taxonomy_state.pim_source_categories,source.categories);
 const added=combined.variants.find(v=>v.legacy_sku==='NEW-SKU');assert.equal(added.stock,null);assert.equal(added.availability,'HIDDEN');assert.equal(added.supplier_links_status,'UNKNOWN');
 const draft=V2.draft(combined),bundle=V2.build(combined,draft);assert.equal(draft.colors.length,0);assert.ok(draft.photo_mappings.every(p=>p.color_id===null));assert.equal(bundle.report.errors.length,0);assert.ok(Object.values(bundle.report.summary).every(n=>n===0));assert.equal(bundle.report.ready_for_migration,false);assert.equal(V2.publicExport(bundle).models.length,0);
});
test('a matching URL on a different product never assigns photo or color ownership',()=>{
 const {source,site,tables,sign}=fullFixture();tables.photos[0].src_url=source.photos[1].url;sign();const r=reconcile(source,site);assert.equal(r.photo_rows[0].status,'SITE_ONLY_REFERENCE');assert.equal(r.photo_rows[0].pim_photo_reference_ids.length,0);assert.equal(r.photo_rows[0].color_id,null);assert.equal(r.photo_rows[0].mapping_status,'UNKNOWN');
});
test('unverified public catalog and explicit category conflicts cannot prepare a migration source',()=>{
 const {source,site,tables,sign}=fullFixture();assert.throws(()=>prepareReconciledSource(source,{items:[]}),/complete/);source.products[0].canonical_category_id='different';assert.ok(reconcile(source,site).errors.some(e=>e.code==='PIM_SITE_CATEGORY_CONFLICT'));assert.throws(()=>prepareReconciledSource(source,site),/identity\/taxonomy/);
 source.products[0].canonical_category_id='clothing_jackets';tables.rubizh_canonical_categories[0].parent_id='clothing_jackets';sign();assert.ok(reconcile(source,site).errors.some(e=>e.code==='CATEGORY_CYCLE'));assert.throws(()=>prepareReconciledSource(source,site),/identity\/taxonomy/);
});
test('internal taxonomy records are preserved as source but cannot publish a confirmed model',()=>{
 const {source,site,tables,sign}=fullFixture();tables.rubizh_canonical_categories[1].status='internal';sign();assert.equal(reconcile(source,site).summary.internal_category_products,3);
 const combined=prepareReconciledSource(source,site);assert.equal(combined.categories.find(c=>c.id==='clothing_jackets').status,'internal');
 const {registry}=fixture();const bundle=V2.build(combined,registry);assert.ok(bundle.report.errors.some(e=>e.code==='CATEGORY_NOT_PUBLIC'));assert.equal(V2.publicExport(bundle).publication_blocked,true);
});
