const {test}=require('node:test'),assert=require('node:assert/strict');
const {createHarness}=require('./isolated-harness.cjs');
async function stored(h){await h.run('Store.init()');h.run('markAllDirty();workflowYield=async()=>{};');assert.equal(await h.run('persist()'),true);h.document.getElementById('toast').innerHTML='';}
function supplierFile(h,{cost=1100,headers=['sku','name','price','stock','description']}={}){const rows=[headers,['feed-a','Рюкзак Test Pack',cost,5,'Матеріал: Нейлон\nОб’єм: 30 л\nПосилена ручка.']];h.ctx.rows=rows;h.ctx.XLSX={read:()=>({SheetNames:['Sheet'],Sheets:{Sheet:{}}}),utils:{sheet_to_json:()=>rows}};h.ctx.fetch=async()=>new Response('synthetic price file',{status:200,headers:{'content-type':'application/octet-stream'}});return rows;}
function source(h,auto=false){h.run(`S.cfg.suppliers[0].source={url:'https://supplier.example/feed.xlsx',hours:24,enabled:true,autoApply:${auto}};`);if(auto)h.run("S.cfg.suppliers[0].source.profile={urlHash:fnvHash('https://supplier.example/feed.xlsx'),headers:fnvHash(JSON.stringify(rows[0])),map:{sku:0,name:1,cost:2,stock:3,desc:4},reviewedAt:Date.now()};");}
test('success toast waits for actual commit and overlapping writes are refused',async()=>{const h=createHarness();h.add(h.product());await stored(h);h.run("S.products.get('p-a').variants[0].offers['supplier-a'].priceAlert={cost:1500,payout:1500,rrp:0};const commitOriginal=Store.catalogCommit;Store.catalogCommit=async(...args)=>{await commitGate;return commitOriginal.apply(Store,args);};");let release;h.ctx.commitGate=new Promise(r=>release=r);const first=h.click('priceAccept',{pid:'p-a',vi:0,sid:'supplier-a'});await new Promise(r=>setImmediate(r));assert.ok(h.run('!!WORKFLOW.active'));assert.doesNotMatch(h.document.getElementById('toast').textContent,/Новая цена принята/);assert.deepEqual(await h.click('priceReject',{pid:'p-a',vi:0,sid:'supplier-a'}),[]);assert.match(h.document.getElementById('toast').textContent,/Дождитесь/);release();assert.deepEqual(await first,[]);assert.match(h.document.getElementById('toast').textContent,/Новая цена принята/);assert.equal(h.run('WORKFLOW.active'),null);});
test('failed write shows pending memory state, retains old persisted cost and can retry',async()=>{const h=createHarness();h.add(h.product());await stored(h);h.run("S.products.get('p-a').variants[0].offers['supplier-a'].priceAlert={cost:1500,payout:1500,rrp:0};const commitOriginal=Store.catalogCommit;Store.catalogCommit=async()=>{throw Error('Quota exceeded');};");await h.click('priceAccept',{pid:'p-a',vi:0,sid:'supplier-a'});assert.equal(h.run('WORKFLOW.unsaved'),true);assert.doesNotMatch(h.document.getElementById('toast').textContent,/Новая цена принята/);const old=await h.run("Store._get0('cat/'+bucketOf('p-a',NB))");assert.equal(old.products['p-a'].variants[0].offers['supplier-a'].cost,1000);assert.match(h.document.getElementById('workflow-status').textContent,/не сохранены/);h.run('Store.catalogCommit=commitOriginal');await h.click('wfRetrySave');const fresh=await h.run("Store._get0('cat/'+bucketOf('p-a',NB))");assert.equal(fresh.products['p-a'].variants[0].offers['supplier-a'].cost,1500);assert.equal(h.run('WORKFLOW.unsaved'),false);});
test('an action with a missing target explains that no data changed',async()=>{const h=createHarness();await h.click('priceAccept',{pid:'missing',vi:0,sid:'supplier-a'});assert.match(h.document.getElementById('toast').textContent,/Данные не изменились/);assert.doesNotMatch(h.document.getElementById('toast').textContent,/Новая цена принята/);});
test('matching sizes and colors are absent from the unified problem queue',()=>{const h=createHarness(),p=h.product();p.variants.push(structuredClone(p.variants[0]));p.variants[1].sku='RUB-00002';p.variants[1].offers['supplier-a'].s='feed-b';h.add(p);assert.equal(h.run('workflowProblems().length'),0);assert.equal(h.run('workflowProblemCount()'),0);});
test('one pending price change is actionable and not duplicated as missing price',()=>{const h=createHarness(),p=h.product();p.variants[0].offers['supplier-a'].priceAlert={cost:2000,fromCost:1000,changePct:100};h.add(p);assert.equal(h.run("workflowProblems().filter(x=>x.kind==='price').length"),1);assert.equal(h.run("workflowProblems().filter(x=>x.kind==='finance').length"),0);assert.match(h.run('vQueue()'),/Принять цену/);});
test('stale stock is grouped once per supplier',()=>{const h=createHarness();for(let i=0;i<3;i++){const p=h.product({id:'p-'+i});p.variants[0].sku='RUB-'+i;p.variants[0].offers['supplier-a'].s='feed-'+i;p.variants[0].offers['supplier-a'].at=Date.now()-100*3600000;h.add(p);}assert.equal(h.run("workflowProblems().filter(x=>x.kind==='stock').length"),1);});
test('confirmed manual manufacture supplies a real lead time; discontinued offer is unavailable',()=>{const h=createHarness(),p=h.product(),o=p.variants[0].offers['supplier-a'];Object.assign(o,{stock:0,availability:'out',preorder:true,preorderManual:true,productionDays:3});h.add(p);assert.equal(h.run("buildFeed().feed.products[0].variants[0].lead_time_days"),3);assert.equal(h.run("buildFeed().feed.products[0].variants[0].preorder_confirmed"),true);h.run("S.products.get('p-a').variants[0].offers['supplier-a'].discontinued=true;markProduct(S.products.get('p-a'))");assert.equal(h.run("calc(S.products.get('p-a'),S.products.get('p-a').variants[0]).avail"),'out');});
test('removing one discontinued supplier preserves a different live offer',()=>{const h=createHarness(),p=h.product();p.variants[0].offers['supplier-a'].discontinued=true;p.variants[0].offers['supplier-b']={s:'other',cost:1200,payout:1200,stock:2,availability:'in',at:Date.now()};h.add(p);h.run("S.cfg.suppliers.push({id:'supplier-b',name:'Другий',terms:{preorderDefault:'no',preorderConfirmed:true}});bumpData()");assert.equal(h.run("calc(S.products.get('p-a'),S.products.get('p-a').variants[0]).o.sid"),'supplier-b');});
test('source link validation rejects passwords, insecure and non-HTTP links',()=>{const h=createHarness();for(const url of ['http://supplier.example/file.xlsx','https://name:password@supplier.example/file.xlsx','file:///etc/passwd']){h.ctx.input=url;assert.throws(()=>h.run('workflowSourceURL(input)'));}});
test('HTML, empty and oversized responses never become import files',async()=>{const h=createHarness();for(const response of [new Response('<html>Login</html>',{headers:{'content-type':'text/html'}}),new Response(''),new Response('tiny',{headers:{'content-length':String(65*1024*1024)}})]){h.ctx.fetch=async()=>response;await assert.rejects(h.run("workflowDownloadSource('https://supplier.example/file.xlsx')"));assert.equal(h.run('S.snap'),null);}});
test('source download first stages a preview without changing the catalog',async()=>{const h=createHarness();h.add(h.product());supplierFile(h);source(h);await stored(h);const r=await h.run("workflowFetchSource('supplier-a')");assert.equal(r.status,'review');assert.equal(h.run('S.view'),'import');assert.equal(h.run("S.products.get('p-a').variants[0].offers['supplier-a'].cost"),1000);assert.equal(h.run('S.imp.zero'),false);});
test('reviewed source automatically updates and verifies storage without browser downloads',async()=>{const h=createHarness();h.add(h.product());supplierFile(h);source(h,true);await stored(h);const r=await h.run("workflowFetchSource('supplier-a')");assert.equal(r.status,'applied');assert.equal(h.run("S.products.get('p-a').variants[0].offers['supplier-a'].cost"),1100);const saved=await h.run("Store._get0('cat/'+bucketOf('p-a',NB))");assert.equal(saved.products['p-a'].variants[0].offers['supplier-a'].cost,1100);assert.equal(h.downloads.length,0);assert.ok(h.run("S.cfg.suppliers[0].source.lastApplied"));});
test('changed source headers require review even when automatic application is enabled',async()=>{const h=createHarness();h.add(h.product());supplierFile(h);source(h,true);h.ctx.rows[0][4]='new description column';await stored(h);const r=await h.run("workflowFetchSource('supplier-a')");assert.equal(r.status,'review');assert.equal(h.run("S.products.get('p-a').variants[0].offers['supplier-a'].cost"),1000);});
test('network failure leaves catalog untouched and adds an actionable source problem',async()=>{const h=createHarness();h.add(h.product());source(h);await stored(h);h.ctx.fetch=async()=>{throw new TypeError('Failed to fetch');};await assert.rejects(h.run("workflowFetchSource('supplier-a')"),/CORS/);assert.equal(h.run("S.products.get('p-a').variants[0].offers['supplier-a'].cost"),1000);assert.equal(h.run("workflowProblems().filter(x=>x.kind==='feed').length"),1);});
test('automatic refresh does not interrupt an open editor',async()=>{const h=createHarness();h.add(h.product());source(h);h.run("openProduct('p-a')");const r=await h.run("workflowFetchSource('supplier-a',{scheduled:true})");assert.equal(r.status,'busy');assert.equal(h.run('S.edit.id'),'p-a');});
test('final import draft is generated from normalized values and manual text stays protected',async()=>{const h=createHarness(),p=h.product({desc:'Мой ручной текст',fieldMeta:{desc:{source:'manual'}}});h.add(p);h.run("S.products.get('p-a').variants[0].offers['supplier-a'].at=1234;workflowYield=async()=>{};");const r=await h.run("workflowContentAfterImport([{sup:'supplier-a',at:1234}],true)");assert.equal(r.applied,0);assert.equal(h.run("S.products.get('p-a').desc"),'Мой ручной текст');});
test('confirmed manual manufacture remains available after stock data expires',()=>{const h=createHarness(),p=h.product(),o=p.variants[0].offers['supplier-a'];Object.assign(o,{stock:0,availability:'out',preorder:true,preorderManual:true,productionDays:3,at:Date.now()-100*3600000});h.add(p);assert.equal(h.run("calc(S.products.get('p-a'),S.products.get('p-a').variants[0]).avail"),'order');assert.equal(h.run("buildFeed().feed.products[0].variants[0].lead_time_days"),3);});
test('explicit stock-only exception overrides supplier preorder',()=>{const h=createHarness(),p=h.product();Object.assign(p.variants[0].offers['supplier-a'],{stock:0,availability:'order',preorder:false,preorderManual:true});h.add(p);assert.equal(h.run("offerAvail(S.products.get('p-a').variants[0].offers['supplier-a'])"),'out');});
test('a stale subset is not hidden by one fresh row of the same supplier',()=>{const h=createHarness(),p=h.product();p.variants.push(structuredClone(p.variants[0]));p.variants[1].sku='RUB-00002';p.variants[1].offers['supplier-a'].s='feed-b';p.variants[1].offers['supplier-a'].at=Date.now()-100*3600000;h.add(p);assert.equal(h.run("workflowProblems().filter(x=>x.kind==='stock').length"),1);});
test('CSV decoding preserves UTF-8 Cyrillic product names',()=>{const h=createHarness();let input;h.ctx.XLSX={read:(text)=>{input=text;return {};}};h.ctx.csv=new TextEncoder().encode('sku,name,price\na,Рюкзак,1000');h.run("workflowReadWorkbook(csv,'price.csv')");assert.match(input,/Рюкзак/);});
test('source download status is not success when a supplier file is missing',async()=>{const h=createHarness();h.add(h.product());source(h);await stored(h);h.ctx.fetch=async()=>new Response('missing',{status:404});await h.click('wfFetchSource',{sid:'supplier-a'});assert.equal(h.run('WORKFLOW.last.kind'),'error');assert.match(h.run('WORKFLOW.last.text'),/HTTP 404/);});
test('manual review records the selected Excel sheet and actual header row',()=>{const h=createHarness();supplierFile(h);source(h);h.run("S.imp={sup:'supplier-a',sourceId:'supplier-a',sourceURLHash:fnvHash(S.cfg.suppliers[0].source.url),sourceHeaders:'old-header',sheet:'Prices',hdr:1,rows:[['Title'],['sku','name','price','stock']],map:{sku:0,name:1,cost:2,stock:3}};workflowRecordSourceProfile(S.imp,false)");assert.equal(h.run('S.cfg.suppliers[0].source.profile.sheet'),'Prices');assert.equal(h.run('S.cfg.suppliers[0].source.profile.hdr'),1);assert.equal(h.run('S.cfg.suppliers[0].source.profile.headers'),h.run("fnvHash(JSON.stringify(['sku','name','price','stock']))"));});
test('automatic parsing uses the reviewed Excel sheet instead of the first sheet',async()=>{const h=createHarness();supplierFile(h);source(h,true);h.run("Object.assign(S.cfg.suppliers[0].source.profile,{sheet:'Prices',hdr:1,headers:fnvHash(JSON.stringify(rows[0]))})");const rows=h.ctx.rows;h.ctx.XLSX={read:()=>({SheetNames:['Info','Prices'],Sheets:{Info:'info',Prices:'prices'}}),utils:{sheet_to_json:sheet=>sheet==='prices'?[['Supplier title'],...rows]:[['Not a price'],['contact']]}};const parsed=await h.run("workflowParseSource({blob:new Blob(['binary']),url:S.cfg.suppliers[0].source.url},S.cfg.suppliers[0])");assert.equal(parsed.sheet,'Prices');assert.equal(parsed.hdr,1);assert.equal(parsed.sourceProfileValid,true);});
test('changing the supplier during manual review never confirms the original source profile',()=>{const h=createHarness();source(h);h.run("workflowRecordSourceProfile({sup:'different',sourceId:'supplier-a',map:{}},false)");assert.equal(h.run('S.cfg.suppliers[0].source.profile'),undefined);});
test('enabled content automation refreshes approved generated text after supplier facts change',async()=>{const h=createHarness();h.add(h.product());h.run("const p=S.products.get('p-a');p.contentDraft=ceGenerate(p);ceApply(p);p.fieldMeta.desc.supplierValue='<p>Матеріал: Нейлон</p><p>Об’єм: 40 л</p>';p.attrs['Об’єм']='40 л';p.variants[0].offers['supplier-a'].at=1234;workflowYield=async()=>{};");const r=await h.run("workflowContentAfterImport([{sup:'supplier-a',at:1234}],true)");assert.equal(r.applied,1);assert.match(h.run("S.products.get('p-a').desc"),/40 л/);assert.equal(h.run("ceAccepted(S.products.get('p-a'))"),true);});
test('draft-only automation leaves approved generated text unchanged',async()=>{const h=createHarness();h.add(h.product());h.run("const p=S.products.get('p-a');p.contentDraft=ceGenerate(p);ceApply(p);p.fieldMeta.desc.supplierValue='<p>Матеріал: Нейлон</p><p>Об’єм: 40 л</p>';p.attrs['Об’єм']='40 л';p.variants[0].offers['supplier-a'].at=1234;workflowYield=async()=>{};");const before=h.run("S.products.get('p-a').desc");const r=await h.run("workflowContentAfterImport([{sup:'supplier-a',at:1234}],false)");assert.equal(r.applied,0);assert.equal(h.run("S.products.get('p-a').desc"),before);assert.match(h.run("S.products.get('p-a').contentDraft.html"),/40 л/);});
test('brief notifications replace prior messages instead of covering the page with a stack',()=>{const h=createHarness();h.run("toast('Первое');toast('Второе');toast('Последнее')");assert.equal(h.document.getElementById('toast').children.length,1);assert.equal(h.document.getElementById('toast').textContent,'Последнее');});
